using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Windows.Forms;
using EmulatorHub;
class AuditTests {
 static int checks;static void Check(bool c,string name){if(!c)throw new Exception(name);checks++;}static void Pump(int ms){var w=Stopwatch.StartNew();while(w.ElapsedMilliseconds<ms){Application.DoEvents();Thread.Sleep(5);}}
 static T Field<T>(object o,string n){return (T)o.GetType().GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(o);}
 [STAThread]static int Main(){try{Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException);Application.EnableVisualStyles();return Run();}catch(Exception ex){Console.Error.WriteLine(ex);return 1;}}
 static int Run(){foreach(var reference in typeof(MainForm).Assembly.GetReferencedAssemblies()){Check(Assembly.Load(reference)!=null,"framework dependency loads: "+reference.Name);}Check(typeof(MainForm).Assembly.GetName().Version.ToString()=="1.29.3.0","release assembly version");var d=Store.Load();d.Games=new List<GameEntry>();d.Emulators=new List<EmulatorProfile>();d.Collections=new List<GameCollection>();d.Experience=new ExperienceSettings();d.UserTools=null;NextData.Ensure(d);LibraryAdditions.Ensure(d);File.WriteAllText("stress.rom","fixture");File.WriteAllText("invalid.png","not an image");string path=Path.GetFullPath("stress.rom");for(int i=0;i<10000;i++)d.Games.Add(new GameEntry{Id="stress"+i,Title="Stress "+i.ToString("00000"),Path=path,Tags=new List<string>()});
  using(var f=new GameLibraryDialog(d)){f.ShowInTaskbar=false;f.StartPosition=FormStartPosition.Manual;f.Location=new Point(-3000,-3000);var watch=Stopwatch.StartNew();f.Show();Pump(100);watch.Stop();var list=Field<ListView>(f,"games");Check(list.Items.Count==10000,"10000 game rows construct");Console.WriteLine("10000-game construction including message pumping: "+watch.ElapsedMilliseconds+" ms");var row=list.Items[55];row.Selected=true;var remove=d.Games[2];d.Games.RemoveAt(2);f.ReloadLibrary();Check(list.Items.Count==9999&&list.SelectedItems[0]==row,"removal preserves unaffected selection");d.Games.Add(new GameEntry{Id="inserted",Title="AAA first",Path=path,Tags=new List<string>()});f.ReloadLibrary();Check(list.Items[0].Text=="AAA first","insert reorders correctly");list.Items[0].Selected=true;d.Games[55].Pinned=true;f.ReloadLibrary();Check(list.SelectedItems.Count==2,"refresh preserves multiple selected games");}
  Check(UserTools.Copy(d).Games.Count==10000,"large library clone stays compatible");string largeJson=Json.Serialize(d);Check(largeJson.Length>2*1024*1024,"stress data exceeds old serializer limit");Check(Json.Deserialize<LibraryData>(largeJson).Games.Count==10000,"large restore reader supports current storage limit");using(var thumbnail=GameLibraryDialog.MakeThumbnail(Path.GetFullPath("invalid.png"),"Fallback",96)){Check(thumbnail.Width==96&&thumbnail.Height==96,"corrupt artwork gets fallback thumbnail");}using(var file=File.Open("invalid.png",FileMode.Open,FileAccess.ReadWrite,FileShare.None)){Check(file.Length>0,"thumbnail loader releases source file");}
  d.Games=d.Games.Take(20).ToList();d.UserTools=null;d.Experience.LibraryView="Artwork";for(int cycle=0;cycle<20;cycle++){foreach(var game in d.Games)game.ArtworkPath=cycle%2==0?Path.GetFullPath("invalid.png"):null;using(var f=new GameLibraryDialog(d)){f.ShowInTaskbar=false;f.StartPosition=FormStartPosition.Manual;f.Location=new Point(-3000,-3000);f.Show();Pump(35);f.ReloadLibrary();Check(Field<ImageList>(f,"coverImages").Images.Count>=1,"artwork startup/reload cycle "+cycle);}}Pump(200);Check(Application.OpenForms.Count==0,"artwork disposal leaves no windows");
  if(File.Exists("FishBowl Setup.exe")){var assembly=Assembly.LoadFrom("FishBowl Setup.exe");using(var form=(Form)Activator.CreateInstance(assembly.GetType("FishBowlSetup.SetupForm"),true)){form.ShowInTaskbar=false;form.StartPosition=FormStartPosition.Manual;form.Location=new Point(-3000,-3000);form.Show();Pump(100);Check(NextUi.Descendants(form).OfType<Label>().Any(label=>label.Text.Contains("1.29.3")),"installer UI constructs with current version");using(var bmp=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bmp,new Rectangle(Point.Empty,bmp.Size));bmp.Save("installer-preview.png");}}}
  using(var main=new MainForm(true)){UserTools.ActiveLaunches=1;bool blocked=false;try{typeof(MainForm).GetMethod("ImportLibrary",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(main,null);}catch(TargetInvocationException ex){blocked=ex.InnerException is IOException;}UserTools.ActiveLaunches=0;Check(blocked,"settings import blocked during tracked session");}
  Store.Save(d);Check(Store.Load().Games.Count==d.Games.Count,"data still persists after stress cycles");Console.WriteLine("PASS: "+checks+" audit checks covering framework dependencies, 10000 games, inserts/removals, selection, damaged images, artwork disposal and installer construction.");return 0;
 }
}
