using System; using System.Collections.Generic; using System.IO; using System.Linq; using EmulatorHub;
class GameToolsTests {
 static int checks;
 static void Check(bool condition,string label) { checks++;if(!condition)throw new Exception(label); }
 static void Reject(Action action,string label) { bool rejected=false;try{action();}catch(IOException){rejected=true;}Check(rejected,label); }
 static int Main() { try { Run();NativeLaunchIntegration();Console.WriteLine("PASS: "+checks+" game tools checks.");return 0; } catch(Exception e){Console.WriteLine(e);return 1;} }
 static void NativeLaunchIntegration() {
  string folder=Path.Combine(Path.GetTempPath(),"FishBowlNativeLaunch-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(folder);string exe=Path.Combine(folder,"Native game.exe");File.WriteAllText(exe,"fixture");GameEntry game=GameTools.NativeEntry(exe,"Native game");game.Arguments="--test";LibraryData library=new LibraryData { Games=new List<GameEntry>{game},Emulators=new List<EmulatorProfile>() };
  EmulatorProfile launch=NextData.LaunchEmulator(library,game);Check(launch!=null&&launch.Executable==exe,"native game launch profile works without registered emulators");Check(GameSessions.Validate(library,game)=="--test","native validation accepts literal args without registered emulator");game.Arguments="{game}";Reject(delegate{GameSessions.Validate(library,game);},"native launch rejects emulator argument templates");game.Arguments="";game.Extras.WorkingDirectory=Path.Combine(folder,"missing");Reject(delegate{GameSessions.Validate(library,game);},"native launch rejects missing working folder");game.Extras.WorkingDirectory=folder;File.Delete(exe);Reject(delegate{GameSessions.Validate(library,game);},"native launch validates executable existence");
 }
 static void Run() {
  string root=Path.Combine(Path.GetTempPath(),"FishBowlGameTools-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
  string src=Path.Combine(root,"mod"),dst=Path.Combine(root,"game"),backup=Path.Combine(root,"backups");Directory.CreateDirectory(src);Directory.CreateDirectory(dst);
  File.WriteAllText(Path.Combine(src,"settings.ini"),"mod");File.WriteAllText(Path.Combine(dst,"settings.ini"),"original");Directory.CreateDirectory(Path.Combine(src,"nested"));File.WriteAllText(Path.Combine(src,"nested","new.txt"),"new");
  var p=new ModProfile { Name="Test",SourceFolder=src,DestinationFolder=dst };var review=GameTools.PreviewMod(src,dst);Check(review.Count==2&&review.Count(x=>x.Existed)==1,"review differentiates added and replaced files");Check(File.ReadAllText(Path.Combine(dst,"settings.ini"))=="original","preview never changes destination");
  File.WriteAllText(Path.Combine(src,"settings.ini"),"changed");Reject(delegate { GameTools.ApplyMod(p,review,backup); },"stale review rejected");Check(!p.Applied,"rejected review cannot apply");review=GameTools.PreviewMod(src,dst);GameTools.ApplyMod(p,review,backup);Check(p.Applied&&File.ReadAllText(Path.Combine(dst,"settings.ini"))=="changed","reviewed overlay applied");Check(File.ReadAllText(Path.Combine(p.BackupFolder,"settings.ini"))=="original","original preserved");
  File.WriteAllText(Path.Combine(dst,"settings.ini"),"user edit");Reject(delegate { GameTools.RollbackMod(p); },"rollback protects post-install edits");Check(File.Exists(Path.Combine(dst,"nested","new.txt")),"blocked rollback performs no deletions");File.WriteAllText(Path.Combine(dst,"settings.ini"),"changed");GameTools.RollbackMod(p);Check(!p.Applied&&File.ReadAllText(Path.Combine(dst,"settings.ini"))=="original","rollback restores original");Check(!File.Exists(Path.Combine(dst,"nested","new.txt")),"rollback removes only added file");Check(File.Exists(Path.Combine(p.BackupFolder,"settings.ini")),"backup retained after rollback");
  Reject(delegate{GameTools.PreviewMod(src,src);},"source destination overlap rejected");Reject(delegate{GameTools.PreviewMod(src,Path.Combine(src,"nested"));},"nested destination rejected");
  GameTools.ApplyMod(p,GameTools.PreviewMod(src,dst),backup);var first=p.Files[0];string rel=first.RelativePath;first.RelativePath="../escape";Reject(delegate{GameTools.ValidateRollback(p);},"tampered manifest traversal rejected");first.RelativePath=rel;
  first= p.Files.First(x=>x.Existed);File.WriteAllText(Path.Combine(p.BackupFolder,first.RelativePath),"tamper");Reject(delegate{GameTools.RollbackMod(p);},"altered backup rejected before write");Check(File.ReadAllText(Path.Combine(dst,"settings.ini"))=="changed","altered backup never restored");
  string safeSrc=Path.Combine(root,"safe mod"),safeDst=Path.Combine(root,"safe game");Directory.CreateDirectory(safeSrc);Directory.CreateDirectory(safeDst);File.WriteAllText(Path.Combine(safeSrc,"existing.txt"),"patched");File.WriteAllText(Path.Combine(safeSrc,"added.txt"),"added");File.WriteAllText(Path.Combine(safeDst,"existing.txt"),"original");ModProfile safe=new ModProfile{SourceFolder=safeSrc,DestinationFolder=safeDst};int checkpoints=0;string journal=null;GameTools.ApplyMod(safe,GameTools.PreviewMod(safeSrc,safeDst),backup,delegate{checkpoints++;journal=Json.Serialize(safe);});Check(checkpoints==3&&journal!=null,"mod journal persists state before every file mutation");ModProfile recovered=Json.Deserialize<ModProfile>(journal);File.WriteAllText(Path.Combine(safeDst,"existing.txt"),"original");File.Delete(Path.Combine(safeDst,"added.txt"));GameTools.RollbackMod(recovered);Check(!recovered.Applied&&recovered.Files.Count==0&&File.ReadAllText(Path.Combine(safeDst,"existing.txt"))=="original","rollback resumes after restore succeeds before journal save");ModProfile malicious=Json.Deserialize<ModProfile>(journal);malicious.Files[0].RelativePath="folder. /file.txt";Reject(delegate{GameTools.ValidateRollback(malicious);},"Windows trailing-space path aliases rejected");malicious.Files[0].RelativePath="NUL.txt";Reject(delegate{GameTools.ValidateRollback(malicious);},"Windows device paths rejected");
  string apps=Path.Combine(root,"steamapps");Directory.CreateDirectory(Path.Combine(apps,"common","Example"));File.WriteAllText(Path.Combine(apps,"appmanifest_10.acf"),"\"AppState\" { \"appid\" \"10\" \"name\" \"Example Game\" \"installdir\" \"Example\" }");File.WriteAllText(Path.Combine(apps,"appmanifest_11.acf"),"\"appid\" \"11\" \"name\" \"Escape\" \"installdir\" \"../outside\"");var steam=GameTools.SteamGames(root);Check(steam.Count==1&&steam[0].Title=="Example Game"&&steam[0].AppId=="10","Steam manifests discover installed games and reject traversal");
  string exe=Path.Combine(root,"game.exe");File.WriteAllText(exe,"fixture");var native=GameTools.NativeEntry(exe,"Custom title");Check(native.Extras.Native&&native.TitleIsCustom&&native.Path==exe&&native.Extras.WorkingDirectory==root,"PC launch entry retains title and working directory");Reject(delegate { GameTools.NativeEntry(Path.Combine(src,"settings.ini"),"bad"); },"non-executable native import rejected");
  var totals=GameTools.Monthly(new[]{new PlaySession{GameId="a",StartedAt="2026-01-03T00:00:00Z",Seconds=3600},new PlaySession{GameId="b",StartedAt="2026-01-04T00:00:00Z",Seconds=-20},new PlaySession{GameId="a",StartedAt="invalid",Seconds=100},new PlaySession{GameId="a",StartedAt="2026-02-04T00:00:00Z",Seconds=120}});Check(totals.Count==2&&totals[0].Month=="2026-02","monthly analytics ordered and invalid dates skipped");Check(totals[1].Seconds==3600&&totals[1].Games==2&&totals[1].Sessions==2,"monthly analytics count unique games and clamp negative duration");
  string original=Path.Combine(root,"original.rom"),patch=Path.Combine(root,"test.ips"),patched=Path.Combine(root,"patched.rom");File.WriteAllBytes(original,new byte[]{1,2,3,4});File.WriteAllBytes(patch,new byte[]{80,65,84,67,72,0,0,1,0,2,8,9,69,79,70});GameTools.CreateIpsPatchedCopy(original,patch,patched);Check(File.ReadAllBytes(patched).SequenceEqual(new byte[]{1,8,9,4})&&File.ReadAllBytes(original).SequenceEqual(new byte[]{1,2,3,4}),"IPS copy patches data without changing original");Reject(delegate{GameTools.CreateIpsPatchedCopy(original,patch,patched);},"IPS cannot overwrite existing files");File.WriteAllBytes(patch,new byte[]{80,65,84,67,72,0,0,0,0,0,0,3,7,69,79,70});string repeated=Path.Combine(root,"repeat.rom");GameTools.CreateIpsPatchedCopy(original,patch,repeated);Check(File.ReadAllBytes(repeated).SequenceEqual(new byte[]{7,7,7,4}),"IPS repeated records supported");File.WriteAllBytes(patch,new byte[]{80,65,84,67,72,0,0,0,0,4,1});string invalid=Path.Combine(root,"invalid.rom");Reject(delegate{GameTools.CreateIpsPatchedCopy(original,patch,invalid);},"truncated IPS rejected");Check(!File.Exists(invalid),"invalid patch never produces output");
  string json=Json.Serialize(new GameToolsSettings { ModProfiles=new List<ModProfile>{p},MediaLinks=new List<GameMediaLink>{new GameMediaLink{Label="Manual",Path="manual.pdf",Kind="Manual"}} });var restored=Json.Deserialize<GameToolsSettings>(json);Check(restored.ModProfiles[0].Files.Count==2&&restored.MediaLinks[0].Label=="Manual","profile backups and media survive saved JSON");
 }
}
