using System;using System.IO;using System.IO.Compression;using System.Linq;using System.Collections.Generic;using System.Drawing;using System.Windows.Forms;using System.Threading;using EmulatorHub;
class Tests
{
 static int checks;static void Check(bool result,string message){checks++;if(!result)throw new Exception(message);}
 static void Throws(Action action,string message){bool threw=false;try{action();}catch(Exception){threw=true;}Check(threw,message);}
 static void RenderModal(Action work,string expected,string filename)
 {using(var timer=new System.Windows.Forms.Timer{Interval=300}){timer.Tick+=delegate{var dialog=Application.OpenForms.Cast<Form>().FirstOrDefault(f=>f.Text==expected&&f.Visible);if(dialog==null)return;dialog.StartPosition=FormStartPosition.Manual;dialog.Location=new Point(-3000,-3000);Application.DoEvents();using(var bitmap=new Bitmap(dialog.Width,dialog.Height)){dialog.DrawToBitmap(bitmap,new Rectangle(0,0,bitmap.Width,bitmap.Height));bitmap.Save(filename);}timer.Stop();dialog.Close();};timer.Start();work();}}
 [STAThread]static int Main(){try{return Run();}catch(Exception e){Console.WriteLine(e);return 1;}}
 static int Run()
 {
  Application.EnableVisualStyles();string root=Path.Combine(Path.GetFullPath(AppDomain.CurrentDomain.BaseDirectory),"fixture-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);string executable=Path.Combine(root,"test-emulator.exe");File.WriteAllText(executable,"fixture");var emulator=new EmulatorProfile{Id="emu1",Name="Test Emulator",Preset="Custom",Executable=executable,ManualVersion="1.0",InGameSaveFolder=Path.Combine(root,"live"),Extensions=new List<string>{"gba"}};
  var game=new GameEntry{Id="game1",Title="Example",Path=Path.Combine(root,"Example.gba"),EmulatorId=emulator.Id,Favorite=true,Pinned=true,Tags=new List<string>{"test"},LastLaunched=DateTime.Now.ToString("g")};File.WriteAllText(game.Path,"game");var library=new LibraryData{Emulators=new List<EmulatorProfile>{emulator},Games=new List<GameEntry>{game},Collections=new List<GameCollection>(),ControllerProfiles=new List<ControllerProfile>(),Links=new List<WebsiteLink>(),Converters=new List<GameConverter>(),Theme=new ThemeSettings{Name="FishBowl Water",CustomizationVersion=9,ShowBanner=true,ShowStatusBar=true,ShowInformationPanel=true,StartupAssistantPreferenceSet=true,GameStorageAssistantPreferenceSet=true,RequirementsStorageAssistantPreferenceSet=true,LastSeenBuild="1.2",DisableInGameSaveNotifications=true},GameLibraryRoot=Path.Combine(root,"Games")};ExperienceData.Ensure(library);Store.Save(library);
  Directory.CreateDirectory(emulator.InGameSaveFolder);string save=Path.Combine(emulator.InGameSaveFolder,"Example.sav");File.WriteAllText(save,"save one");GameSaves.Link(game,save,"In-game saves");var first=SaveHistory.Capture(library,game,save,"In-game saves",false,CancellationToken.None);Check(File.ReadAllText(first.Path)=="save one"&&File.ReadAllText(save)=="save one","snapshot preserves original");Check(SaveHistory.Capture(library,game,save,"In-game saves",true,CancellationToken.None).Id==first.Id,"identical contents deduplicated");File.WriteAllText(save,"save two");var second=SaveHistory.Capture(library,game,save,"In-game saves",true,CancellationToken.None);Check(second.Id!=first.Id,"changed contents create history");SaveHistory.Restore(library,first,CancellationToken.None);Check(File.ReadAllText(save)=="save one","reviewed restore writes selected snapshot");Check(library.SaveSnapshots.Any(s=>s.Pinned&&s.Note!=null&&s.Note.StartsWith("Before restoring")),"restore preserves pinned backup");
  string folder=Path.Combine(root,"folder-save");Directory.CreateDirectory(Path.Combine(folder,"nested"));File.WriteAllText(Path.Combine(folder,"a.dat"),"a");File.WriteAllText(Path.Combine(folder,"nested","b.dat"),"b");GameSaves.Link(game,folder,"In-game saves");var tree=SaveHistory.Capture(library,game,folder,"In-game saves",false,CancellationToken.None);Check(tree.IsFolder&&File.Exists(Path.Combine(tree.Path,"nested","b.dat")),"directory snapshot preserves structure");string bundle=Path.Combine(root,"save.zip");SaveHistory.Export(library,tree,bundle,CancellationToken.None);var imported=SaveHistory.Import(library,game,bundle,CancellationToken.None);Check(imported.Hash==tree.Hash&&imported.Source==null,"import verifies contents and does not trust restore path");
  string bad=Path.Combine(root,"bad.zip");using(var archive=ZipFile.Open(bad,ZipArchiveMode.Create)){var manifest=archive.CreateEntry("snapshot.json");using(var writer=new StreamWriter(manifest.Open()))writer.Write(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(tree));var escape=archive.CreateEntry("data/../../escape");using(var writer=new StreamWriter(escape.Open()))writer.Write("bad");}Throws(()=>SaveHistory.Import(library,game,bad,CancellationToken.None),"zip traversal rejected");Throws(()=>SafeFiles.Under(root,"../escape"),"unsafe relative paths rejected");
  var cancelled=new CancellationTokenSource();cancelled.Cancel();int before=library.SaveSnapshots.Count;Throws(()=>SaveHistory.Capture(library,game,save,"In-game saves",false,cancelled.Token),"cancelled snapshot stops");Check(library.SaveSnapshots.Count==before,"cancelled snapshot not committed");library.Experience.SnapshotCount=1;library.Experience.SnapshotDays=0;library.Experience.SnapshotMegabytes=0;Check(!SaveHistory.CleanupCandidates(library,game).Any(s=>s.Pinned),"retention preserves pinned backups");
  string rom=Path.Combine(root,"import.gba");File.WriteAllText(rom,"rom");var plan=OrganizedGames.Plan(library,new[]{rom},null,false,CancellationToken.None);var transaction=OrganizedGames.Apply(library,plan,false,CancellationToken.None,s=>{});Check(!File.Exists(rom)&&File.Exists(plan[0].Destination),"move verified and journaled");OrganizedGames.Undo(library,transaction,CancellationToken.None);Check(File.Exists(rom)&&!File.Exists(plan[0].Destination)&&transaction.Undone,"undo restores source and records completion");
  string track=Path.Combine(root,"disc.bin"),cue=Path.Combine(root,"disc.cue"),playlist=Path.Combine(root,"game.m3u");File.WriteAllText(track,"track");File.WriteAllText(cue,"FILE \"disc.bin\" BINARY");File.WriteAllText(playlist,"disc.cue");var grouped=OrganizedGames.Plan(library,new[]{track,cue,playlist},"PlayStation",true,CancellationToken.None);string groupedSummary=string.Join(" | ",grouped.Select((p,i)=>"#"+i+" source="+p.Source+" files=["+string.Join(", ",p.Files.ToArray())+"]"));Check(grouped.Count==1&&grouped[0].Files.Count==3,"multi-disc support files grouped once; grouped.Count="+grouped.Count+"; grouped="+groupedSummary);var copyTransaction=OrganizedGames.Apply(library,grouped,true,CancellationToken.None,s=>{});Check(File.Exists(Path.Combine(Path.GetDirectoryName(grouped[0].Destination),"disc.bin")),"disc tracks copied together");File.WriteAllText(track,"original changed");OrganizedGames.Undo(library,copyTransaction,CancellationToken.None);Check(File.ReadAllText(track)=="original changed","undo copy preserves changed original");File.WriteAllText(playlist,"game.m3u");Throws(()=>OrganizedGames.Related(playlist),"circular playlist rejected");
  library.SaveReviews.Add(new SaveReviewItem{Path="group",GameId=game.Id,Files=new List<string>{save},ChangedAt=DateTime.UtcNow.ToString("o")});library.Experience.QuietStartHour=22;library.Experience.QuietEndHour=7;Check(ExperienceData.Quiet(library.Experience,new DateTime(2026,10,2,23,0,0))&&!ExperienceData.Quiet(library.Experience,new DateTime(2026,10,2,12,0,0)),"overnight quiet hours");Store.Save(library);var loaded=Store.Load();ExperienceData.Ensure(loaded);Check(loaded.SaveReviews.Count==1&&loaded.SaveSnapshots.Count==library.SaveSnapshots.Count,"inbox and history persist");
  using(var home=new Form{ClientSize=new Size(1280,720),ShowInTaskbar=false,StartPosition=FormStartPosition.Manual,Location=new Point(-3000,-3000)}){home.Controls.Add(new HomeSurface(library,(a,g,e)=>{}));home.Show();Application.DoEvents();using(var bitmap=new Bitmap(home.Width,home.Height)){home.DrawToBitmap(bitmap,new Rectangle(0,0,bitmap.Width,bitmap.Height));bitmap.Save("home.png");}}
  using(var history=new SaveHistoryDialog(library,game)){history.ShowInTaskbar=false;history.Location=new Point(-3000,-3000);history.StartPosition=FormStartPosition.Manual;history.Show();Application.DoEvents();using(var bitmap=new Bitmap(history.Width,history.Height)){history.DrawToBitmap(bitmap,new Rectangle(0,0,bitmap.Width,bitmap.Height));bitmap.Save("history.png");}}
  using(var form=new MainForm(true)){form.ShowInTaskbar=false;form.StartPosition=FormStartPosition.Manual;form.Location=new Point(-3000,-3000);form.Show();Application.DoEvents();Check(form.Controls.OfType<TableLayoutPanel>().Count()==1,"main workspace constructs");using(var bitmap=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bitmap,new Rectangle(0,0,bitmap.Width,bitmap.Height));bitmap.Save("main.png");}}
  using(var owner=new Form{ShowInTaskbar=false,StartPosition=FormStartPosition.Manual,Location=new Point(-3000,-3000)}){owner.Show();RenderModal(()=>ExperienceTools.Settings(owner,library),"Home, Library and Save Preferences","settings.png");RenderModal(()=>ExperienceTools.Cloud(owner,library),"Optional Cloud Backup Folder","cloud.png");RenderModal(()=>ExperienceTools.Bulk(owner,library,new List<GameEntry>{game}),"Bulk edit 1 games","bulk.png");RenderModal(()=>ExperienceTools.Readiness(owner,library),"Emulator Readiness, Releases and Save Folders","readiness.png");}
  string runner=Path.Combine(root,"SessionFixture.exe");string runnerSource=Path.Combine(root,"SessionFixture.cs");File.WriteAllText(runnerSource,"class Runner { static void Main() { System.Threading.Thread.Sleep(1200); } }");var compiler=System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo{FileName=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows),"Microsoft.NET","Framework64","v4.0.30319","csc.exe"),Arguments="/nologo /target:winexe /out:\""+runner+"\" \""+runnerSource+"\"",UseShellExecute=false,CreateNoWindow=true});compiler.WaitForExit();Check(compiler.ExitCode==0,"session fixture builds");emulator.Executable=runner;emulator.Arguments="{unsupported}";Throws(()=>GameSessions.Validate(library,game),"unsupported launch templates rejected");emulator.Arguments=null;
  using(var owner=new Form{ShowInTaskbar=false,Location=new Point(-3000,-3000),StartPosition=FormStartPosition.Manual}){owner.Show();long seconds=game.TotalPlaySeconds;ExperienceTools.Launch(owner,library,game);var wait=System.Diagnostics.Stopwatch.StartNew();while(wait.ElapsedMilliseconds<3000){Application.DoEvents();System.Threading.Thread.Sleep(20);}Check(game.TotalPlaySeconds>seconds&&game.LaunchCount>0,"actual emulator-process session time recorded");}
  var feed=new EmulatorProfile{Id="feed",Name="Feed",Preset="Custom",Executable=executable,GitHubRepository="example/emulator",IgnoredReleaseTag="v2.0"};var result=EmulatorUpdates.Check(feed,url=>"{\"tag_name\":\"v2.0\",\"name\":\"v2.0\",\"html_url\":\"https://github.com/example/emulator/releases/tag/v2.0\",\"body\":\"Release notes\",\"draft\":false,\"prerelease\":false}");Check(result.Status.Contains("ignored"),"release ignore preference affects comparison");
  foreach(float factor in new[]{1.25f,1.5f,2f})using(var form=new Form{ClientSize=new Size(1000,640),ShowInTaskbar=false,Location=new Point(-4000,-4000),StartPosition=FormStartPosition.Manual}){var surface=new HomeSurface(library,(a,g,e)=>{});form.Controls.Add(surface);form.Show();form.Scale(new SizeF(factor,factor));Application.DoEvents();Check(surface.Controls.OfType<FlowLayoutPanel>().All(p=>p.Width>0&&p.Height>0),"Home scales at "+factor);using(var bitmap=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bitmap,new Rectangle(0,0,bitmap.Width,bitmap.Height));bitmap.Save("home-scale-"+factor.ToString("0.00",System.Globalization.CultureInfo.InvariantCulture)+".png");}}
  using(var monitored=new MainForm(true)){monitored.ShowInTaskbar=false;monitored.StartPosition=FormStartPosition.Manual;monitored.Location=new Point(-3000,-3000);var field=typeof(MainForm).GetField("library",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);var data=(LibraryData)field.GetValue(monitored);data.Theme.DisableInGameSaveNotifications=false;data.Experience.SnoozeUntil=DateTime.UtcNow.AddHours(1).ToString("o");data.SaveReviews.Clear();var watched=data.Games.Single(g=>g.Id==game.Id);string extra=Path.Combine(emulator.InGameSaveFolder,"extra.sav");File.WriteAllText(extra,"old");GameSaves.Link(watched,extra,"In-game saves");monitored.Show();var wait=System.Diagnostics.Stopwatch.StartNew();while(wait.ElapsedMilliseconds<800){Application.DoEvents();System.Threading.Thread.Sleep(20);}File.WriteAllText(save,"watched changed");File.WriteAllText(extra,"watched second changed");wait.Restart();while(wait.ElapsedMilliseconds<6000){Application.DoEvents();System.Threading.Thread.Sleep(20);}Check(data.SaveReviews.Count==1&&data.SaveReviews[0].Files.Count==2,"actual file events coalesce into one persisted game group");Check(Store.Load().SaveReviews.Count==1,"watcher inbox survives settings reload");watched.SaveCopyPreference="Automatic copies";wait.Restart();while(wait.ElapsedMilliseconds<4000){Application.DoEvents();System.Threading.Thread.Sleep(20);}Check(data.SaveReviews.Count==0&&data.SaveSnapshots.Any(s=>GameLibraryRemoval.SamePath(s.Source,extra)),"automatic copies capture explicit associations and clear review");}
  Console.WriteLine("PASS: "+checks+" checks covering history, folder saves, deduplication, restore backups, bundle validation, cancellation, retention, move/copy undo, multi-disc grouping, quiet hours, persistence and UI construction.");return 0;
 }
}