using System; using System.IO; using System.Linq; using System.Collections.Generic; using System.Threading; using System.Runtime.InteropServices; using System.Text; using System.Drawing; using System.Windows.Forms; using EmulatorHub;
class LibraryRecoveryTests
{
 static int checks;
 static void Check(bool value, string name) { checks++; if (!value) throw new Exception(name); }
 [DllImport("kernel32.dll", CharSet=CharSet.Unicode)] static extern uint GetShortPathName(string longPath, StringBuilder shortPath, uint size);
 static LibraryData Library() { return new LibraryData { Games=new List<GameEntry>(), Emulators=new List<EmulatorProfile>(), Collections=new List<GameCollection>(), PlayQueue=new List<string>() }; }
 [STAThread] static int Main() { try { Application.EnableVisualStyles(); Run(); Console.WriteLine("PASS: " + checks + " recovery, portable paths, artwork retention and multi-disc checks."); return 0; } catch(Exception e) { Console.WriteLine(e); return 1; } }
 static void Run()
 {
  string root=Path.Combine(Path.GetFullPath(AppDomain.CurrentDomain.BaseDirectory),"Recovery with spaces "+Guid.NewGuid().ToString("N")); Directory.CreateDirectory(root);
  string rom=Path.Combine(root,"Game.gba"),exe=Path.Combine(root,"Emulator.exe"); File.WriteAllText(rom,"rom"); File.WriteAllText(exe,"exe");
  var d=Library(); var emu=new EmulatorProfile{Id="emu",Name="Test",Executable=exe}; d.Emulators.Add(emu);
  var a=new GameEntry{Id="a",Title="Custom title",TitleIsCustom=true,Path=rom,EmulatorId="emu",ArtworkPath=Path.Combine(root,"art.png"),Notes="keep notes",Tags=new List<string>{"tag"},TotalPlaySeconds=99};
  var b=new GameEntry{Id="b",Path=Path.Combine(root,"Other.gba")}; d.Games.AddRange(new[]{a,b}); d.PlayQueue.AddRange(new[]{"a","b"}); d.Collections.Add(new GameCollection{Id="c",GameIds=new List<string>{"a","b"}});
  Check(GameLibraryRemoval.RemoveGames(d,new[]{"a"})==1,"remove saves entry"); Check(d.RemovalHistory.Count==1,"undo history recorded");
  var json=Json.Serialize(d); d=Json.Deserialize<LibraryData>(json); Check(GameLibraryRemoval.Undo(d)==1,"undo survives JSON"); a=d.Games.First(g=>g.Id=="a");
  Check(a.Title=="Custom title"&&a.TitleIsCustom&&a.Notes=="keep notes"&&a.TotalPlaySeconds==99,"undo retains metadata"); Check(d.PlayQueue.SequenceEqual(new[]{"a","b"}),"queue order restored"); Check(d.Collections[0].GameIds.SequenceEqual(new[]{"a","b"}),"collection order restored"); Check(!GameLibraryRemoval.IsExcluded(d,rom),"undo permits scanning again"); Check(File.ReadAllText(rom)=="rom","undo leaves game file unchanged");
  GameLibraryRemoval.RemoveGames(d,new[]{"a"}); var conflict=new GameEntry{Id="new",Path=rom,Title="New title"}; d.Games.Add(conflict); Check(GameLibraryRemoval.Undo(d)==0,"path collision skipped"); Check(d.RemovalHistory.Count==1,"conflict retains recoverable entry"); Check(conflict.Title=="New title","conflict never overwrites metadata"); d.Games.Remove(conflict); Check(GameLibraryRemoval.Undo(d)==1,"restore after collision resolved");
  GameLibraryRemoval.RemoveGames(d,new[]{"a","b"});d.Games.Add(conflict);Check(GameLibraryRemoval.Undo(d)==1,"partial undo restores nonconflicting game");Check(d.RemovalHistory[0].Games.Count==1,"partial history contains only pending entry");d=Json.Deserialize<LibraryData>(Json.Serialize(d));d.Games.RemoveAll(g=>g.Id=="new");Check(GameLibraryRemoval.Undo(d)==1&&d.RemovalHistory.Count==0,"partial undo finishes after restart");Check(d.PlayQueue.SequenceEqual(new[]{"a","b"}),"partial undo preserves queue order after restart");
  a=d.Games.First(g=>g.Id=="a"); GameLibraryRemoval.RemoveEmulator(d,"emu"); d.Emulators.Add(new EmulatorProfile{Id="other",Executable=Path.Combine(root,"other.exe")}); Check(a.RequiresEmulatorAssignment,"removal requires assignment"); Check(ExperienceData.Emulator(d,a)==null,"no unsuitable sole emulator fallback"); Check(GameLibraryRemoval.Undo(d)==1,"emulator restored"); Check(a.EmulatorId=="emu"&&!a.RequiresEmulatorAssignment,"previous assignment restored");
  GameLibraryRemoval.RemoveEmulator(d,"emu"); a.PreferredEmulatorId="other";a.RequiresEmulatorAssignment=false; GameLibraryRemoval.Undo(d); Check(a.PreferredEmulatorId=="other","undo preserves reassignment"); Check(File.ReadAllText(exe)=="exe","emulator disk preserved");
  string old=Path.Combine(root,"old portable"),moved=Path.Combine(root,"moved portable");Directory.CreateDirectory(Path.Combine(old,"FishBowlData","Artwork","GameCovers"));string art=Path.Combine(old,"FishBowlData","Artwork","GameCovers",Guid.NewGuid().ToString("N")+".png");File.WriteAllText(art,"art");string game=Path.Combine(old,"Disc.cue");File.WriteAllText(game,"game");a.Path=game;a.ArtworkPath=art;a.Discs=new List<string>{game};d.Emulators[0].Executable=game;LibraryPaths.Stamp(d,Path.Combine(old,"FishBowlData"),old);Directory.Move(old,moved);
  Check(LibraryPaths.Rebase(d,old,moved,false)>=3,"batch review counts existing replacements");Check(a.Path==game,"review does not apply changes");LibraryPaths.Load(d,Path.Combine(moved,"FishBowlData"),moved);Check(File.Exists(a.Path)&&File.Exists(a.ArtworkPath),"portable move repairs games and covers");Check(a.Discs[0]==a.Path,"disc paths repaired");Check(File.Exists(d.Emulators[0].Executable),"portable executable repaired");Check(LibraryPaths.Rebase(d,old,moved,true)==0,"repair is idempotent");
  string liveRoot=Path.Combine(moved,"FishBowlData"),covers=Path.Combine(liveRoot,"Artwork","GameCovers");string orphan=Path.Combine(covers,Guid.NewGuid().ToString("N")+".png"),manual=Path.Combine(covers,"my-cover.png");File.WriteAllText(orphan,"unused");File.WriteAllText(manual,"manual");
  var candidates=LibraryPaths.ArtworkCandidates(d,liveRoot,new LibraryData[0]);Check(candidates.Count==1&&GameLibraryRemoval.SamePath(candidates[0],orphan),"cleanup only unreferenced generated files: expected "+orphan+"; found "+string.Join("; ",candidates));GameLibraryRemoval.RemoveGames(d,new[]{"a"});Check(!LibraryPaths.ArtworkCandidates(d,liveRoot,new LibraryData[0]).Any(path=>GameLibraryRemoval.SamePath(path,a.ArtworkPath)),"undo artwork protected");var backup=Library();backup.Games.Add(new GameEntry{ArtworkPath=orphan});Check(LibraryPaths.ArtworkCandidates(d,liveRoot,new[]{backup}).Count==0,"backup artwork protected");Check(File.Exists(orphan)&&File.Exists(manual),"cleanup review never deletes files");
  string icons=Path.Combine(liveRoot,"Artwork","GameIcons");Directory.CreateDirectory(icons);string unusedIcon=Path.Combine(icons,new string('a',20)+"-"+Guid.NewGuid().ToString("N")+".png");File.WriteAllText(unusedIcon,"icon");candidates=LibraryPaths.ArtworkCandidates(d,liveRoot,new[]{backup});Check(candidates.Count==1&&GameLibraryRemoval.SamePath(candidates[0],unusedIcon),"unused recognized icons are candidates");backup.Games.Add(new GameEntry{ArtworkPath=unusedIcon});Check(LibraryPaths.ArtworkCandidates(d,liveRoot,new[]{backup}).Count==0,"backup icons protected");
  string track=Path.Combine(root,"disc.bin"),cue=Path.Combine(root,"disc.cue"),playlist=Path.Combine(root,"game.m3u");File.WriteAllText(track,"track");File.WriteAllText(cue,"FILE \"disc.bin\" BINARY");File.WriteAllText(playlist,"disc.cue\ndisc.cue");d.GameLibraryRoot=Path.Combine(root,"Games");var sources=new[]{track,cue,playlist};
  foreach(var order in new[]{sources,sources.Reverse().ToArray(),new[]{cue,playlist,track}}) {var plans=OrganizedGames.Plan(d,order,"PlayStation",true,CancellationToken.None);Check(plans.Count==1&&plans[0].Files.Count==3,"order-independent group with repeated disc");}
  var shortName=new StringBuilder(32768);uint shortLength=GetShortPathName(root,shortName,32768);if(shortLength>0&&shortLength<32768){var shortSources=sources.Select(p=>Path.Combine(shortName.ToString(),Path.GetFileName(p))).ToArray();var plans=OrganizedGames.Plan(d,shortSources,"PlayStation",true,CancellationToken.None);Check(plans.Count==1&&plans[0].Files.Count==3,"short Windows temp paths group once");}else Console.WriteLine("Short-path alias unavailable for this fixture; relative and absolute source checks still run.");
  string current=Environment.CurrentDirectory;try{Environment.CurrentDirectory=root;var plans=OrganizedGames.Plan(d,new[]{"disc.bin",".\\disc.cue","game.m3u"},"PlayStation",true,CancellationToken.None);Check(plans.Count==1&&plans[0].Files.Count==3,"relative source paths group once");}finally{Environment.CurrentDirectory=current;}
  File.WriteAllText(playlist,"game.m3u");bool threw=false;try{OrganizedGames.Related(playlist);}catch(IOException){threw=true;}Check(threw,"circular playlists rejected");
  a.RequiresEmulatorAssignment=true;
  foreach(int percent in new[]{100,150,200}) {
   NextUi.TextPercent=percent; bool opened=false;
   using(var timer=new System.Windows.Forms.Timer{Interval=40}) {
    int ticks=0;timer.Tick+=delegate {var form=Application.OpenForms.Cast<Form>().FirstOrDefault(f=>f.Text=="Preferred emulator"&&f.Visible);if(form==null){if(++ticks>100)throw new Exception("Reassignment prompt missing");return;}timer.Stop();opened=true;using(var image=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(image,new Rectangle(Point.Empty,image.Size));image.Save("Reassignment-"+percent+".png");}form.Close();};timer.Start();ExperienceTools.Launch(null,d,a);
   }
   Check(opened&&a.RequiresEmulatorAssignment,"cancel reassignment leaves game unassigned at "+percent+"%");
  }
  NextUi.TextPercent=100;
 }
}
