using System;using System.Drawing;using System.IO;using System.Linq;using System.Windows.Forms;using EmulatorHub;
class NavigationTests {
 [System.Runtime.InteropServices.DllImport("user32.dll")]static extern bool EnableWindow(IntPtr window,bool enabled);
 static int checks;static void Check(bool value,string message){checks++;if(!value)throw new Exception(message);}
 [STAThread]static int Main(){try{Application.EnableVisualStyles();Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException);Run();Console.WriteLine("PASS: "+checks+" controller state, menus, overflow, controls, unified appearance and general preference checks.");return 0;}catch(Exception error){Console.Error.WriteLine(error);return 1;}}
 static void Modal(Action open,Action<Form> inspect){Exception error=null;using(var timer=new Timer{Interval=150}){timer.Tick+=delegate{var dialog=Application.OpenForms.Cast<Form>().LastOrDefault(f=>f is NextDialog);if(dialog==null)return;timer.Stop();try{inspect(dialog);}catch(Exception e){error=e;}finally{if(!dialog.IsDisposed)dialog.Close();}};timer.Start();open();}if(error!=null)throw error;}
 static void Run(){
  var state=new ControllerInput();Check(state.Sample(true,0,0x1000,0,0,0,true)==0,"connect with A held does not activate");Check(state.Sample(true,0,0,0,0,20,true)==0,"release is quiet");Check(state.Sample(true,0,0x1000,0,0,40,true)==0x1000,"fresh A edge activates");Check(state.Sample(true,0,0x1000,0,0,500,true)==0,"A never auto repeats");
  Check(state.Sample(false,0,0,0,0,520,true)==0,"disconnect quiet");Check(state.Sample(true,0,0x1000,0,0,540,true)==0,"reconnect holding A quiet");Check(state.Sample(true,1,0x1000,0,0,560,true)==0,"controller switch quiet");Check(state.Sample(true,1,0,0,0,580,false)==0,"background quiet");Check(state.Sample(true,1,0x1000,0,0,600,true)==0,"refocus holding A quiet");
  state=new ControllerInput();state.Sample(true,0,0,0,0,0,true);Check(state.Sample(true,0,0,7849,-7849,20,true)==0,"stick deadzone suppresses drift");Check(state.Sample(true,0,0,12000,0,40,true)==8,"right stick motion maps to right");Check(state.Sample(true,0,0,12000,0,439,true)==0,"direction waits initial delay");Check(state.Sample(true,0,0,12000,0,440,true)==8,"direction repeats after delay");Check(state.Sample(true,0,0,12000,0,549,true)==0,"repeat bounded");Check(state.Sample(true,0,0,12000,0,550,true)==8,"direction repeat interval");Check(state.Sample(true,0,1,12000,0,600,true)==1,"physical d-pad overrides stick");
  using(var owner=new Form{ClientSize=new Size(720,500),ShowInTaskbar=false}){
   var check=new CheckBox{Text="Enabled",Location=new Point(10,20),AutoSize=true};var combo=new ComboBox{Location=new Point(10,60),DropDownStyle=ComboBoxStyle.DropDownList};combo.Items.AddRange(new object[]{"One","Two"});combo.SelectedIndex=0;var list=new CheckedListBox{Location=new Point(10,110)};list.Items.AddRange(new object[]{"First","Second"});var number=new NumericUpDown{Location=new Point(10,230),Minimum=0,Maximum=5,Value=2};var tabs=new TabControl{Location=new Point(300,20),Size=new Size(350,250)};tabs.TabPages.Add("First");tabs.TabPages.Add("Second");owner.Controls.AddRange(new Control[]{check,combo,list,number,tabs});owner.Show();Application.DoEvents();
   Check(NavigationController.CanNavigate(owner,owner.Handle),"enabled foreground owner accepts controller input");
   EnableWindow(owner.Handle,false);try{Check(!NavigationController.CanNavigate(owner,owner.Handle),"native disabled owner rejects controller input");}finally{EnableWindow(owner.Handle,true);}
   using(var nativeModal=new Form{ShowInTaskbar=false}){nativeModal.Show();Application.DoEvents();Check(!NavigationController.CanNavigate(owner,nativeModal.Handle),"foreign same-process modal root rejects underlying owner input");nativeModal.Close();}
   Check(!NavigationController.CanNavigate(owner,IntPtr.Zero),"missing foreground rejects controller input");
   check.Focus();NavigationController.ApplyButtons(owner,owner,0x1000);Check(check.Checked,"A toggles checkbox");combo.Focus();NavigationController.ApplyButtons(owner,owner,0x1000);Check(combo.DroppedDown,"A opens combo");NavigationController.ApplyButtons(owner,owner,2);Check(combo.SelectedIndex==1,"down changes combo selection");NavigationController.ApplyButtons(owner,owner,0x2000);Check(!combo.DroppedDown&&!owner.IsDisposed,"B closes combo before owner");list.Focus();list.SelectedIndex=0;NavigationController.ApplyButtons(owner,owner,0x1000);Check(list.GetItemChecked(0),"A checks selected list item");NavigationController.ApplyButtons(owner,owner,2);Check(list.SelectedIndex==1,"down moves checked-list selection");number.Focus();NavigationController.ApplyButtons(owner,owner,8);Check(number.Value==3,"right increments numeric input");for(int i=0;i<10;i++)NavigationController.ApplyButtons(owner,owner,4);Check(number.Value==0,"numeric input respects minimum");tabs.Focus();NavigationController.ApplyButtons(owner,owner,0x200);Check(tabs.SelectedIndex==1,"RB switches tabs");NavigationController.ApplyButtons(owner,owner,0x100);Check(tabs.SelectedIndex==0,"LB switches tabs back");
   int activated=0;using(var menu=new ContextMenuStrip()){menu.Items.Add(new ToolStripMenuItem("Disabled"){Enabled=false});menu.Items.Add("Review",null,delegate{activated++;});menu.Items.Add("Other");NavigationController.Register(menu);menu.Show(owner,new Point(100,300));Application.DoEvents();Check(NavigationController.CanNavigate(owner,menu.Handle),"registered visible overflow popup accepts controller input");NavigationController.ApplyButtons(owner,owner,2);Check(menu.Items[1].Selected,"overflow skips disabled entries");NavigationController.ApplyButtons(owner,owner,8);Check(activated==0&&menu.Visible,"right does not activate overflow leaf");NavigationController.ApplyButtons(owner,owner,0x1000);Check(activated==1&&!menu.Visible,"A activates real overflow action once");menu.Show(owner,new Point(100,300));Application.DoEvents();NavigationController.ApplyButtons(owner,owner,0x2000);Check(!menu.Visible&&!owner.IsDisposed,"B dismisses overflow without closing owner");}
   using(var nested=new ContextMenuStrip()){var group=new ToolStripMenuItem("Group");group.DropDownItems.Add("Child",null,delegate{activated++;});nested.Items.Add(group);NavigationController.Register(nested);nested.Show(owner,new Point(100,300));Application.DoEvents();NavigationController.ApplyButtons(owner,owner,2);NavigationController.ApplyButtons(owner,owner,8);Application.DoEvents();Check(group.DropDown.Visible,"right opens submenu");NavigationController.ApplyButtons(owner,owner,0x2000);Check(!group.DropDown.Visible&&nested.Visible,"B returns from submenu to parent");NavigationController.ApplyButtons(owner,owner,0x2000);Check(!nested.Visible,"B closes parent overflow");}
   var strip=new MenuStrip();var file=new ToolStripMenuItem("File");file.DropDownItems.Add("Review",null,delegate{activated++;});strip.Items.Add(file);owner.Controls.Add(strip);NavigationController.ApplyButtons(owner,owner,16);Application.DoEvents();Check(file.DropDown.Visible,"Start opens app menu");NavigationController.ApplyButtons(owner,owner,0x1000);Check(activated==2,"app menu action activates");
   using(var child=new Form{Owner=owner,ShowInTaskbar=false}){child.Show();NavigationController.ApplyButtons(child,owner,0x2000);Check(child.IsDisposed,"B closes child dialog");}
   owner.Close();
  }
  var data=Store.Load();NextData.Ensure(data);ExperienceData.Ensure(data);data.Theme.ColorHarmony="Original";data.Theme.ControlDensity="Roomy";int refreshed=0,fonts=0,cosmetics=0;Directory.CreateDirectory("navigation-previews");
  foreach(int percent in new[]{100,150,200}){NextUi.TextPercent=percent;TextFit.WorkingAreaOverride=new Rectangle(0,0,1024,720);Modal(delegate{WindowsAppearance.Open(null,data,delegate{refreshed++;},delegate{fonts++;},delegate{cosmetics++;});},dialog=>{var buttons=NextUi.Descendants(dialog).OfType<Button>().ToArray();Check(new[]{"Appearance and Home","Live appearance and accessibility","Cosmetic styles","Immersion settings","General settings"}.All(name=>buttons.Any(b=>b.Text==name)),"hub exposes all appearance groups at "+percent);buttons.Single(b=>b.Text=="Live appearance and accessibility").PerformClick();buttons.Single(b=>b.Text=="Cosmetic styles").PerformClick();Check(fonts==cosmetics,"hub invokes existing editors");Check(buttons.All(b=>b.Bottom<=b.Parent.ClientSize.Height),"hub actions fit at "+percent);using(var image=new Bitmap(dialog.Width,dialog.Height)){dialog.DrawToBitmap(image,new Rectangle(Point.Empty,image.Size));image.Save("navigation-previews/appearance-"+percent+".png");}});}
  bool prior=data.Theme.ShowStartupAssistant;Modal(delegate{WindowsAppearance.General(null,data,delegate{refreshed++;});},dialog=>{var boxes=NextUi.Descendants(dialog).OfType<CheckBox>().ToArray();Check(boxes.Length==5,"general includes all startup/launch/sync preferences");Check(boxes.All(b=>b.Width>=TextRenderer.MeasureText(b.Text,b.Font).Width+18&&b.Height>=b.Font.Height),"general checkboxes fit readable text at 200%");using(var image=new Bitmap(dialog.Width,dialog.Height)){dialog.DrawToBitmap(image,new Rectangle(Point.Empty,image.Size));image.Save("navigation-previews/general-200.png");}boxes[0].Checked=!prior;NextUi.Descendants(dialog).OfType<Button>().Single(b=>b.Text=="Cancel").PerformClick();});Check(data.Theme.ShowStartupAssistant==prior,"General cancel preserves preferences");Modal(delegate{WindowsAppearance.General(null,data,delegate{refreshed++;});},dialog=>{NextUi.Descendants(dialog).OfType<CheckBox>().Single(b=>b.Text.StartsWith("Show the setup assistant")).Checked=!prior;NextUi.Descendants(dialog).OfType<Button>().Single(b=>b.Text=="Save").PerformClick();});Check(data.Theme.ShowStartupAssistant==!prior&&data.Theme.StartupAssistantPreferenceSet&&refreshed==1,"General saves and applies preferences");Check(data.Theme.ColorHarmony=="Original"&&data.Theme.ControlDensity=="Roomy","General preserves appearance preferences");NextUi.TextPercent=100;TextFit.WorkingAreaOverride=null;
 }
}
