using System;using System.Collections.Generic;using System.Diagnostics;using System.Drawing;using System.IO;using System.Linq;using System.Reflection;using System.Runtime.InteropServices;using System.Threading;using System.Windows.Forms;using EmulatorHub;
class PlayLaunchTests {
 static int checks;static string childExe;static DateTime began;static readonly List<Process> owned=new List<Process>();static readonly BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;
 [DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr window,out uint pid);
 [DllImport("user32.dll")]static extern IntPtr GetParent(IntPtr window);
 [DllImport("user32.dll")]static extern IntPtr GetWindow(IntPtr window,uint command);
 [DllImport("user32.dll")]static extern bool PostMessage(IntPtr window,uint message,IntPtr wparam,IntPtr lparam);
 [DllImport("user32.dll")]static extern bool IsWindow(IntPtr window);
 [DllImport("user32.dll")]static extern bool IsWindowEnabled(IntPtr window);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern uint GetLongPathName(string path,System.Text.StringBuilder result,uint capacity);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern uint GetShortPathName(string path,System.Text.StringBuilder result,uint capacity);
 static string Canonical(string path){string full=Path.GetFullPath(path);var result=new System.Text.StringBuilder(512);uint length=GetLongPathName(full,result,(uint)result.Capacity);if(length>=result.Capacity){result=new System.Text.StringBuilder((int)length+1);length=GetLongPathName(full,result,(uint)result.Capacity);}return length>0&&length<result.Capacity?Path.GetFullPath(result.ToString()):full;}
 static string OwnershipDetails(Process process){try{return "requested="+childExe+" actual="+process.MainModule.FileName+" canonical-requested="+Canonical(childExe)+" canonical-actual="+Canonical(process.MainModule.FileName)+" started="+process.StartTime.ToUniversalTime().ToString("o")+" epoch="+began.ToString("o");}catch(Exception error){return error.Message;}}
 static void Check(bool value,string message){checks++;if(!value)throw new Exception(message);}
 static void Pump(int ms){var clock=Stopwatch.StartNew();while(clock.ElapsedMilliseconds<ms){Application.DoEvents();Thread.Sleep(5);}}
 static bool Until(Func<bool> condition){var clock=Stopwatch.StartNew();while(!condition()&&clock.ElapsedMilliseconds<12000)Pump(25);return condition();}
 static object Field(object value,string name){return value.GetType().GetField(name,Private).GetValue(value);}
 static bool MatchesIdentity(Process process,string expected,DateTime epoch){try{return !process.HasExited&&Canonical(process.MainModule.FileName).Equals(Canonical(expected),StringComparison.OrdinalIgnoreCase)&&process.StartTime.ToUniversalTime()>=epoch;}catch{return false;}}
 static bool IsOwned(Process process){return MatchesIdentity(process,childExe,began);}
 static Process Record(PlayWindowHost host){uint pid;GetWindowThreadProcessId(host.GameWindow,out pid);var process=Process.GetProcessById((int)pid);Check(IsOwned(process),"attached launch belongs to the exact distinct fixture executable and creation time: "+OwnershipDetails(process));owned.Add(process);return process;}
 static PlayWindowHost Attached(MainForm main){Check(Until(()=>NextUi.Descendants(main).OfType<PlayWindowHost>().Any(h=>h.IsAttached)),"launch attaches a real cross-process window: "+string.Join(" | ",NextUi.Descendants((Control)Field(main,"playSurface")).OfType<Label>().Select(l=>l.Text)));return NextUi.Descendants(main).OfType<PlayWindowHost>().Single(h=>h.IsAttached);}
 static void Stop(Process process,IntPtr window){if(process.HasExited)return;if(!IsOwned(process))throw new Exception("Refusing cleanup of an unverified process");uint pid;if(window!=IntPtr.Zero&&IsWindow(window)){GetWindowThreadProcessId(window,out pid);if(pid==(uint)process.Id)PostMessage(window,0x10,IntPtr.Zero,IntPtr.Zero);}if(!process.WaitForExit(2500)){Check(IsOwned(process),"cleanup revalidates fixture identity before terminating");process.Kill();process.WaitForExit();}Pump(150);}
 [STAThread]static int Main(string[] args){if(args.Contains("--child")){Application.EnableVisualStyles();using(var child=new Form{Text="Actual launch fixture",StartPosition=FormStartPosition.Manual,Bounds=new Rectangle(-3500,-3500,640,480),FormBorderStyle=FormBorderStyle.SizableToolWindow,ShowInTaskbar=true}){child.Controls.Add(new Label{Text="Cross-process launched game",Dock=DockStyle.Fill});Application.Run(child);}return 0;}try{Application.EnableVisualStyles();Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException);Run();Console.WriteLine("PASS: "+checks+" actual emulator, embedded-library, modal-game launch routing and retained-process checks.");return 0;}catch(Exception error){Console.Error.WriteLine(error);return 1;}finally{foreach(var process in owned){try{if(IsOwned(process)){process.Kill();process.WaitForExit();}}catch{}process.Dispose();}if(childExe!=null){foreach(var process in Process.GetProcessesByName(Path.GetFileNameWithoutExtension(childExe))){try{if(IsOwned(process)){process.Kill();process.WaitForExit();}}catch{}process.Dispose();}}}}
 static void Run(){
  childExe=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"FishBowlLaunchFixture-"+Guid.NewGuid().ToString("N")+".exe");File.Copy(Assembly.GetExecutingAssembly().Location,childExe);began=DateTime.UtcNow.AddSeconds(-1);
  using(var main=new MainForm(true)){
   main.ShowInTaskbar=false;main.StartPosition=FormStartPosition.Manual;main.Location=new Point(-4500,-4500);main.Show();Pump(150);
   var data=(LibraryData)Field(main,"library");NextData.Ensure(data);data.Emulators.Clear();data.Games.Clear();data.Theme.ConfirmBeforeGameLaunch=false;data.Theme.ConfirmBeforeEmulatorLaunch=false;Immersion.Ensure(data).LaunchPresentation=false;Immersion.Ensure(data).Recap=false;
   var tabs=(TabControl)Field(main,"workspaceNavigation");Check(tabs.TabCount==4&&tabs.TabPages[3].Text=="Play","actual launch targets the fourth Play workspace");
   var emulator=new EmulatorProfile{Id="launch-fixture",Name="Fixture emulator",Executable=childExe,Arguments="--child",Extensions=new List<string>(),LaunchProfiles=new List<LaunchProfile>()};data.Emulators.Add(emulator);
   typeof(MainForm).GetMethod("OpenEmulator",Private).Invoke(main,new object[]{emulator,"--child","Fixture emulator"});var host=Attached(main);var process=Record(host);IntPtr window=host.GameWindow;Check(tabs.SelectedIndex==3,"OpenEmulator selects Play after starting a native executable");
   string originalPath=childExe;var shortPath=new System.Text.StringBuilder(512);uint shortLength=GetShortPathName(originalPath,shortPath,(uint)shortPath.Capacity);
   var expandedAlias=new System.Text.StringBuilder(32768); uint expandedLength=shortLength>0&&shortLength<shortPath.Capacity?GetLongPathName(shortPath.ToString(),expandedAlias,(uint)expandedAlias.Capacity):0;
   if(expandedLength>0&&expandedLength<expandedAlias.Capacity){Check(MatchesIdentity(process,shortPath.ToString(),began),"8.3 executable/directory aliases preserve exact fixture ownership: "+OwnershipDetails(process)+" short="+shortPath+" canonical-short="+Canonical(shortPath.ToString()));}else{Console.WriteLine("Short-path alias check unavailable: Windows did not expand this fixture alias. Exact executable and creation-time checks remain enabled.");}
   Check(!MatchesIdentity(process,childExe,DateTime.UtcNow.AddMinutes(1)),"canonical path does not bypass process creation-time guard");
   string otherDirectory=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"other-fixture");Directory.CreateDirectory(otherDirectory);string otherPath=Path.Combine(otherDirectory,Path.GetFileName(childExe));File.Copy(childExe,otherPath);Check(!MatchesIdentity(process,otherPath,began),"same filename and bytes at a different path are not owned");
Check(host.IsAttached&&((!host.IsAnchored&&GetParent(window)==host.Handle)||(host.IsAnchored&&GetWindow(window,4)==main.Handle)),"OpenEmulator integrates the actual native window using reparenting or verified anchored DPI fallback");host.Detach();Check(GetParent(window)==IntPtr.Zero&&!process.HasExited,"detaching leaves actual emulator process alive in its original top-level window");Stop(process,window);
   var game=new GameEntry{Id="launch-game",Title="Native launch fixture",Path=childExe,Arguments="--child",Extras=new GameExtras{Native=true}};data.Games.Add(game);var library=(GameLibraryDialog)Field(main,"embeddedLibrary");tabs.SelectedIndex=2;ExperienceTools.Launch(library,data,game);host=Attached(main);process=Record(host);window=host.GameWindow;Check(tabs.SelectedIndex==3&&game.LaunchCount==1,"embedded Library native game launch routes into Play and records launch");Check(IsWindowEnabled(main.Handle),"embedded Library launch leaves MainForm enabled");host.Detach();Stop(process,window);
   bool launchReturned=false;Exception timerError=null;using(var modal=new Form{Text="Modal launch fixture",ShowInTaskbar=false,StartPosition=FormStartPosition.Manual,Location=new Point(-4000,-4000)})using(var timer=new System.Windows.Forms.Timer{Interval=100})using(var watchdog=new System.Windows.Forms.Timer{Interval=15000}){
    timer.Tick+=delegate{timer.Stop();try{Check(!IsWindowEnabled(main.Handle),"native modal owner disables MainForm before launch");ExperienceTools.Launch(modal,data,game);launchReturned=true;}catch(Exception error){timerError=error;modal.Close();}};watchdog.Tick+=delegate{watchdog.Stop();timerError=new Exception("Modal launch did not close its owner within the bounded launch timeout");modal.Close();};watchdog.Start();timer.Start();modal.ShowDialog(main);
   }
   if(timerError!=null)throw timerError;Check(launchReturned,"successful game launch returns from the modal launch owner");Check(IsWindowEnabled(main.Handle),"successful modal launch closes owner and reenables MainForm");host=Attached(main);process=Record(host);window=host.GameWindow;Check(tabs.SelectedIndex==3&&game.LaunchCount==2,"modal native launch routes to Play and retains launch bookkeeping");
   main.Close();main.Dispose();Check(!process.HasExited&&IsWindow(window)&&GetParent(window)==IntPtr.Zero,"closing FishBowl preserves and detaches the launched game process");Stop(process,window);
  }
 }
}



