using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Windows.Forms;
using EmulatorHub;
class PolishTests {
 static int checks;static BindingFlags flags=BindingFlags.Instance|BindingFlags.NonPublic;static object Field(object o,string n){return o.GetType().GetField(n,flags).GetValue(o);}static void Call(object o,string n){o.GetType().GetMethod(n,flags).Invoke(o,null);}static void Check(bool b,string n){if(!b)throw new Exception(n);checks++;}static void Throws(Action a,string n){bool failed=false;try{a();}catch{failed=true;}Check(failed,n);}static void Pump(int ms){var w=Stopwatch.StartNew();while(w.ElapsedMilliseconds<ms){Application.DoEvents();Thread.Sleep(10);}}
 [STAThread]static int Main(){try{return Run();}catch(Exception ex){Console.Error.WriteLine(ex);return 1;}}static int Run(){Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException);Application.EnableVisualStyles();var d=Store.Load();d.Games=new List<GameEntry>();d.Emulators=new List<EmulatorProfile>();d.Collections=new List<GameCollection>();d.SaveSnapshots=new List<SaveSnapshot>();d.UserTools=null;d.Experience=new ExperienceSettings();NextData.Ensure(d);LibraryAdditions.Ensure(d);File.WriteAllText("game.rom","fixture");using(var art=new Bitmap(64,64)){using(var gr=Graphics.FromImage(art))gr.Clear(Color.Orange);art.Save("cover.png");}string gamePath=Path.GetFullPath("game.rom");for(int i=0;i<2000;i++)d.Games.Add(new GameEntry{Id="game"+i,Title="Game "+i.ToString("0000"),Path=gamePath,ArtworkPath=Path.GetFullPath("cover.png"),Tags=new List<string>()});var s=UserTools.Ensure(d);string first=s.ActiveId;var second=UserTools.Create(d,"Another");
  using(var f=new GameLibraryDialog(d)){f.ShowInTaskbar=false;f.StartPosition=FormStartPosition.Manual;f.Location=new Point(-3000,-3000);var clock=Stopwatch.StartNew();f.Show();Pump(200);clock.Stop();Console.WriteLine("2000-game construction: "+clock.ElapsedMilliseconds+" ms");var list=(ListView)Field(f,"games");Check(list.Items.Count==2000,"large library loads all rows");var row=list.Items[20];row.Selected=true;list.TopItem=list.Items[15];Call(f,"RememberNavigation");Console.WriteLine("Navigation: selected="+s.Navigation.SelectedId+", top="+s.Navigation.TopId);Check(s.Navigation.SelectedId=="game20"&&!string.IsNullOrWhiteSpace(s.Navigation.TopId),"navigation captures selection and scroll");d.Games[20].Favorite=true;Call(f,"RefreshGames");Check(object.ReferenceEquals(row,list.Items[20])&&row.Text.Contains("★"),"metadata update reuses row and updates contents");
   ((TextBox)Field(f,"search")).Text="Game 0020";Pump(450);Check(list.Items.Count==1,"search debounces then filters");((TextBox)Field(f,"search")).Clear();Pump(450);Call(f,"ToggleGameView");Pump(1600);var images=(ImageList)Field(f,"coverImages");Check(images.Images.Count>1&&images.Images.Count<128,"artwork loads only viewport thumbnails");var cached=(System.Collections.IDictionary)Field(f,"thumbnailSlots");object cachedKey=cached.Keys.Cast<object>().First();object cachedSlot=cached[cachedKey];Call(f,"RefreshGames");Check(cached.Contains(cachedKey)&&cached[cachedKey].Equals(cachedSlot),"refresh retains cached artwork");Call(f,"RememberNavigation");Check(s.Navigation.Artwork,"artwork view remembered");UserTools.Switch(d,second.Id);f.ReloadLibrary();Check(string.IsNullOrEmpty(((TextBox)Field(f,"search")).Text),"new user gets fresh filters");((TextBox)Field(f,"search")).Text="Game 0040";Pump(450);Call(f,"RememberNavigation");UserTools.Switch(d,first);f.ReloadLibrary();Check(((TextBox)Field(f,"search")).Text==""&&list.Items.Count==2000,"original user navigation restored");UserTools.Switch(d,second.Id);f.ReloadLibrary();Check(((TextBox)Field(f,"search")).Text=="Game 0040"&&list.Items.Count==1,"second user filter restored");Check(list.AccessibleName=="FishBowl game list"&&list.AccessibleDescription.Contains("Enter"),"library has meaningful screen-reader instructions");f.Close();}
  Store.Save(d);var reloaded=Store.Load();Check(reloaded.UserTools.Navigation.Search=="Game 0040","navigation survives persistence");
  var e=new EmulatorProfile{Id="emulator",Name="Dolphin",Executable=Path.GetFullPath("Dolphin.exe")};d.Emulators.Add(e);s=UserTools.Ensure(d);s.SaveRoutes=new List<SaveRouting>{new SaveRouting{EmulatorId=e.Id,Mode="Dolphin user directory"}};string root=UserSaveRoutes.Root(d,e);string args=UserSaveRoutes.Apply(d,e,"--exec \"game.rom\"",false);Check(args.Contains("--user")&&args.Contains(root),"Dolphin receives isolated user-directory flag");Check(!Directory.Exists(root),"route preview never creates directories");UserSaveRoutes.Arguments(d,e,true);Check(Directory.Exists(Path.Combine(root,"User")),"launch preparation creates isolated directory");Throws(()=>UserSaveRoutes.Apply(d,e,"--user somewhere",false),"conflicting user-folder flag rejected");Throws(()=>UserSaveRoutes.Apply(d,e,"-u somewhere",false),"short conflicting flag rejected");UserTools.Switch(d,first);Check(UserSaveRoutes.Arguments(d,e,false)=="","routing off for other profile");string other=UserSaveRoutes.Root(d,e);Check(other!=root,"profile managed paths differ");s=UserTools.Ensure(d);s.SaveRoutes=new List<SaveRouting>{new SaveRouting{EmulatorId=e.Id,Mode="RetroArch save folders"}};e.Executable=Path.GetFullPath("retroarch.exe");string ra=UserSaveRoutes.Arguments(d,e,true);Check(ra.StartsWith("--appendconfig"),"RetroArch receives appended config");string cfg=Path.Combine(UserSaveRoutes.Root(d,e),"FishBowl-saves.cfg");Check(File.ReadAllText(cfg).Contains("savefile_directory")&&File.ReadAllText(cfg).Contains("savestate_directory")&&File.ReadAllText(cfg).Contains("config_save_on_exit = false"),"RetroArch config routes saves and preserves base config");s.SaveRoutes[0].Mode="Custom arguments";s.SaveRoutes[0].Arguments="--saves {saves} --states {states}";Check(UserSaveRoutes.Arguments(d,e,false).Contains("--saves \""),"custom routing paths quoted");s.SaveRoutes[0].Arguments="--saves {unknown}";Throws(()=>UserSaveRoutes.Arguments(d,e,false),"unknown custom tokens rejected");s.SaveRoutes[0].Mode="Dolphin user directory";Throws(()=>UserSaveRoutes.Arguments(d,e,false),"adapter/executable mismatch rejected");s.SaveRoutes.Clear();
  d.Games[0].Path="missing.rom";d.Games[0].ArtworkPath="missing.png";d.Games[0].EmulatorId="emulator";e.Executable="missing.exe";d.BackupFolder="missing-backup-folder";var issues=Polish.Health(d,CancellationToken.None);Check(issues.Any(x=>x.Area=="Game file"&&x.GameId==d.Games[0].Id),"health identifies missing game");Check(issues.Any(x=>x.Area=="Artwork"),"health identifies missing artwork");Check(issues.Any(x=>x.Area=="Emulator"),"health identifies unavailable emulator");Check(issues.Any(x=>x.Area=="Backup"),"health identifies missing backup folder");var cancel=new CancellationTokenSource();cancel.Cancel();Throws(()=>Polish.Health(d,cancel.Token),"health scanning cancels");Check(Polish.DeviceReport(d).Contains("Connected XInput controller"),"device report includes hardware availability");Console.WriteLine("Connected XInput controller: "+UserToolRuntime.ControllerConnected());
  string preview=Polish.BulkSummary(new[]{d.Games[0]},"Keep current","Completed","Favorite","Keep current","new","","None");Check(preview.Contains("Status:")&&preview.Contains("→ Completed")&&preview.Contains("Favorite:")&&preview.Contains("Tags:"),"bulk review shows concrete changed fields");Check(!preview.Contains("Artwork:"),"unchanged fields absent from bulk review");Check(Polish.ImportSummary(d,reloaded).Contains("Games:")&&Polish.ImportSummary(d,reloaded).Contains("User profiles:"),"import review includes before and after counts");
  using(var owner=new Form{ShowInTaskbar=false,StartPosition=FormStartPosition.Manual,Location=new Point(-3000,-3000)}){owner.Show();using(var timer=new System.Windows.Forms.Timer{Interval=250}){timer.Tick+=(a,b)=>{var f=Application.OpenForms.OfType<NextDialog>().FirstOrDefault(x=>x.Text=="Review fixture");if(f==null)return;timer.Stop();Check(NextUi.Descendants(f).OfType<TextBox>().Single().ReadOnly,"review contents cannot be edited accidentally");NextUi.Descendants(f).OfType<Button>().Single(x=>x.Text=="Cancel").PerformClick();};timer.Start();Check(!Polish.Review(owner,"Review fixture","Before → After"),"cancel review returns false");}}
  var empty=UserTools.Copy(d);empty.Games.Clear();empty.UserTools.Navigation=null;using(var f=new GameLibraryDialog(empty)){f.ShowInTaskbar=false;f.StartPosition=FormStartPosition.Manual;f.Location=new Point(-3000,-3000);f.Show();Pump(200);var panel=(Panel)Field(f,"emptyState");Check(panel.Visible&&panel.Height>100,"empty library shows usable guidance panel");Check(NextUi.Descendants(panel).OfType<Button>().Any(x=>x.Text=="Add game"),"empty library has next action");using(var bitmap=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bitmap,new Rectangle(Point.Empty,bitmap.Size));bitmap.Save("empty-library.png");}}
  using(var f=new NextDialog("Accessibility fixture")){var table=NextDialog.Fields(f.Body);var box=new TextBox();NextDialog.Field(table,"User name",box);f.Action("Save",()=>{});Polish.Accessibility(f);Check(box.AccessibleName=="User name","field retains its descriptive accessible name");Check(NextUi.Descendants(f).OfType<Button>().All(b=>!string.IsNullOrWhiteSpace(b.AccessibleName)),"all action buttons have accessible names");using(var tabs=new FishBowlTabs{PreferredColumns=3,Width=800}){tabs.Font=new Font("Segoe UI",20);tabs.TabPages.Add("Long label");tabs.FitTabs();Check(tabs.ItemSize.Height>=tabs.Font.Height+12,"tabs grow for large text");}}
  foreach(int percent in new[]{100,125,150,200}){NextUi.TextPercent=percent;using(var f=new GameLibraryDialog(empty)){f.ShowInTaskbar=false;f.StartPosition=FormStartPosition.Manual;f.Location=new Point(-3000,-3000);f.Show();Pump(150);var header=((TextBox)Field(f,"search")).Parent;var filters=header.Controls.OfType<FlowLayoutPanel>().Single();Check(header.Height>=filters.Height+60,"header adapts at "+percent+"%");var panel=(Panel)Field(f,"emptyState");Check(panel.Height>80,"empty guidance keeps room at "+percent+"%");using(var bitmap=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bitmap,new Rectangle(Point.Empty,bitmap.Size));bitmap.Save("library-text-"+percent+".png");}}}NextUi.TextPercent=100;
  using(var f=new Form{ShowInTaskbar=false,StartPosition=FormStartPosition.Manual,Location=new Point(-3000,-3000)}){var number=new NumericUpDown{Minimum=0,Maximum=100,Value=10};f.Controls.Add(number);f.Show();number.Focus();UserToolRuntime.ApplyButtons(f,f,8);Check(number.Value==11,"controller adjusts focused numeric field");UserToolRuntime.ApplyButtons(f,f,4);Check(number.Value==10,"controller reverses numeric adjustment");}
  Console.WriteLine("PASS: "+checks+" polish checks covering large libraries, row reuse, lazy artwork, navigation, save routing, health, reviews and accessibility.");return 0;
 }
}
