using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace EmulatorHub {
 public class LibraryNavigation {
  public string Search {get;set;} public string Scope {get;set;} public string Console {get;set;}
  public string Emulator {get;set;} public string Saves {get;set;} public string Sort {get;set;}
  public string Tags {get;set;} public string SelectedId {get;set;} public string TopId {get;set;} public bool Artwork {get;set;}
 }
 public class SaveRouting {
  public string EmulatorId {get;set;} public string Mode {get;set;} public string Arguments {get;set;}
 }
 public class HealthIssue {public string Area {get;set;} public string Message {get;set;} public string GameId {get;set;}}
 public static class Polish {
  public static bool Review(IWin32Window owner,string title,string beforeAfter){using(var f=new NextDialog(title,850,600)){f.Body.Controls.Add(new TextBox{Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Both,Dock=DockStyle.Fill,Text=beforeAfter,WordWrap=false,AccessibleName="Changes to review"});f.Action("Apply reviewed changes",()=>f.DialogResult=DialogResult.OK);f.Action("Cancel",()=>f.DialogResult=DialogResult.Cancel);return f.ShowDialog(owner)==DialogResult.OK;}}
  public static string ImportSummary(LibraryData current,LibraryData incoming){return "Replace these FishBowl settings. Game and save files themselves will not be moved.\r\nA restore point will be created before replacement.\r\n\r\n"+"Games: "+current.Games.Count+" → "+(incoming.Games??new List<GameEntry>()).Count+"\r\nEmulators: "+current.Emulators.Count+" → "+incoming.Emulators.Count+"\r\nUser profiles: "+UserTools.Ensure(current).Users.Count+" → "+(incoming.UserTools==null||incoming.UserTools.Users==null?1:incoming.UserTools.Users.Count)+"\r\nTheme: "+(current.Theme==null?"Default":current.Theme.Name)+" → "+(incoming.Theme==null?"Default":incoming.Theme.Name)+"\r\n\r\nIncoming games (first 100):\r\n"+string.Join("\r\n",(incoming.Games??new List<GameEntry>()).Take(100).Select(g=>g.Title+" | "+g.Path));}
  public static string BulkSummary(IEnumerable<GameEntry> games,string emulator,string status,string favorite,string pinned,string tags,string art,string collection){var b=new StringBuilder("Only the following fields will change. Other fields and game/save files stay unchanged.\r\n\r\n");foreach(var g in games){b.AppendLine(g.Title);if(emulator!="Keep current")b.AppendLine("  Emulator assignment → "+emulator);if(status!="Keep current")b.AppendLine("  Status: "+g.PlayStatus+" → "+status);if(favorite!="Keep current")b.AppendLine("  Favorite: "+g.Favorite+" → "+(favorite=="Favorite"));if(pinned!="Keep current")b.AppendLine("  Pinned: "+g.Pinned+" → "+(pinned=="Pin"));if(!string.IsNullOrWhiteSpace(tags))b.AppendLine("  Tags: "+string.Join(", ",g.Tags??new List<string>())+" → add "+tags);if(!string.IsNullOrWhiteSpace(art))b.AppendLine("  Artwork: "+g.ArtworkPath+" → "+art);if(collection!="None")b.AppendLine("  Collection → add to "+collection);b.AppendLine();}return b.ToString();}
  public static List<HealthIssue> Health(LibraryData d,CancellationToken token){var issues=new List<HealthIssue>();foreach(var g in d.Games){token.ThrowIfCancellationRequested();if(!File.Exists(NextData.LaunchPath(g)))issues.Add(new HealthIssue{Area="Game file",GameId=g.Id,Message=g.Title+": missing file. Choose a replacement in Repair game paths."});var e=ExperienceData.Emulator(d,g);if(!Hub.Native(g)&&(e==null||!File.Exists(NextData.LaunchEmulator(d,g).Executable)))issues.Add(new HealthIssue{Area="Emulator",GameId=g.Id,Message=g.Title+": assign an available emulator in game settings."});if(string.IsNullOrWhiteSpace(g.ArtworkPath)||!File.Exists(g.ArtworkPath))issues.Add(new HealthIssue{Area="Artwork",GameId=g.Id,Message=g.Title+": artwork unavailable. Choose a local image in game settings."});foreach(var save in g.Saves??new List<GameSaveEntry>())if(!File.Exists(save.Path)&&!Directory.Exists(save.Path))issues.Add(new HealthIssue{Area="Linked save",GameId=g.Id,Message=g.Title+": linked save unavailable; review its save associations."});}foreach(var s in d.SaveSnapshots??new List<SaveSnapshot>()){token.ThrowIfCancellationRequested();if(!File.Exists(s.Path)&&!Directory.Exists(s.Path))issues.Add(new HealthIssue{Area="Backup",GameId=s.GameId,Message="Missing save snapshot: "+s.Path});}if(!string.IsNullOrWhiteSpace(d.BackupFolder)&&!Directory.Exists(d.BackupFolder))issues.Add(new HealthIssue{Area="Backup",Message="Configured backup folder is unavailable: "+d.BackupFolder});return issues;}
  public static void HealthScreen(IWin32Window owner,LibraryData d){var issues=BackgroundWork<List<HealthIssue>>.Run(owner,"Check Library health",(token,progress)=>{progress("Checking configured files and folders…");return Health(d,token);});if(issues==null)return;using(var f=new NextDialog("Library health")){var list=new ListView{Dock=DockStyle.Fill,View=View.Details,FullRowSelect=true,HideSelection=false,AccessibleName="Library health issues"};list.Columns.Add("Area",120);list.Columns.Add("Issue and next step",660);foreach(var issue in issues)list.Items.Add(new ListViewItem(new[]{issue.Area,issue.Message}){Tag=issue});if(issues.Count==0)list.Items.Add(new ListViewItem(new[]{"Ready","No missing configured files detected. Emulator compatibility still needs a game test."}));f.Body.Controls.Add(list);f.Action("Resolve selected game",()=>{if(list.SelectedItems.Count==0)return;var issue=list.SelectedItems[0].Tag as HealthIssue;var g=issue==null?null:d.Games.FirstOrDefault(x=>x.Id==issue.GameId);if(g!=null)UserTools.Troubleshoot(f,d,g,null);else UserTools.Report(f,"Backup issue","Use Backup verification and retention to select a known archive. Reconnect missing backup drives before restoring.");});f.Action("Verify save snapshots",()=>{var result=BackgroundWork<string>.Run(f,"Verify snapshot contents",(token,progress)=>{var b=new StringBuilder();foreach(var snapshot in d.SaveSnapshots??new List<SaveSnapshot>()){token.ThrowIfCancellationRequested();progress(snapshot.Path);try{SaveHistory.Verify(snapshot,token);b.AppendLine("Verified: "+snapshot.Path);}catch(OperationCanceledException){throw;}catch(Exception ex){b.AppendLine("Issue: "+snapshot.Path+" — "+ex.Message);}}return b.Length==0?"No save snapshots yet. Create a snapshot from Saves and history first.":b.ToString();});if(result!=null)UserTools.Report(f,"Snapshot verification",result);});f.Action("Repair game paths",()=>ExperienceTools.Relink(f,d));f.Action("Close",f.Close);f.ShowDialog(owner);}}
  public static string DeviceReport(LibraryData d){var b=new StringBuilder("Connected XInput controller: "+(UserToolRuntime.ControllerConnected()?"detected":"none detected")+"\r\n\r\nEmulator installations:\r\n");foreach(var e in d.Emulators){try{b.AppendLine(e.Name+": "+(File.Exists(e.Executable)?FileVersionInfo.GetVersionInfo(e.Executable).FileVersion:"executable missing"));}catch(Exception ex){b.AppendLine(e.Name+": "+ex.Message);}}b.AppendLine("\r\nFor a real game check: use a copy of a game you own, select an isolated save route where supported, launch, verify controller navigation, close the emulator, then check the session journal. Break reminders depend on Windows notification settings. This inventory does not claim game compatibility.");return b.ToString();}
  public static void Accessibility(Control root){var fields=root as TableLayoutPanel;if(fields!=null){for(int row=0;row<fields.RowStyles.Count;row++){if(fields.RowStyles[row].SizeType!=SizeType.Absolute||fields.RowStyles[row].Height==0)continue;int height=(int)fields.RowStyles[row].Height;for(int column=0;column<fields.ColumnCount;column++){var control=fields.GetControlFromPosition(column,row);if(control==null)continue;height=Math.Max(height,control.Font.Height+24);if(control is Label)height=Math.Max(height,TextRenderer.MeasureText(control.Text,control.Font,new Size(Math.Max(100,control.Width),1000),TextFormatFlags.WordBreak).Height+16);if(control is FlowLayoutPanel)height=Math.Max(height,control.GetPreferredSize(new Size(Math.Max(100,control.Width),0)).Height+16);}fields.RowStyles[row].Height=height;}var panel=fields.Parent as Panel;if(panel!=null)panel.AutoScroll=true;}int index=0;foreach(Control c in root.Controls){c.TabIndex=index++;if(string.IsNullOrWhiteSpace(c.AccessibleName)){if(c is Button||c is CheckBox||c is Label||c is TabPage)c.AccessibleName=c.Text.Replace("&","");else if(c is ComboBox)c.AccessibleName="Choose an option";else if(c is ListView||c is ListBox)c.AccessibleName="Items";}if(c is Button){c.AccessibleRole=AccessibleRole.PushButton;if(c.Parent is FlowLayoutPanel){var action=c as FishBowlActionButton;if(action==null||!action.IconOnly)c.Width=Math.Max(c.Width,TextRenderer.MeasureText(c.Text,c.Font).Width+56);c.Height=Math.Max(c.Height,c.Font.Height+16);}}if(c is TextBoxBase&&((TextBoxBase)c).ReadOnly)c.TabStop=true;Accessibility(c);}if(fields!=null)for(int row=0;row<fields.RowStyles.Count;row++){if(fields.RowStyles[row].SizeType!=SizeType.Absolute||fields.RowStyles[row].Height==0)continue;for(int column=0;column<fields.ColumnCount;column++){var flow=fields.GetControlFromPosition(column,row) as FlowLayoutPanel;if(flow!=null)fields.RowStyles[row].Height=Math.Max(fields.RowStyles[row].Height,flow.GetPreferredSize(new Size(Math.Max(100,flow.Width),0)).Height+16);}}var toolbar=root as FlowLayoutPanel;if(toolbar!=null&&toolbar.Name=="FishBowlToolbar")toolbar.Height=Math.Max(48,toolbar.Controls.OfType<Button>().Select(b=>b.Height+b.Margin.Vertical+toolbar.Padding.Vertical).DefaultIfEmpty(48).Max());root.AccessibleDescription=string.IsNullOrWhiteSpace(root.AccessibleDescription)?"Use Tab and Shift+Tab to move between controls. Enter activates the focused command.":root.AccessibleDescription;}
 }
 public static class UserSaveRoutes {
  static string Identity(string value){using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(value??""))).Replace("-","").Substring(0,32);}
  public static string Root(LibraryData d,EmulatorProfile emulator){return Path.Combine(Store.DataDirectory,"UserEmulatorData",Identity(UserTools.Ensure(d).ActiveId),Identity(emulator.Id));}
  public static SaveRouting Route(LibraryData d,EmulatorProfile emulator){return (UserTools.Ensure(d).SaveRoutes??new List<SaveRouting>()).FirstOrDefault(r=>r.EmulatorId==emulator.Id);}
  public static string Arguments(LibraryData d,EmulatorProfile e,bool create){var r=Route(d,e);if(r==null||r.Mode=="Off"||string.IsNullOrWhiteSpace(r.Mode))return "";string root=Root(d,e);string saves=Path.Combine(root,"Saves"),states=Path.Combine(root,"States"),user=Path.Combine(root,"User");string result;
   if(r.Mode=="Dolphin user directory"){if(!Path.GetFileNameWithoutExtension(e.Executable).Equals("Dolphin",StringComparison.OrdinalIgnoreCase))throw new IOException("Dolphin save routing requires Dolphin.exe. Review this emulator's route.");result="--user "+Quote(user);if(create)Directory.CreateDirectory(user);}
   else if(r.Mode=="RetroArch save folders"){if(!Path.GetFileNameWithoutExtension(e.Executable).StartsWith("retroarch",StringComparison.OrdinalIgnoreCase))throw new IOException("RetroArch save routing requires a RetroArch executable.");string config=Path.Combine(root,"FishBowl-saves.cfg");result="--appendconfig "+Quote(config);if(create){Directory.CreateDirectory(saves);Directory.CreateDirectory(states);File.WriteAllText(config,"savefile_directory = "+Quote(saves.Replace('\\','/'))+"\n"+"savestate_directory = "+Quote(states.Replace('\\','/'))+"\nconfig_save_on_exit = false\n",new UTF8Encoding(false));}}
   else if(r.Mode=="Custom arguments"){if(string.IsNullOrWhiteSpace(r.Arguments)||!(r.Arguments.Contains("{saves}")||r.Arguments.Contains("{states}")||r.Arguments.Contains("{user}")))throw new IOException("Custom routing must use {saves}, {states} or {user}, without extra quotes around the token.");result=r.Arguments.Replace("{saves}",Quote(saves)).Replace("{states}",Quote(states)).Replace("{user}",Quote(user));if(result.Contains("{")||result.Contains("}"))throw new IOException("Unknown save-routing token.");if(create){Directory.CreateDirectory(saves);Directory.CreateDirectory(states);Directory.CreateDirectory(user);}}
   else throw new IOException("Unknown save-routing mode.");return result;
  }
  static string Quote(string path){if(path.Contains("\"")||path.Contains("\r")||path.Contains("\n"))throw new IOException("Invalid save path.");return "\""+path+"\"";}
  public static string Apply(LibraryData d,EmulatorProfile e,string args,bool create){string routing=Arguments(d,e,false);if(string.IsNullOrEmpty(routing))return args;var r=Route(d,e);string[] switches=r.Mode=="Dolphin user directory"?new[]{"--user","-u"}:r.Mode=="RetroArch save folders"?new[]{"--appendconfig","--save","--savestate","-s","-S"}:new string[0];if(switches.Any(flag=>System.Text.RegularExpressions.Regex.IsMatch(args??"","(^|\\s)"+System.Text.RegularExpressions.Regex.Escape(flag)+"(\\s|=|$)")))throw new IOException("Existing arguments already choose a user/save configuration. Remove that override or disable per-user routing to avoid conflicting locations.");return (args+" "+Arguments(d,e,create)).Trim();}
  public static void Show(IWin32Window owner,LibraryData d){if(UserTools.Guest)return;using(var f=new NextDialog("Per-user emulator saves")){var fields=NextDialog.Fields(f.Body);var choice=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,DisplayMember="Name"};choice.Items.AddRange(d.Emulators.Cast<object>().ToArray());var mode=NextDialog.Choice(new[]{"Off","Dolphin user directory","RetroArch save folders","Custom arguments"},"Off");var args=new TextBox();var location=new TextBox{ReadOnly=true};NextDialog.Field(fields,"Emulator",choice);NextDialog.Field(fields,"Routing",mode);NextDialog.Field(fields,"Custom arguments",args,70);NextDialog.Field(fields,"Current user's managed folder",location,70);NextDialog.Field(fields,"Scope",new Label{Text="Off is the default. Dolphin isolates its entire user directory, including settings and Wii data. RetroArch routes save files and states. Custom flags require emulator support. Existing saves are never moved or copied automatically; a new route starts empty. Overrides inside the emulator can still affect save locations.",AutoSize=true},180);
   choice.SelectedIndexChanged+=(a,b)=>{var e=choice.SelectedItem as EmulatorProfile;if(e==null)return;var r=Route(d,e);mode.SelectedItem=r==null?"Off":r.Mode;args.Text=r==null?"":r.Arguments;location.Text=Root(d,e);};if(choice.Items.Count>0)choice.SelectedIndex=0;
   f.Action("Preview and save",()=>{var e=choice.SelectedItem as EmulatorProfile;if(e==null)throw new IOException("Add an emulator first.");if(UserTools.ActiveLaunches>0)throw new IOException("Close emulator sessions before changing save routing.");var s=UserTools.Ensure(d);var proposed=new SaveRouting{EmulatorId=e.Id,Mode=mode.Text,Arguments=args.Text};var clone=UserTools.Copy(d);var routes=UserTools.Ensure(clone).SaveRoutes??new List<SaveRouting>();routes.RemoveAll(r=>r.EmulatorId==e.Id);routes.Add(proposed);clone.UserTools.SaveRoutes=routes;string preview=Arguments(clone,e,false);if(!Polish.Review(f,"Review per-user save routing","Emulator: "+e.Name+"\r\nUser: "+s.Users.First(u=>u.Id==s.ActiveId).Name+"\r\nOld route: "+(Route(d,e)==null?"Off":Route(d,e).Mode)+"\r\nNew route: "+proposed.Mode+"\r\nManaged folder: "+Root(d,e)+"\r\nAdded launch arguments: "+preview+"\r\n\r\nNo original saves or configurations will be moved or overwritten. New folders are created on launch. Dolphin's new user folder needs its own setup."))return;if(s.SaveRoutes==null)s.SaveRoutes=new List<SaveRouting>();s.SaveRoutes.RemoveAll(r=>r.EmulatorId==e.Id);s.SaveRoutes.Add(proposed);Store.Save(d);f.Close();});f.Action("Close",f.Close);f.ShowDialog(owner);}}
 }
 public partial class GameLibraryDialog {
  readonly System.Windows.Forms.Timer polishTimer=new System.Windows.Forms.Timer{Interval=220};
  readonly Dictionary<string,ListViewItem> reusableRows=new Dictionary<string,ListViewItem>();
  readonly Dictionary<string,string> fileSizes=new Dictionary<string,string>();DateTime statExpiry;
  readonly Dictionary<string,int> thumbnailSlots=new Dictionary<string,int>();readonly Dictionary<int,HashSet<ListViewItem>> slotOwners=new Dictionary<int,HashSet<ListViewItem>>();
  bool thumbnailBusy,polishReady,refreshingRows;int nextSlot=1,artSize;string artStyle,viewUser;Panel emptyState;DateTime searchDue;bool searchQueued;
  bool fittingHeader;
  void FitLibraryHeader(){if(fittingHeader||search.Parent==null)return;var header=search.Parent as Panel;if(header==null)return;fittingHeader=true;try{var labels=header.Controls.OfType<Label>().OrderBy(l=>l.Top).ToList();var filters=header.Controls.OfType<FlowLayoutPanel>().FirstOrDefault();if(labels.Count<2||filters==null)return;int available=Math.Max(200,header.ClientSize.Width-header.Padding.Horizontal-filters.Padding.Horizontal-8);foreach(var box in filters.Controls.OfType<ComboBox>()){int width=TextRenderer.MeasureText(box.Text,box.Font).Width+42;box.Width=Math.Max(120,Math.Min(300,width));}int rowsHeight=0,rowWidth=0,rowHeight=0;foreach(Control c in filters.Controls){int width=c.Width+c.Margin.Horizontal;int height=Math.Max(c.Height,c.Font.Height+12)+c.Margin.Vertical;if(rowWidth>0&&rowWidth+width>available){rowsHeight+=rowHeight;rowHeight=0;rowWidth=0;}rowWidth+=width;rowHeight=Math.Max(rowHeight,height);}filters.Height=Math.Max(66,rowsHeight+rowHeight+filters.Padding.Vertical);labels[0].Location=new Point(18,12);labels[1].Location=new Point(20,labels[0].Bottom+5);bool enlarged=search.Font.Height>20;if(enlarged){int y=labels[1].Bottom+8;search.Location=new Point(20,y);search.Width=Math.Max(180,Math.Min(350,available/2-12));scope.Width=Math.Max(180,Math.Min(320,available-search.Width-12));scope.Location=new Point(search.Right+12,y);header.Height=Math.Max(132,y+Math.Max(search.Height,scope.Height)+filters.Height+20);}else{scope.Width=170;scope.Location=new Point(header.ClientSize.Width-190,22);search.Width=210;search.Location=new Point(scope.Left-220,22);header.Height=Math.Max(132,labels[1].Bottom+filters.Height+12);}}finally{fittingHeader=false;}}
  void InitializePolish(){if(polishReady)return;polishReady=true;games.ShowItemToolTips=true;games.AccessibleDescription="Use arrows to choose games, Enter to launch, and Tab to reach game actions.";games.KeyDown+=(a,b)=>{if(b.KeyCode==Keys.Enter){LaunchGame();b.Handled=true;}else if(b.KeyCode==Keys.Escape){search.Clear();b.Handled=true;}};scope.AccessibleName="Library scope";consoleChoice.AccessibleName="Console filter";emulatorChoice.AccessibleName="Emulator filter";saveChoice.AccessibleName="Save status filter";sortChoice.AccessibleName="Game sorting";tagChoice.AccessibleName="Tag filter";
   emptyState=new Panel{Dock=DockStyle.Fill,Visible=false,BackColor=FishBowlPalette.ThemeSurface};var label=new Label{Dock=DockStyle.Top,Height=100,Padding=new Padding(24),ForeColor=FishBowlPalette.ThemeInk,Text="No games yet. Add a game or scan a configured game folder to begin."};emptyState.Controls.Add(label);var actions=ExperienceUi.Bar();actions.Dock=DockStyle.Top;actions.Controls.Add(ExperienceUi.Button("Add game",AddGame));actions.Controls.Add(ExperienceUi.Button("Clear filters",()=>{buildingLibraryFilters=true;search.Clear();tagChoice.Clear();scope.SelectedIndex=0;consoleChoice.SelectedIndex=0;emulatorChoice.SelectedIndex=0;saveChoice.SelectedIndex=0;buildingLibraryFilters=false;RefreshGames();}));actions.Controls.Add(ExperienceUi.Button("Check Library health",()=>Polish.HealthScreen(this,library)));emptyState.Controls.Add(actions);emptyState.Controls.SetChildIndex(label,0);Controls.Add(emptyState);emptyState.BringToFront();
   polishTimer.Tick+=(a,b)=>{if(searchQueued&&DateTime.UtcNow>=searchDue){searchQueued=false;RefreshGames();}LoadVisibleArtwork();RememberNavigation();};polishTimer.Start();Shown+=(a,b)=>{FitLibraryHeader();RestoreNavigation();RefreshGames();};SizeChanged+=(a,b)=>FitLibraryHeader();foreach(var c in NextUi.Descendants(this))c.FontChanged+=(a,b)=>FitLibraryHeader();FormClosing+=(a,b)=>{RememberNavigation();if(!UserTools.Guest)Store.Save(library);};Disposed+=(a,b)=>{polishTimer.Stop();polishTimer.Dispose();};}
  void QueueLibraryRefresh(){if(buildingLibraryFilters)return;searchQueued=true;searchDue=DateTime.UtcNow.AddMilliseconds(180);}
  void RememberNavigation(){if(!polishReady||buildingLibraryFilters||refreshingRows||UserTools.Guest)return;var s=UserTools.Ensure(library);if(viewUser!=s.ActiveId)return;string top=null;try{if(games.View==View.Details&&games.TopItem!=null)top=((GameEntry)games.TopItem.Tag).Id;else{var item=games.GetItemAt(20,20);if(item!=null)top=((GameEntry)item.Tag).Id;}}catch(InvalidOperationException){}s.Navigation=new LibraryNavigation{Search=search.Text,Scope=scope.Text,Console=consoleChoice.Text,Emulator=emulatorChoice.Text,Saves=saveChoice.Text,Sort=sortChoice.Text,Tags=tagChoice.Text,SelectedId=SelectedGame()==null?null:SelectedGame().Id,TopId=top,Artwork=artworkView};if(s.Views==null)s.Views=new Dictionary<string,LibraryNavigation>();s.Views[artworkView?"Artwork":"Details"]=UserTools.Copy(s.Navigation);}
  void RestoreNavigation(){var s=UserTools.Ensure(library);viewUser=s.ActiveId;var n=s.Navigation;if(n==null)return;buildingLibraryFilters=true;try{search.Text=n.Search??"";tagChoice.Text=n.Tags??"";foreach(var pair in new[]{Tuple.Create(scope,n.Scope),Tuple.Create(consoleChoice,n.Console),Tuple.Create(emulatorChoice,n.Emulator),Tuple.Create(saveChoice,n.Saves),Tuple.Create(sortChoice,n.Sort)})if(pair.Item2!=null&&pair.Item1.Items.Contains(pair.Item2))pair.Item1.SelectedItem=pair.Item2;artworkView=n.Artwork;library.Experience.LibraryView=artworkView?"Artwork":"Details";}finally{buildingLibraryFilters=false;}}
  class RowOrder:IComparer {readonly Dictionary<string,int> positions;public RowOrder(Dictionary<string,int> p){positions=p;}public int Compare(object a,object b){return positions[((GameEntry)((ListViewItem)a).Tag).Id].CompareTo(positions[((GameEntry)((ListViewItem)b).Tag).Id]);}}
  void RefreshLibraryRows(){if(buildingLibraryFilters)return;bool changingProfile=polishReady&&viewUser!=UserTools.Ensure(library).ActiveId;if(changingProfile)RestoreNavigation();bool profileChanged=changingProfile;var selected=new HashSet<string>(games.SelectedItems.Cast<ListViewItem>().Select(x=>((GameEntry)x.Tag).Id));if(profileChanged)selected.Clear();string top=null;try{if(!profileChanged&&games.View==View.Details&&games.TopItem!=null)top=((GameEntry)games.TopItem.Tag).Id;}catch(InvalidOperationException){}var list=VisibleGames().ToList();var wanted=new HashSet<string>(list.Select(g=>g.Id));if(DateTime.UtcNow>statExpiry){fileSizes.Clear();statExpiry=DateTime.UtcNow.AddSeconds(10);}var emulators=library.Emulators.GroupBy(e=>e.Id).ToDictionary(g=>g.Key,g=>g.First());bool orderChanged=!games.Items.Cast<ListViewItem>().Select(x=>((GameEntry)x.Tag).Id).SequenceEqual(list.Select(g=>g.Id));refreshingRows=true;games.BeginUpdate();try{foreach(var removed in reusableRows.Keys.Where(k=>!wanted.Contains(k)).ToArray()){foreach(var owners in slotOwners.Values)owners.Remove(reusableRows[removed]);games.Items.Remove(reusableRows[removed]);reusableRows.Remove(removed);}foreach(var g in list){ListViewItem row;if(!reusableRows.TryGetValue(g.Id,out row)){row=new ListViewItem(new[]{"","","","",""}){Tag=g,ImageIndex=0};reusableRows[g.Id]=row;games.Items.Add(row);}row.Tag=g;EmulatorProfile e;emulators.TryGetValue(string.IsNullOrWhiteSpace(g.PreferredEmulatorId)?g.EmulatorId??"":g.PreferredEmulatorId,out e);if(e==null&&library.Emulators.Count==1)e=library.Emulators[0];string size;string path=g.Path??"";if(!fileSizes.TryGetValue(path,out size)){try{var info=new FileInfo(path);size=info.Exists?FormatBytes(info.Length):"Missing";}catch{size="Unavailable";}fileSizes[path]=size;}if(Hub.Native(g))e=Hub.NativeProfile(g);string[] values={(g.Pinned?"● ":"")+(g.Favorite?"★ ":"")+g.Title+(library.Cosmetics!=null&&library.Cosmetics.PlatformLabels&&!string.IsNullOrWhiteSpace(g.ConsoleLabel)?" ["+g.ConsoleLabel+"]":""),e==null?"Not assigned":e.Name,path,size,string.IsNullOrWhiteSpace(g.LastLaunched)?"Never":g.LastLaunched};for(int i=0;i<values.Length;i++)if(row.SubItems[i].Text!=values[i])row.SubItems[i].Text=values[i];row.ToolTipText=size=="Missing"?"Missing game file. Use Library tools → Repair game paths.":e==null?"Assign an emulator in Game actions → Edit game.":"Enter or double-click to launch. Game actions contains editing and saves.";row.Selected=selected.Contains(g.Id);}
    if(orderChanged&&list.Count>0){var positions=list.Select((g,i)=>new{g.Id,Index=i}).ToDictionary(x=>x.Id,x=>x.Index);games.ListViewItemSorter=new RowOrder(positions);games.Sort();games.ListViewItemSorter=null;}ApplyArtworkView();if(selected.Count==0&&polishReady){var n=UserTools.Ensure(library).Navigation;if(n!=null&&!string.IsNullOrWhiteSpace(n.SelectedId)&&reusableRows.ContainsKey(n.SelectedId))reusableRows[n.SelectedId].Selected=true;if(top==null&&n!=null)top=n.TopId;}if(top!=null&&reusableRows.ContainsKey(top)){if(games.View==View.Details)games.TopItem=reusableRows[top];else reusableRows[top].EnsureVisible();}}
   finally{games.EndUpdate();refreshingRows=false;}if(emptyState!=null){games.Visible=list.Count>0;emptyState.Visible=list.Count==0;emptyState.Controls.OfType<Label>().First().Text=library.Games.Count==0?"No games yet. Add a game or scan a configured folder from Library tools.":"No games match these filters. Clear filters to show your Library, or check Library health for missing files.";if(emptyState.Visible)emptyState.BringToFront();}UpdateSelectionCommands();RememberNavigation();}
  void ApplyLazyArtwork(){UpdateDetailPane();games.TileSize=new Size(Math.Max(130,library.Experience.ArtworkSize+24),library.Experience.ArtworkSize+(library.Cosmetics!=null&&library.Cosmetics.LibrarySpacing=="Compact"?32:55));games.View=artworkView?View.LargeIcon:View.Details;ApplyHubSpacing();if(!artworkView)return;int size=Math.Max(64,Math.Min(192,library.Experience.ArtworkSize));string style=Json.Serialize(CosmeticRuntime.Current)+"|"+FishBowlPalette.ThemeSurface.ToArgb()+"|"+FishBowlPalette.ThemeInk.ToArgb()+"|"+FishBowlPalette.IconAccent.ToArgb();if(size!=artSize||style!=artStyle||coverImages.Images.Count==0){thumbnailSlots.Clear();slotOwners.Clear();nextSlot=1;coverImages.Images.Clear();coverImages.ImageSize=new Size(size,size);var imageHandle=coverImages.Handle;using(var placeholder=MakeThumbnail(null,"?",size))coverImages.Images.Add(placeholder);artSize=size;artStyle=style;foreach(ListViewItem item in games.Items)item.ImageIndex=0;}LoadVisibleArtwork();}
  public static Bitmap MakeThumbnail(string path,string title,int size){var bitmap=new Bitmap(size,size);using(var graphics=Graphics.FromImage(bitmap)){graphics.Clear(FishBowlPalette.ThemeSurface);bool loaded=false;try{if(!string.IsNullOrWhiteSpace(path)&&File.Exists(path)){using(var image=Image.FromFile(path)){if(image.Width<12000&&image.Height<12000){graphics.DrawImage(image,new Rectangle(4,4,size-8,size-8));loaded=true;}}}}catch{}if(!loaded)using(var font=new Font("Segoe UI",Math.Max(8,size/3),FontStyle.Bold))FishBowlText.DrawText(graphics,string.IsNullOrWhiteSpace(title)?"?":title.Substring(0,1).ToUpperInvariant(),font,new Rectangle(0,0,size,size),FishBowlPalette.ThemeInk,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter);CosmeticRuntime.DecorateArtwork(bitmap);}return bitmap;}
  void LoadVisibleArtwork(){if(!polishReady||!artworkView||thumbnailBusy||!games.Visible||!games.IsHandleCreated||games.Items.Count==0)return;var visible=new HashSet<ListViewItem>();for(int y=8;y<games.ClientSize.Height;y+=32)for(int x=8;x<games.ClientSize.Width;x+=32){var item=games.GetItemAt(x,y);if(item!=null)visible.Add(item);}foreach(var item in visible){var g=item.Tag as GameEntry;if(g==null)continue;long stamp=0;try{if(File.Exists(g.ArtworkPath))stamp=File.GetLastWriteTimeUtc(g.ArtworkPath).Ticks;}catch{}string key=(g.ArtworkPath??"")+"|"+g.Title+"|"+g.ConsoleLabel+"|"+stamp+"|"+artSize+"|"+artStyle;int slot;if(thumbnailSlots.TryGetValue(key,out slot)){item.ImageIndex=slot;if(!slotOwners.ContainsKey(slot))slotOwners[slot]=new HashSet<ListViewItem>();slotOwners[slot].Add(item);continue;}thumbnailBusy=true;string path=g.ArtworkPath,title=g.Title,platform=g.ConsoleLabel;bool badge=library.Cosmetics!=null&&library.Cosmetics.PlatformLabels;int size=artSize;string style=artStyle;Task.Factory.StartNew(()=>Hub.PlatformThumbnail(path,title,platform,size,badge)).ContinueWith(task=>{if(task.IsFaulted){thumbnailBusy=false;return;}var bitmap=task.Result;if(IsDisposed||Disposing||!IsHandleCreated){bitmap.Dispose();return;}try{BeginInvoke((Action)(()=>{try{if(IsDisposed||Disposing||artSize!=size||artStyle!=style)return;int use=nextSlot++;if(use>=128){nextSlot=2;use=1;}if(use<coverImages.Images.Count){foreach(var old in thumbnailSlots.Where(k=>k.Value==use).Select(k=>k.Key).ToArray())thumbnailSlots.Remove(old);HashSet<ListViewItem> previous;if(slotOwners.TryGetValue(use,out previous))foreach(var old in previous)if(old.ListView==games)old.ImageIndex=0;coverImages.Images[use]=bitmap;}else coverImages.Images.Add(bitmap);thumbnailSlots[key]=use;slotOwners[use]=new HashSet<ListViewItem>{item};if(item.ListView==games)item.ImageIndex=use;}finally{bitmap.Dispose();thumbnailBusy=false;}}));}catch(InvalidOperationException){bitmap.Dispose();thumbnailBusy=false;}});break;}}
 }
}
