using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Media;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace EmulatorHub {
 public class ImmersionSettings {
  public bool Bubbles {get;set;} public bool Roomier {get;set;} public bool Backdrops {get;set;} public bool Transitions {get;set;} public bool Sounds {get;set;}
  public bool LaunchPresentation {get;set;} public bool Recap {get;set;} public bool Ambient {get;set;}
  public int Volume {get;set;} public int IdleMinutes {get;set;} public string Preset {get;set;}
  public ImmersionSettings(){Bubbles=true;Roomier=true;Volume=20;IdleMinutes=3;Preset="Current";Transitions=true;}
 }
 public static class Immersion {
  public static ImmersionSettings Ensure(LibraryData d){var h=Hub.Ensure(d);if(h.Immersion==null)h.Immersion=new ImmersionSettings();return h.Immersion;}
  public static string ArtworkStamp(string path){try{var f=new FileInfo(path);return f.Exists?path+"|"+f.Length+"|"+f.LastWriteTimeUtc.Ticks:path??"";}catch{return path??"";}}
  public static bool Animate(LibraryData d){return Ensure(d).Transitions&&!d.Enhancements.ReducedMotion;}
  public static Bitmap ImageCopy(string path,int width,int height){try{if(!File.Exists(path)||new FileInfo(path).Length>32*1024*1024)return null;using(var image=Image.FromFile(path)){if(image.Width>12000||image.Height>12000)return null;var result=new Bitmap(width,height);using(var g=Graphics.FromImage(result)){g.Clear(FishBowlPalette.ThemeSurface);g.InterpolationMode=InterpolationMode.HighQualityBicubic;float scale=Math.Max((float)width/image.Width,(float)height/image.Height);float w=image.Width*scale,h=image.Height*scale;g.DrawImage(image,(width-w)/2,(height-h)/2,w,h);}return result;}}catch{return null;}}
  public static Bitmap Dimmed(string path,int width,int height,Color background){var image=ImageCopy(path,width,height);if(image==null)return null;using(var g=Graphics.FromImage(image))using(var b=new SolidBrush(Color.FromArgb(235,background)))g.FillRectangle(b,0,0,width,height);return image;}
  public static DateTime Date(string text){DateTime value;return DateTime.TryParse(text,out value)?value:DateTime.MinValue;}
  public static List<GameEntry> Shelf(LibraryData d,string shelf){IEnumerable<GameEntry> games=d.Games;if(shelf=="Favorites")games=games.Where(g=>g.Favorite).OrderBy(g=>g.Title);else if(shelf=="Recently added")games=games.OrderByDescending(g=>Date(g.AddedAt));else games=games.Where(g=>g.LaunchCount>0&&!string.Equals(g.PlayStatus,"Completed",StringComparison.OrdinalIgnoreCase)).OrderByDescending(g=>Date(g.LastLaunched));return games.Take(40).ToList();}
  public static void Show(IWin32Window owner,LibraryData d,GameEntry g){NextData.Ensure(d);Ensure(d);using(var f=new ImmersionWindow(d,g))f.ShowDialog(owner);}
  public static byte[] Wave(int volume,bool launch){volume=Math.Max(0,Math.Min(100,volume));const int rate=22050;int count=rate*(launch?180:65)/1000;using(var m=new MemoryStream())using(var w=new BinaryWriter(m)){w.Write(Encoding.ASCII.GetBytes("RIFF"));w.Write(36+count*2);w.Write(Encoding.ASCII.GetBytes("WAVEfmt "));w.Write(16);w.Write((short)1);w.Write((short)1);w.Write(rate);w.Write(rate*2);w.Write((short)2);w.Write((short)16);w.Write(Encoding.ASCII.GetBytes("data"));w.Write(count*2);for(int i=0;i<count;i++){double fade=Math.Sin(Math.PI*i/count);double frequency=launch?(i<count/2?440:660):520;w.Write((short)(Math.Sin(2*Math.PI*frequency*i/rate)*fade*5000*volume/100));}return m.ToArray();}}
  static readonly object soundGate=new object();static DateTime lastSound;static bool soundBusy;
  public static void Sound(LibraryData d,bool launch){var s=Ensure(d);if(!s.Sounds||s.Volume<=0)return;lock(soundGate){if(soundBusy||(!launch&&(DateTime.UtcNow-lastSound).TotalMilliseconds<150))return;soundBusy=true;lastSound=DateTime.UtcNow;}var bytes=Wave(s.Volume,launch);Task.Factory.StartNew(()=>{try{using(var stream=new MemoryStream(bytes))using(var player=new SoundPlayer(stream))player.PlaySync();}catch(Exception ex){Store.Log("Interface sound unavailable: "+ex.Message);}finally{lock(soundGate)soundBusy=false;}});}
  public static bool PreLaunch(IWin32Window owner,LibraryData d,GameEntry g){if(!Ensure(d).LaunchPresentation)return true;using(var f=new LaunchPresentation(d,g))return f.ShowDialog(owner)==DialogResult.OK;}
  public static void AfterSession(IWin32Window owner,LibraryData d,GameEntry g,PlaySession session){if(!Ensure(d).Recap||UserTools.Guest||session.Uncertain)return;var control=owner as Control;if(control==null||control.IsDisposed||!control.IsHandleCreated)return;control.BeginInvoke(new Action(()=>{if(control.IsDisposed||UserTools.ActiveLaunches>0)return;using(var f=new SessionRecap(d,g,session))f.ShowDialog(owner);}));}
  public static void ApplyPreset(LibraryData d,string preset){if(preset=="Current")return;if(!new[]{"Arcade","Minimal","Retro"}.Contains(preset))throw new ArgumentException("Unknown immersion preset.");if(d.Cosmetics==null)d.Cosmetics=new CosmeticSettings();var c=d.Cosmetics;c.CustomPalette=true;c.TextColor="#F4F5F7";c.MutedColor="#CBD2DC";c.SelectionColor="";c.FocusColor="";c.ArtworkFrame=preset=="Minimal"?"None":"Rounded";c.LibrarySpacing=preset=="Minimal"?"Compact":"Comfortable";
   if(preset=="Arcade"){c.TopColor="#20112C";c.BottomColor="#110D19";c.SurfaceColor="#2B2038";c.AccentColor="#DA9CFA";c.SecondaryColor="#9BCDF8";c.BackgroundStyle="Gradient";}
   else if(preset=="Retro"){c.TopColor="#29251D";c.BottomColor="#15140F";c.SurfaceColor="#353129";c.AccentColor="#E7C67F";c.SecondaryColor="#AFCEAA";c.BackgroundStyle="Dots";}
   else if(preset=="Minimal"){c.TopColor="#20242B";c.BottomColor="#14171C";c.SurfaceColor="#292F37";c.AccentColor="#B9D6ED";c.SecondaryColor="#C5CDD9";c.BackgroundStyle="Plain";}
   else throw new ArgumentException("Unknown immersion preset.");
  }
 }
 public class FadingCover : PictureBox {
  public float Blend=1;
  protected override void OnPaint(PaintEventArgs e){if(Image==null)return;float scale=Math.Min((float)ClientSize.Width/Image.Width,(float)ClientSize.Height/Image.Height);int width=(int)(Image.Width*scale),height=(int)(Image.Height*scale);using(var attrs=new ImageAttributes()){var matrix=new ColorMatrix();matrix.Matrix33=Math.Max(0,Math.Min(1,Blend));attrs.SetColorMatrix(matrix);e.Graphics.DrawImage(Image,new Rectangle((ClientSize.Width-width)/2,(ClientSize.Height-height)/2,width,height),0,0,Image.Width,Image.Height,GraphicsUnit.Pixel,attrs);}}
 }
 public class FocusSurface : Panel {
  readonly LibraryData data;Bitmap backdrop;string stamp;float blend=1;readonly Timer fade;
  public readonly PictureBox Cover;public readonly Label Title;public readonly TextBox Description;
  public FocusSurface(LibraryData d){data=d;DoubleBuffered=true;Dock=DockStyle.Fill;Padding=new Padding(22);BackColor=FishBowlPalette.ThemeSurface;
   Cover=new FadingCover{Dock=DockStyle.Left,Width=210,SizeMode=PictureBoxSizeMode.Zoom,BackColor=FishBowlPalette.ThemeSurface,AccessibleName="Game cover"};
   Title=new Label{Dock=DockStyle.Top,AutoSize=false,Height=Math.Max(65,Font.Height*3),ForeColor=FishBowlPalette.ThemeInk,BackColor=FishBowlPalette.ThemeSurface,Padding=new Padding(12)};
   Description=new TextBox{Dock=DockStyle.Fill,ReadOnly=true,TabStop=false,Multiline=true,ScrollBars=ScrollBars.Vertical,BorderStyle=BorderStyle.None,BackColor=FishBowlPalette.ThemeSurface,ForeColor=FishBowlPalette.ThemeInk,AccessibleName="Focused game description"};var right=new Panel{Dock=DockStyle.Fill,Padding=new Padding(20)};right.Controls.Add(Description);right.Controls.Add(Title);Controls.Add(right);Controls.Add(Cover);
   fade=new Timer{Interval=30};fade.Tick+=(a,b)=>{blend=Math.Min(1,blend+0.12f);((FadingCover)Cover).Blend=blend;Cover.Invalidate();Invalidate();if(blend>=1)fade.Stop();};
  }
  public void SelectGame(GameEntry game){fade.Stop();if(Cover.Image!=null){var old=Cover.Image;Cover.Image=null;old.Dispose();}Title.Text=game==null?"Choose a game":game.Title;Description.Text=game==null?"Add games to your Library to start.":game.ConsoleLabel+"  •  "+game.Genre+"\r\n\r\n"+(game.Description??"")+"\r\n\r\n"+(game.Notes??"");if(game!=null)Cover.Image=Immersion.ImageCopy(game.ArtworkPath,210,280);string next=game==null?"":game.Id+"|"+Immersion.ArtworkStamp(game.ArtworkPath)+"|"+Immersion.Ensure(data).Backdrops;if(next!=stamp){stamp=next;if(backdrop!=null)backdrop.Dispose();backdrop=game!=null&&Immersion.Ensure(data).Backdrops?Immersion.Dimmed(game.ArtworkPath,960,540,BackColor):null;}blend=Immersion.Animate(data)?0:1;((FadingCover)Cover).Blend=blend;Cover.Invalidate();Description.Select(0,0);if(blend<1)fade.Start();Invalidate();}
  protected override void OnPaintBackground(PaintEventArgs e){base.OnPaintBackground(e);if(backdrop!=null)e.Graphics.DrawImage(backdrop,ClientRectangle);if(blend<1)using(var brush=new SolidBrush(Color.FromArgb((int)((1-blend)*255),BackColor)))e.Graphics.FillRectangle(brush,ClientRectangle);}
  protected override void Dispose(bool disposing){if(disposing){fade.Dispose();if(backdrop!=null)backdrop.Dispose();if(Cover.Image!=null){Cover.Image.Dispose();Cover.Image=null;}}base.Dispose(disposing);}
 }
 public class LaunchPresentation : NextDialog {
  readonly Timer timer;int steps;
  public LaunchPresentation(LibraryData d,GameEntry g):base("Preparing "+g.Title,760,460){var surface=new FocusSurface(d);surface.SelectGame(g);Body.Controls.Add(surface);var status=new Label{Dock=DockStyle.Bottom,Height=50,Text="Configuration validated. Preparing to start the selected program.",ForeColor=FishBowlPalette.ThemeInk};Body.Controls.Add(status);Action("Cancel launch",()=>{DialogResult=DialogResult.Cancel;Close();});KeyPreview=true;KeyDown+=(a,b)=>{if(b.KeyCode==Keys.Escape){DialogResult=DialogResult.Cancel;Close();}};timer=new Timer{Interval=Immersion.Animate(d)?250:100};timer.Tick+=(a,b)=>{steps++;if(steps>=3){timer.Stop();DialogResult=DialogResult.OK;Close();}};Shown+=(a,b)=>timer.Start();FormClosed+=(a,b)=>timer.Stop();}
  protected override void Dispose(bool disposing){if(disposing)timer.Dispose();base.Dispose(disposing);}
 }
 public class SessionRecap : NextDialog {
  public readonly TextBox Note;public readonly NumericUpDown Rating;
  public SessionRecap(LibraryData d,GameEntry g,PlaySession s):base("Session recap — "+g.Title,760,540){var table=Fields(Body);Field(table,"Recorded session",new Label{Text=TimeSpan.FromSeconds(Math.Max(0,s.Seconds)).ToString()+" (launched process)",TextAlign=ContentAlignment.MiddleLeft},65);Note=new TextBox{Multiline=true,ScrollBars=ScrollBars.Vertical,MaxLength=2000};Field(table,"Session note (optional)",Note,130);Rating=Number(g.PersonalRating,0,5);Field(table,"Personal rating (0 = unset)",Rating);Action("Save note / rating",()=>{Save(d,g,s,Note.Text,(int)Rating.Value);Close();});Action("Dismiss",Close);}
  public static void Save(LibraryData d,GameEntry g,PlaySession session,string note,int rating){if(UserTools.Guest)return;note=(note??"").Trim();if(note.Length>2000)throw new ArgumentException("Session notes must be at most 2000 characters.");g.PersonalRating=Math.Max(0,Math.Min(5,rating));if(note.Length>0){session.Note=string.IsNullOrWhiteSpace(session.Note)?note:session.Note+"\r\n"+note;g.Notes=(g.Notes??"").TrimEnd()+"\r\n["+DateTime.Now.ToString("g")+"] "+note;}Store.Save(d);}
 }
 public class ScreenshotGallery : NextDialog {
  readonly LibraryData data;readonly GameEntry game;readonly ListBox list;readonly PictureBox image;
  public ScreenshotGallery(LibraryData d,GameEntry g):base("Screenshot gallery",960,700){data=d;game=g;image=new PictureBox{Dock=DockStyle.Fill,SizeMode=PictureBoxSizeMode.Zoom,BackColor=FishBowlPalette.ThemeSurface,AccessibleName="Selected screenshot"};list=new ListBox{Dock=DockStyle.Left,Width=240,DisplayMember="Path",HorizontalScrollbar=true,AccessibleName="Screenshots for selected game"};Body.Controls.Add(image);Body.Controls.Add(list);list.SelectedIndexChanged+=(a,b)=>LoadSelection();Action("Manage / add screenshots",()=>{NextMedia.Screenshots(this,d,g);Reload();});Action("Previous",()=>{if(list.Items.Count>0)list.SelectedIndex=(list.SelectedIndex+list.Items.Count-1)%list.Items.Count;});Action("Next",()=>{if(list.Items.Count>0)list.SelectedIndex=(list.SelectedIndex+1)%list.Items.Count;});Action("Close",Close);Reload();}
  public void Reload(){list.DataSource=(data.GameScreenshots??new List<GameScreenshot>()).Where(s=>game==null||s.GameId==game.Id).OrderBy(s=>s.AddedAt).ToList();LoadSelection();}
  void LoadSelection(){var old=image.Image;image.Image=null;if(old!=null)old.Dispose();var shot=list.SelectedItem as GameScreenshot;if(shot!=null){try{if(File.Exists(shot.Path)&&new FileInfo(shot.Path).Length<=32*1024*1024)using(var source=Image.FromFile(shot.Path))if(source.Width<=12000&&source.Height<=12000){float scale=Math.Min(1,Math.Min(1600f/source.Width,1000f/source.Height));image.Image=new Bitmap(source,Math.Max(1,(int)(source.Width*scale)),Math.Max(1,(int)(source.Height*scale)));}}catch{}}Text=shot==null?"Screenshot gallery — no captures linked":"Screenshot gallery — "+Path.GetFileName(shot.Path);}
  protected override void Dispose(bool disposing){if(disposing&&image.Image!=null){image.Image.Dispose();image.Image=null;}base.Dispose(disposing);}
 }
 public class ImmersionWindow : NextDialog {
  readonly LibraryData data;readonly ListBox games;readonly FocusSurface surface;readonly ComboBox shelf;readonly TextBox search;
  public ImmersionWindow(LibraryData d,GameEntry selected):base("Immersion",1080,730){data=d;Immersion.Ensure(d);var top=new TableLayoutPanel{Dock=DockStyle.Top,Height=55,ColumnCount=2};top.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,40));top.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,60));shelf=Choice(new[]{"All games","Continue playing","Recently added","Favorites"},"All games");shelf.Dock=DockStyle.Fill;shelf.AccessibleName="Personal shelf";search=new TextBox{Dock=DockStyle.Fill,AccessibleName="Search immersive Library"};top.Controls.Add(shelf,0,0);top.Controls.Add(search,1,0);games=new ListBox{Dock=DockStyle.Left,Width=260,DisplayMember="Title",AccessibleName="Games on selected shelf"};surface=new FocusSurface(d);Body.Controls.Add(surface);Body.Controls.Add(games);Body.Controls.Add(top);shelf.SelectedIndexChanged+=(a,b)=>Reload(null);search.TextChanged+=(a,b)=>Reload(null);games.SelectedIndexChanged+=(a,b)=>{surface.SelectGame(games.SelectedItem as GameEntry);Immersion.Sound(d,false);};
   Action("Focus / shelves",()=>{games.Visible=!games.Visible;top.Visible=games.Visible;});Action("Play",()=>{var g=Selected();if(g!=null)ExperienceTools.Launch(this,d,g);});Action("Screenshots",()=>{using(var f=new ScreenshotGallery(d,Selected()))f.ShowDialog(this);});Action("Details",()=>{var g=Selected();if(g!=null){using(var f=new GameExperienceDialog(d,g))f.ShowDialog(this);Reload(g.Id);}});Action("Ambient preview",()=>{using(var f=new AmbientWindow(d))f.ShowDialog(this);});Action("Immersion settings",()=>{using(var f=new ImmersionSettingsDialog(d))f.ShowDialog(this);Reload(Selected()==null?null:Selected().Id);});Action("Close",Close);Reload(selected==null?null:selected.Id);if(selected!=null){games.Visible=false;top.Visible=false;}
  }
  GameEntry Selected(){return games.SelectedItem as GameEntry;}
  public void Reload(string selected){var source=shelf.Text=="All games"?data.Games.OrderBy(g=>g.Title).ToList():Immersion.Shelf(data,shelf.Text);games.DataSource=source.Where(g=>Hub.SearchText(g).IndexOf(search.Text.Trim(),StringComparison.OrdinalIgnoreCase)>=0).ToList();if(selected!=null)for(int i=0;i<games.Items.Count;i++)if(((GameEntry)games.Items[i]).Id==selected){games.SelectedIndex=i;break;}surface.SelectGame(Selected());}
 }
 public class ImmersionSettingsDialog : NextDialog {
  readonly LibraryData data;readonly Dictionary<string,CheckBox> checks=new Dictionary<string,CheckBox>();readonly NumericUpDown volume,idle;readonly ComboBox preset;
  public ImmersionSettingsDialog(LibraryData d):base("Immersion settings",840,730){data=d;var s=Immersion.Ensure(d);var table=Fields(Body);foreach(var pair in new[]{new[]{"Bubbles","Theme bubbles along the workspace sides"},new[]{"Roomier","Roomier Home cards and Library rows"},new[]{"Backdrops","Dim selected-game backgrounds"},new[]{"Transitions","Gentle tab highlights and artwork fades (honors reduced motion)"},new[]{"Sounds","Interface selection and launch sounds"},new[]{"LaunchPresentation","Brief launch artwork with cancel before starting"},new[]{"Recap","Offer session recap after tracked process closes"},new[]{"Ambient","Artwork slideshow after idle time"}}){var c=new CheckBox{Checked=(bool)typeof(ImmersionSettings).GetProperty(pair[0]).GetValue(s,null)};checks[pair[0]]=c;Field(table,pair[1],c,Math.Max(48,Font.Height*3));}volume=Number(s.Volume,0,100);Field(table,"Interface volume (%)",volume);idle=Number(s.IdleMinutes,1,60);Field(table,"Idle minutes",idle);preset=Choice(new[]{"Current","Arcade","Minimal","Retro"},"Current");Field(table,"Apply a coordinated cosmetic preset",preset);Field(table,"Backgrounds are local artwork. Sounds and ambient mode start off.",new Label{Text="Preset replaces palette, spacing and background style when applied.",AutoSize=true},75);Action("Test sound",()=>{var preview=new LibraryData();Hub.Ensure(preview).Immersion=new ImmersionSettings{Sounds=true,Volume=(int)volume.Value};Immersion.Sound(preview,false);});Action("Apply",Apply);Action("Cancel",Close);}
  public void Apply(){var s=new ImmersionSettings{Volume=(int)volume.Value,IdleMinutes=(int)idle.Value,Preset=preset.Text};foreach(var c in checks)typeof(ImmersionSettings).GetProperty(c.Key).SetValue(s,c.Value.Checked,null);Immersion.ApplyPreset(data,preset.Text);Hub.Ensure(data).Immersion=s;FluidStyle.Configure(data);Store.Save(data);foreach(var main in Application.OpenForms.OfType<MainForm>().ToArray())main.RefreshUserToolsViews(data);foreach(var lib in Application.OpenForms.OfType<GameLibraryDialog>().ToArray())lib.ReloadLibrary();DialogResult=DialogResult.OK;Close();}
 }
 public class IdleInput : IMessageFilter,IDisposable {
  public DateTime Last=DateTime.UtcNow;Point position=Cursor.Position;
  public IdleInput(){Application.AddMessageFilter(this);}
  public bool PreFilterMessage(ref Message m){if((m.Msg>=0x100&&m.Msg<=0x109)||(m.Msg>=0x201&&m.Msg<=0x20E)){Last=DateTime.UtcNow;}else if(m.Msg==0x200&&Cursor.Position!=position){position=Cursor.Position;Last=DateTime.UtcNow;}return false;}
  public void Dispose(){Application.RemoveMessageFilter(this);}
 }
 public class AmbientWindow : NextDialog,IMessageFilter {
  readonly List<GameEntry> games;readonly PictureBox artwork;readonly Label caption;readonly Timer timer;int index;Point origin;bool closing;
  public AmbientWindow(LibraryData d):base("Ambient artwork — move, click or press a key to exit",1100,740){FormBorderStyle=FormBorderStyle.None;WindowState=FormWindowState.Maximized;KeyPreview=true;games=d.Games.Where(g=>File.Exists(g.ArtworkPath)).OrderBy(g=>g.Title).Take(200).ToList();artwork=new PictureBox{Dock=DockStyle.Fill,SizeMode=PictureBoxSizeMode.Zoom,BackColor=FishBowlPalette.ThemeSurface,AccessibleName="Ambient game artwork"};caption=new Label{Dock=DockStyle.Bottom,Height=65,TextAlign=ContentAlignment.MiddleCenter,ForeColor=FishBowlPalette.ThemeInk,BackColor=FishBowlPalette.ThemeSurface};Body.Controls.Add(artwork);Body.Controls.Add(caption);Action("Exit ambient mode",Close);KeyDown+=(a,b)=>{b.SuppressKeyPress=true;Close();};origin=Cursor.Position;Application.AddMessageFilter(this);timer=new Timer{Interval=12000};timer.Tick+=(a,b)=>Advance();Shown+=(a,b)=>{origin=Cursor.Position;caption.Height=Math.Max(65,caption.Font.Height*3);Advance();timer.Start();};FormClosed+=(a,b)=>timer.Stop();}
  public bool PreFilterMessage(ref Message m){if(!IsHandleCreated||closing||!Visible)return false;var target=Control.FromHandle(m.HWnd);if(target==null||target.FindForm()!=this)return false;bool input=(m.Msg>=0x100&&m.Msg<=0x109)||(m.Msg>=0x201&&m.Msg<=0x20E)||(m.Msg==0x200&&Math.Abs(Cursor.Position.X-origin.X)+Math.Abs(Cursor.Position.Y-origin.Y)>5);if(input){closing=true;BeginInvoke(new Action(Close));return true;}return false;}
  public void Advance(){var old=artwork.Image;artwork.Image=null;if(old!=null)old.Dispose();if(games.Count==0){caption.Text="No game artwork linked. Move, click or press a key to exit.";return;}var game=games[index++%games.Count];var image=Immersion.ImageCopy(game.ArtworkPath,1920,1080);if(image!=null)using(var g=Graphics.FromImage(image))using(var brush=new SolidBrush(Color.FromArgb(75,Color.Black)))g.FillRectangle(brush,0,0,image.Width,image.Height);artwork.Image=image;caption.Text=game.Title+"  •  "+game.ConsoleLabel;}
  protected override void Dispose(bool disposing){if(disposing){timer.Dispose();Application.RemoveMessageFilter(this);if(artwork.Image!=null){artwork.Image.Dispose();artwork.Image=null;}}base.Dispose(disposing);}
 }
 public partial class MainForm {
  IdleInput immersionInput;Timer immersionIdle;
  void StartImmersionRuntime(){immersionInput=new IdleInput();immersionIdle=new Timer{Interval=1000};immersionIdle.Tick+=(a,b)=>{var s=Immersion.Ensure(library);if(EligibleForAmbient(s,(DateTime.UtcNow-immersionInput.Last).TotalMinutes,Form.ActiveForm==this,UserTools.ActiveLaunches,WorkGate.Busy)){immersionInput.Last=DateTime.UtcNow;try{using(var f=new AmbientWindow(library))f.ShowDialog(this);}finally{immersionInput.Last=DateTime.UtcNow;}}};immersionIdle.Start();Disposed+=(a,b)=>{immersionIdle.Dispose();immersionInput.Dispose();};}
  public static bool EligibleForAmbient(ImmersionSettings s,double minutes,bool focused,int sessions,int work){return s.Ambient&&focused&&sessions==0&&work==0&&minutes>=Math.Max(1,Math.Min(60,s.IdleMinutes));}
 }
 public partial class GameLibraryDialog {
  Bitmap immersionBackdrop;string immersionStamp;
  void RefreshImmersionBackdrop(){var selected=SelectedGame();var s=Immersion.Ensure(library);string stamp=s.Backdrops&&selected!=null?selected.Id+"|"+Immersion.ArtworkStamp(selected.ArtworkPath)+"|"+FishBowlPalette.ThemeSurface.ToArgb():"";if(stamp==immersionStamp)return;immersionStamp=stamp;games.BackgroundImage=null;if(immersionBackdrop!=null){immersionBackdrop.Dispose();immersionBackdrop=null;}if(stamp.Length>0)immersionBackdrop=Immersion.Dimmed(selected.ArtworkPath,960,540,games.BackColor);games.BackgroundImage=immersionBackdrop;}
  void StartImmersionLibrary(){games.SelectedIndexChanged+=(a,b)=>{RefreshImmersionBackdrop();if(Focused||ContainsFocus)Immersion.Sound(library,false);};Disposed+=(a,b)=>{games.BackgroundImage=null;if(immersionBackdrop!=null)immersionBackdrop.Dispose();};}
 }
}
