using System; using System.Collections.Generic; using System.Drawing; using System.IO; using System.Linq; using System.Text; using System.Threading; using System.Windows.Forms;
namespace EmulatorHub {
 public static class WindowsGameTools {
  static void Run(IWin32Window owner, Action work) { try { work(); } catch(Exception e) { MessageBox.Show(owner, e.Message, "Game tools", MessageBoxButtons.OK, MessageBoxIcon.Information); } }
  static GameToolsSettings Settings(GameEntry game) { if(game.Tools == null) game.Tools = new GameToolsSettings(); if(game.Tools.ModProfiles == null) game.Tools.ModProfiles = new List<ModProfile>(); if(game.Tools.MediaLinks == null) game.Tools.MediaLinks = new List<GameMediaLink>(); return game.Tools; }
  public static void Open(IWin32Window owner, LibraryData library, GameEntry game, Action refresh) {
   if(game == null) { MessageBox.Show(owner, "Select a game first.", "Game tools"); return; } NextData.Ensure(library); Settings(game);
   using(NextDialog dialog = new NextDialog("Game tools — " + game.Title, 850, 560)) {
    TableLayoutPanel fields = NextDialog.Fields(dialog.Body);
    NextDialog.Field(fields, "Game", new Label { Text = game.Title, TextAlign=ContentAlignment.MiddleLeft });
    NextDialog.Field(fields, "Setup and profiles", ExperienceUi.Button("Game setup", delegate { Setup(dialog, library, game, refresh); }));
    NextDialog.Field(fields, "Mods and patches", ExperienceUi.Button("Mod profiles", delegate { Mods(dialog, library, game); }));
    NextDialog.Field(fields, "Screenshots, manuals and videos", ExperienceUi.Button("Media library", delegate { Media(dialog, library, game); }));
    NextDialog.Field(fields, "Save history and device transfer", ExperienceUi.Button("Save timeline and transfer", delegate { Saves(dialog, library, game); }));
    NextDialog.Field(fields, "Session notes and play history", ExperienceUi.Button("Play history", delegate { Analytics(dialog, library, game); }));
    dialog.Action("Close", dialog.Close); dialog.ShowDialog(owner);
   }
  }
  static void Setup(IWin32Window owner, LibraryData library, GameEntry game, Action refresh) {
   using(NextDialog d = new NextDialog("Game setup", 850, 680)) {
    TableLayoutPanel table = NextDialog.Fields(d.Body);
    List<EmulatorProfile> emulators = library.Emulators ?? new List<EmulatorProfile>();
    ComboBox emulator = NextDialog.Choice(new[]{"Default"}.Concat(emulators.Select(x=> x.Name + " [" + x.Id + "]")), "Default");
    int selected = emulators.FindIndex(x=> x.Id == (game.PreferredEmulatorId ?? game.EmulatorId)); emulator.SelectedIndex = selected + 1;
    ComboBox build = NextDialog.Choice(new[]{"Default"}, "Default"); ComboBox profile = NextDialog.Choice(new[]{"Default"}, "Default");
    Action update = delegate { EmulatorProfile emu = emulator.SelectedIndex > 0 ? emulators[emulator.SelectedIndex-1] : null; build.Items.Clear(); build.Items.Add("Default"); profile.Items.Clear(); profile.Items.Add("Default"); if(emu != null) { foreach(EmulatorBuild b in emu.Builds ?? new List<EmulatorBuild>()) build.Items.Add(b.Label + " [" + b.Id + "]"); foreach(LaunchProfile p in emu.LaunchProfiles ?? new List<LaunchProfile>()) profile.Items.Add(p.Name); int bi=(emu.Builds ?? new List<EmulatorBuild>()).FindIndex(x=>x.Id==game.PreferredBuildId); build.SelectedIndex=bi+1; } if(build.SelectedIndex<0)build.SelectedIndex=0; profile.SelectedItem=game.LaunchProfileName; if(profile.SelectedIndex<0)profile.SelectedIndex=0; };
    emulator.SelectedIndexChanged += delegate { update(); }; update();
    List<ControllerProfile> controllers = library.ControllerProfiles ?? new List<ControllerProfile>(); ComboBox controller=NextDialog.Choice(new[]{"Default"}.Concat(controllers.Select(x=>x.Name + " [" + x.Id + "]")), "Default");controller.SelectedIndex=controllers.FindIndex(x=>x.Id==game.ControllerProfileId)+1;
    TextBox args = new TextBox { Text=game.Arguments }; TextBox work = new TextBox { Text=game.Extras == null ? "" : game.Extras.WorkingDirectory }; TextBox core = new TextBox { Text=game.EmulatorCore }; TextBox notes = new TextBox { Text=game.CompatibilityNotes, Multiline=true };
    NextDialog.Field(table,"Preferred emulator",emulator); NextDialog.Field(table,"Preferred build",build); NextDialog.Field(table,"Launch profile",profile); NextDialog.Field(table,"Controller profile",controller); NextDialog.Field(table,"Core",core); NextDialog.Field(table,"Launch arguments",args); NextDialog.Field(table,"Working folder (PC games)",work); NextDialog.Field(table,"Setup notes",notes,100);
    d.Action("Save",delegate { Run(d,delegate { if(!string.IsNullOrWhiteSpace(work.Text)&& !Directory.Exists(work.Text))throw new IOException("The working folder does not exist."); EmulatorProfile emu=emulator.SelectedIndex>0?emulators[emulator.SelectedIndex-1]:null; game.PreferredEmulatorId=emu==null?null:emu.Id; game.PreferredBuildId=emu!=null&&build.SelectedIndex>0?emu.Builds[build.SelectedIndex-1].Id:null; game.LaunchProfileName=profile.SelectedIndex>0?profile.Text:null; game.ControllerProfileId=controller.SelectedIndex>0?controllers[controller.SelectedIndex-1].Id:null; game.Arguments=args.Text;game.EmulatorCore=core.Text;game.CompatibilityNotes=notes.Text;if(game.Extras==null)game.Extras=new GameExtras();game.Extras.WorkingDirectory=work.Text;if(emu!=null)game.RequiresEmulatorAssignment=false;Store.Save(library);refresh();d.Close(); }); });d.Action("Cancel",d.Close);d.ShowDialog(owner);
   }
  }
  static string Folder(IWin32Window owner, string description) { using(FolderBrowserDialog f=new FolderBrowserDialog { Description=description }) return f.ShowDialog(owner)==DialogResult.OK?f.SelectedPath:null; }
  static bool Review(IWin32Window owner,string title,string text) { using(NextDialog d=new NextDialog(title,850,580)) { d.Body.Controls.Add(new TextBox { Text=text,ReadOnly=true,Multiline=true,ScrollBars=ScrollBars.Both,Dock=DockStyle.Fill });bool accepted=false;d.Action("Apply reviewed changes",delegate { accepted=true;d.Close(); });d.Action("Cancel",d.Close);d.ShowDialog(owner);return accepted; } }
  static void Mods(IWin32Window owner,LibraryData library,GameEntry game) {
   using(NextDialog d=new NextDialog("Mod and patch profiles",880,580)) {
    ListBox list=new ListBox { Dock=DockStyle.Fill };d.Body.Controls.Add(list);Action reload=delegate { list.DataSource=null;list.DataSource=Settings(game).ModProfiles.ToList(); };reload();
    d.Action("Create IPS patched copy",delegate { Run(d,delegate { using(OpenFileDialog original=new OpenFileDialog { Title="Select original game file",Filter="All files|*.*" }) using(OpenFileDialog patch=new OpenFileDialog { Title="Select IPS patch",Filter="IPS patch|*.ips" }) using(SaveFileDialog output=new SaveFileDialog { Title="Create a new patched game copy",Filter="All files|*.*" }) { if(original.ShowDialog(d)!=DialogResult.OK||patch.ShowDialog(d)!=DialogResult.OK)return;output.FileName=Path.GetFileNameWithoutExtension(original.FileName)+"-patched"+Path.GetExtension(original.FileName);if(output.ShowDialog(d)!=DialogResult.OK)return;if(!Review(d,"Review patched copy","Original preserved: "+original.FileName+"\r\nIPS patch: "+patch.FileName+"\r\nNew file: "+output.FileName))return;GameTools.CreateIpsPatchedCopy(original.FileName,patch.FileName,output.FileName);MessageBox.Show(d,"Patched copy created. Add it to the library when ready.","IPS patch"); } }); });
    d.Action("Add profile",delegate { Run(d,delegate { string source=Folder(d,"Select the mod or already-patched files");if(source==null)return;string target=Folder(d,"Select the game folder to receive those files");if(target==null)return;GameTools.PreviewMod(source,target);Settings(game).ModProfiles.Add(new ModProfile { Id=Guid.NewGuid().ToString("N"),Name=Path.GetFileName(source),SourceFolder=source,DestinationFolder=target });Store.Save(library);reload(); }); });
    d.Action("Review and apply",delegate { Run(d,delegate { ModProfile p=list.SelectedItem as ModProfile;if(p==null)throw new IOException("Select a profile.");List<ModFileRecord> files=GameTools.PreviewMod(p.SourceFolder,p.DestinationFolder);string text="Destination: "+p.DestinationFolder+"\r\nExisting files are backed up before replacement. Close the game before continuing.\r\n\r\n"+string.Join("\r\n",files.Select(x=>(x.Existed?"REPLACE ":"ADD ")+x.RelativePath));if(!Review(d,"Review mod files",text))return;RequireClosed(library,game);try { GameTools.ApplyMod(p,files,Path.Combine(Store.DataDirectory,"ModBackups"),delegate { Store.Save(library); }); } finally { Store.Save(library);reload(); } }); });
    d.Action("Review and roll back",delegate { Run(d,delegate { ModProfile p=list.SelectedItem as ModProfile;if(p==null)throw new IOException("Select a profile.");GameTools.ValidateRollback(p);if(!Review(d,"Review rollback","Destination: "+p.DestinationFolder+"\r\n\r\n"+string.Join("\r\n",p.Files.Select(x=>(x.Existed?"RESTORE ":"REMOVE ADDED FILE ")+x.RelativePath))))return;RequireClosed(library,game);try { GameTools.RollbackMod(p,delegate { Store.Save(library); }); } finally { Store.Save(library);reload(); } }); });
    d.Action("Remove profile",delegate { Run(d,delegate { ModProfile p=list.SelectedItem as ModProfile;if(p==null)return;if(p.Applied)throw new IOException("Roll back the profile before removing it.");Settings(game).ModProfiles.Remove(p);Store.Save(library);reload(); }); });d.Action("Close",d.Close);d.ShowDialog(owner);
   }
  }
  static void RequireClosed(LibraryData library, GameEntry game) { SaveHistory.RequireClosed(library,new SaveSnapshot { GameId=game.Id }); }
  static void Media(IWin32Window owner,LibraryData library,GameEntry game) {
   using(NextDialog d=new NextDialog("Game media library",850,570)) {
    ListBox list=new ListBox { Dock=DockStyle.Fill,DisplayMember="Label" }; d.Body.Controls.Add(list); Action reload=delegate { list.DataSource=null;list.DataSource=Settings(game).MediaLinks.ToList(); };reload();
    d.Action("Screenshots",delegate { NextMedia.Screenshots(d,library,game); });
    d.Action("Add manual or video",delegate { Run(d,delegate { using(OpenFileDialog f=new OpenFileDialog { Filter="Manuals and videos|*.pdf;*.txt;*.html;*.mp4;*.mkv;*.webm;*.avi|All files|*.*" }) { if(f.ShowDialog(d)!=DialogResult.OK)return;Settings(game).MediaLinks.Add(new GameMediaLink { Label=Path.GetFileName(f.FileName),Path=f.FileName,Kind="Local media" });Store.Save(library);reload(); } }); });
    d.Action("Open selected",delegate { Run(d,delegate { GameMediaLink item=list.SelectedItem as GameMediaLink;if(item==null)return;if(!File.Exists(item.Path))throw new IOException("This media file is missing.");System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(item.Path) { UseShellExecute=true }); }); });
    d.Action("Open game manual",delegate { Run(d,delegate { if(!File.Exists(game.ManualPath))throw new IOException("Set the game manual in Edit game first.");System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(game.ManualPath) { UseShellExecute=true }); }); });
    d.Action("Open trailer",delegate { Run(d,delegate { Uri uri;if(game.Extras==null||!Uri.TryCreate(game.Extras.TrailerUrl,UriKind.Absolute,out uri)||(uri.Scheme!="https"&&uri.Scheme!="http"))throw new IOException("Set an HTTP or HTTPS trailer in Game extras first.");System.Diagnostics.Process.Start(uri.AbsoluteUri); }); });
    d.Action("Remove selected link",delegate { GameMediaLink item=list.SelectedItem as GameMediaLink;if(item==null)return;Settings(game).MediaLinks.Remove(item);Store.Save(library);reload(); });d.Action("Close",d.Close);d.ShowDialog(owner);
   }
  }
  static void Saves(IWin32Window owner,LibraryData library,GameEntry game) {
   using(NextDialog d=new NextDialog("Save timeline and device transfer",850,570)) {
    ListBox list=new ListBox { Dock=DockStyle.Fill };d.Body.Controls.Add(list);Action reload=delegate { list.Items.Clear();foreach(SaveSnapshot s in (library.SaveSnapshots??new List<SaveSnapshot>()).Where(x=>x.GameId==game.Id).OrderByDescending(x=>x.CreatedAt))list.Items.Add(new SnapshotItem { Snapshot=s }); };reload();
    d.Action("Save history",delegate { using(SaveHistoryDialog h=new SaveHistoryDialog(library,game))h.ShowDialog(d);reload(); });
    d.Action("Changed files",delegate { NextTools.Timeline(d,library); });
    d.Action("Restore comparison",delegate { Run(d,delegate { SnapshotItem item=list.SelectedItem as SnapshotItem;if(item==null)throw new IOException("Select a snapshot.");UserTools.Report(d,"Restore comparison",Hub.RestorePreview(item.Snapshot,CancellationToken.None)); }); });
    d.Action("Export save bundle",delegate { Run(d,delegate { SnapshotItem item=list.SelectedItem as SnapshotItem;if(item==null)throw new IOException("Select a snapshot.");using(SaveFileDialog f=new SaveFileDialog { Filter="Save bundle|*.zip",FileName="FishBowl-save.zip" }) { if(f.ShowDialog(d)==DialogResult.OK)SaveHistory.Export(library,item.Snapshot,f.FileName,CancellationToken.None); } }); });
    d.Action("Import save bundle",delegate { Run(d,delegate { using(OpenFileDialog f=new OpenFileDialog { Filter="Save bundle|*.zip" }) { if(f.ShowDialog(d)!=DialogResult.OK)return;SaveHistory.Import(library,game,f.FileName,CancellationToken.None);Store.Save(library);reload(); } }); });d.Action("Close",d.Close);d.ShowDialog(owner);
   }
  }
  class SnapshotItem { public SaveSnapshot Snapshot;public override string ToString() { return Snapshot.CreatedAt+" — "+Snapshot.Kind+" — "+Snapshot.Bytes+" bytes"; } }
  public static void OpenLibrary(IWin32Window owner,LibraryData library,Action refresh) {
   using(NextDialog d=new NextDialog("PC games and library insights",850,560)) {TableLayoutPanel fields=NextDialog.Fields(d.Body);
    NextDialog.Field(fields,"PC games and shortcuts",ExperienceUi.Button("Add PC games",delegate { NativeFiles(d,library,refresh,null); }));NextDialog.Field(fields,"Installed Steam library",ExperienceUi.Button("Review Steam games",delegate { Steam(d,library,refresh); }));NextDialog.Field(fields,"Monthly play insights",ExperienceUi.Button("Play history",delegate { Analytics(d,library,null); }));d.Action("Close",d.Close);d.ShowDialog(owner);
   }
  }
  static void NativeFiles(IWin32Window owner,LibraryData library,Action refresh,InstalledSteamGame steam) {
   Run(owner,delegate { using(OpenFileDialog f=new OpenFileDialog { Filter="PC games and shortcuts|*.exe;*.lnk",Multiselect=steam==null,InitialDirectory=steam==null?"":steam.Folder }) { if(f.ShowDialog(owner)!=DialogResult.OK)return;List<GameEntry> entries=f.FileNames.Select(x=>GameTools.NativeEntry(x,steam==null?null:steam.Title)).Where(x=>!library.Games.Any(g=>string.Equals(g.Path,x.Path,StringComparison.OrdinalIgnoreCase))).ToList();if(entries.Count==0)throw new IOException("These entries are already in the library.");if(!Hub.PreviewImport(owner,library,entries))return;library.Games.AddRange(entries);Store.Save(library);refresh(); } });
  }
  static void Steam(IWin32Window owner,LibraryData library,Action refresh) {
   Run(owner,delegate { string folder=Folder(owner,"Select a Steam library folder containing steamapps");if(folder==null)return;List<InstalledSteamGame> games=GameTools.SteamGames(folder);if(library.GameTools==null)library.GameTools=new GameToolsLibrarySettings();if(library.GameTools.SteamLibraryFolders==null)library.GameTools.SteamLibraryFolders=new List<string>();if(!library.GameTools.SteamLibraryFolders.Any(x=>string.Equals(x,folder,StringComparison.OrdinalIgnoreCase)))library.GameTools.SteamLibraryFolders.Add(folder);Store.Save(library);using(NextDialog d=new NextDialog("Installed Steam games",850,550)) { ListBox list=new ListBox { Dock=DockStyle.Fill,DataSource=games };d.Body.Controls.Add(list);d.Action("Choose game executable",delegate { InstalledSteamGame game=list.SelectedItem as InstalledSteamGame;if(game!=null)NativeFiles(d,library,refresh,game); });d.Action("Open install folder",delegate { Run(d,delegate { InstalledSteamGame game=list.SelectedItem as InstalledSteamGame;if(game!=null)System.Diagnostics.Process.Start("explorer.exe",game.Folder); }); });d.Action("Close",d.Close);d.ShowDialog(owner); } });
  }
  static void Analytics(IWin32Window owner,LibraryData library,GameEntry game) {
   IEnumerable<PlaySession> sessions=library.PlaySessions??new List<PlaySession>();if(game!=null)sessions=sessions.Where(x=>x.GameId==game.Id);List<MonthlyPlayTotal> totals=GameTools.Monthly(sessions);
   using(NextDialog d=new NextDialog("Monthly play insights",850,570)) {ListView list=new ListView { View=View.Details,Dock=DockStyle.Fill,FullRowSelect=true };list.Columns.Add("Month",160);list.Columns.Add("Hours",150);list.Columns.Add("Sessions",150);list.Columns.Add("Games",150);foreach(MonthlyPlayTotal t in totals)list.Items.Add(new ListViewItem(new[]{t.Month,(t.Seconds/3600.0).ToString("0.0"),t.Sessions.ToString(),t.Games.ToString()}));d.Body.Controls.Add(list);d.Action("Session notes",delegate { NextTools.Sessions(d,library); });d.Action("Export CSV",delegate { Run(d,delegate { using(SaveFileDialog f=new SaveFileDialog { Filter="CSV|*.csv",FileName="FishBowl-monthly-play.csv" }) { if(f.ShowDialog(d)!=DialogResult.OK)return;File.WriteAllLines(f.FileName,new[]{"Month,Hours,Sessions,Games"}.Concat(totals.Select(t=>t.Month+","+(t.Seconds/3600.0).ToString("0.00",System.Globalization.CultureInfo.InvariantCulture)+","+t.Sessions+","+t.Games))); } }); });d.Action("Close",d.Close);d.ShowDialog(owner);}
  }
 }
}
