using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Windows.Forms;
using EmulatorHub;
class HubTests {
 static int checks;static void Check(bool value,string message){if(!value)throw new Exception(message);checks++;}static void Throws(Action action,string message){bool failed=false;try{action();}catch{failed=true;}Check(failed,message);}static void Pump(int ms){var clock=Stopwatch.StartNew();while(clock.ElapsedMilliseconds<ms){Application.DoEvents();Thread.Sleep(5);}}
 static object Field(object o,string name){return o.GetType().GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}static void Call(object o,string name){o.GetType().GetMethod(name,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,null);}
 static void Dialog(string title,Action show,Action<NextDialog> inspect){Exception failure=null;using(var timer=new System.Windows.Forms.Timer{Interval=180}){timer.Tick+=(a,b)=>{var form=Application.OpenForms.OfType<NextDialog>().FirstOrDefault(f=>f.Text.StartsWith(title));if(form==null)return;timer.Stop();try{inspect(form);}catch(Exception ex){failure=ex;}finally{form.Close();}};timer.Start();show();}if(failure!=null)throw failure;}
 [STAThread]static int Main(){try{Application.EnableVisualStyles();Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException);Run();Console.WriteLine("PASS: "+checks+" hub extension checks covering native sessions, nested collections, imports, custom search, adapters, portable paths, sync conflicts, restore previews, storage and UI.");return 0;}catch(Exception ex){Console.Error.WriteLine(ex);return 1;}}
 static void Run(){var fixture=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"hub-fixture-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(fixture);Directory.SetCurrentDirectory(fixture);var d=Store.Load();d.Games=new List<GameEntry>();d.Emulators=new List<EmulatorProfile>();d.Collections=new List<GameCollection>();d.SaveSnapshots=new List<SaveSnapshot>();d.UserTools=null;d.Hub=null;d.Cosmetics=new CosmeticSettings();d.GameLibraryRoot=Path.GetFullPath("hub-storage");NextData.Ensure(d);LibraryAdditions.Ensure(d);Directory.CreateDirectory("hub-root");File.WriteAllText("hub-root/game.rom","123456");File.WriteAllText("hub-root/disc.rom","disc");File.WriteAllText("hub-root/manual.txt","manual");using(var bmp=new Bitmap(32,32)){using(var gr=Graphics.FromImage(bmp))gr.Clear(Color.CornflowerBlue);bmp.Save("hub-root/cover.png");}
  var g=new GameEntry{Id="hubgame",Title="Fixture",Path=Path.GetFullPath("hub-root/game.rom"),ArtworkPath=Path.GetFullPath("hub-root/cover.png"),ManualPath=Path.GetFullPath("hub-root/manual.txt"),Description="An adventure",Tags=new List<string>{"co-op"},Discs=new List<string>{Path.GetFullPath("hub-root/disc.rom")},Extras=new GameExtras{Fields=new Dictionary<string,string>{{"Series","Fish series"}}}};d.Games.Add(g);
  Check(Hub.Ensure(d).ResumeAfterCrash,"crash recovery defaults on");Check(Hub.Ensure(d).Adapters.Count==0,"adapters are optional");Check(Hub.SearchText(g).Contains("Fish series"),"custom values searched");Check(Hub.SearchText(g).Contains("Series"),"custom keys searched");Check(LibraryAdditions.Match(d,new SmartLibraryList{Search="adventure"}).Count==1,"smart lists search descriptions");Check(LibraryAdditions.Match(d,new SmartLibraryList{Search="Fish series"}).Count==1,"smart lists search custom fields");Check(Hub.ParseFields("Publisher = Me\nPlayers = 2").Count==2,"custom fields parsed");Throws(()=>Hub.ParseFields("bad field"),"malformed custom fields rejected");Throws(()=>Hub.ParseFields("A = 1\na = 2"),"duplicate custom fields rejected");Throws(()=>Hub.ParseFields(new string('x',81)+" = y"),"long custom names rejected");Check(Hub.ParseFields("").Count==0,"custom fields removable");
  var parent=new GameCollection{Id="parent",Name="Parent",GameIds=new List<string>()};var child=new GameCollection{Id="child",Name="Child",GameIds=new List<string>{g.Id}};var leaf=new GameCollection{Id="leaf",Name="Leaf",GameIds=new List<string>()};d.Collections.AddRange(new[]{parent,child,leaf});Hub.Parent(d,child,parent.Id);Hub.Parent(d,leaf,child.Id);Check(Hub.NestedEntries(d,parent,d.Games).Single()==g,"parents include descendants");Throws(()=>Hub.Parent(d,parent,leaf.Id),"collection cycles rejected");Throws(()=>Hub.Parent(d,parent,parent.Id),"collection self-parent rejected");Throws(()=>Hub.Parent(d,parent,"missing"),"missing parent rejected");Hub.Parent(d,leaf,null);Check(leaf.ParentId==null,"parent removed");
  File.WriteAllText("HubSessionFixture.cs","class Runner { static void Main() { System.Threading.Thread.Sleep(1200); } }");string runner=Path.GetFullPath("HubSessionFixture.exe");using(var compiler=Process.Start(new ProcessStartInfo{FileName=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows),"Microsoft.NET","Framework64","v4.0.30319","csc.exe"),Arguments="/nologo /target:winexe /out:\""+runner+"\" HubSessionFixture.cs",UseShellExecute=false,CreateNoWindow=true})){compiler.WaitForExit();Check(compiler.ExitCode==0,"native session fixture builds");}
  var adapter=new EmulatorAdapter{Name="Fixture emulator",Platform="Test",Extensions=new List<string>{"rom"},Arguments="{game}",Website="https://example.com",Repository="owner/repo"};Hub.ValidateAdapter(adapter);checks++;Check(File.Exists(runner),"native session fixture available");var emulator=Hub.FromAdapter(adapter,runner);d.Emulators.Add(emulator);g.EmulatorId=emulator.Id;Check(emulator.Extensions.Single()=="rom"&&emulator.GitHubRepository=="owner/repo","adapter creates usable emulator profile");Throws(()=>Hub.ValidateAdapter(new EmulatorAdapter{Name="Bad",Extensions=new List<string>{"../rom"}}),"adapter path extensions rejected");Throws(()=>Hub.ValidateAdapter(new EmulatorAdapter{Name="Bad",Extensions=new List<string>{"rom"},Arguments="{shell}"}),"unsupported adapter token rejected");Throws(()=>Hub.ValidateAdapter(new EmulatorAdapter{Name="Bad",Extensions=new List<string>{"rom"},Website="http://example.com"}),"non-HTTPS adapter rejected");Throws(()=>Hub.FromAdapter(adapter,"missing.exe"),"missing adapter executable rejected");Check(Hub.Readiness(d,g).Contains("Ready to start"),"readiness validates emulator entry");
  string alternateRunner=Path.GetFullPath("AlternateFixture.exe");File.Copy(runner,alternateRunner,true);emulator.Builds.Add(new EmulatorBuild{Id="alternate",Label="Alternate",Executable=alternateRunner});g.PreferredBuildId="alternate";using(var activeBuild=Process.Start(new ProcessStartInfo(alternateRunner){UseShellExecute=false,CreateNoWindow=true})){Throws(()=>SaveHistory.RequireClosed(d,new SaveSnapshot{GameId=g.Id}),"save restore is blocked by a running alternate build");activeBuild.WaitForExit();}g.PreferredBuildId=null;
  var pc=new GameEntry{Id="hubpc",Title="Native fixture",Path=runner,Arguments="--literal",Tags=new List<string>(),Extras=new GameExtras{Native=true,WorkingDirectory=Path.GetDirectoryName(runner)}};d.Games.Add(pc);Check(Hub.Native(pc),"native entry recognized");Check(GameSessions.Validate(d,pc)=="--literal","native launch omits ROM path");Check(NextData.LaunchEmulator(d,pc).Executable==runner,"native session program resolved");Check(!Polish.Health(d,CancellationToken.None).Any(i=>i.Area=="Emulator"&&i.GameId==pc.Id),"native health skips emulator assignment");var invalid=UserTools.Copy(pc);invalid.Path=g.Path;Throws(()=>GameSessions.Validate(d,invalid),"native unsupported file rejected");invalid=UserTools.Copy(pc);invalid.Arguments="{game}";Throws(()=>GameSessions.Validate(d,invalid),"native templates rejected");invalid=UserTools.Copy(pc);invalid.Extras.WorkingDirectory="missing-folder";Throws(()=>GameSessions.Validate(d,invalid),"native missing working directory rejected");
  var binding=Hub.Bind(d,Path.GetFullPath("hub-root"));Check(binding.Any(p=>p.Key=="game:"+g.Id),"game relative binding");Check(binding.Any(p=>p.Key=="art:"+g.Id),"art relative binding");Check(binding.Any(p=>p.Key=="manual:"+g.Id),"manual relative binding");Check(binding.Any(p=>p.Key.StartsWith("disc:")),"disc relative binding");Check(!binding.Any(p=>p.Key=="game:"+pc.Id),"outside-root path retained");Hub.Ensure(d).Paths=binding;var plan=Hub.Rebase(d,Path.GetFullPath("new-hub-root"),false);Check(plan.Count==binding.Count&&g.Path.Contains("hub-root"),"rebase preview changes no data");Throws(()=>Hub.Resolve("hub-root","../escape"),"relative traversal rejected");Throws(()=>Hub.Resolve("hub-root",runner),"absolute relative binding rejected");var copied=UserTools.Copy(d);Hub.Rebase(copied,Path.GetFullPath("new-hub-root"),true);Check(copied.Games[0].Path.Contains("new-hub-root"),"rebase applies reviewed paths");Check(copied.Games[1].Path==runner,"rebase retains external native path");
  var portableCopy=UserTools.Copy(d);portableCopy.GameLibraryRoot=Path.GetFullPath("hub-root");portableCopy.Games[0].Saves=new List<GameSaveEntry>{new GameSaveEntry{Path=Path.GetFullPath("hub-root/live.sav"),Kind="In-game saves"}};portableCopy.SaveSnapshots=new List<SaveSnapshot>{new SaveSnapshot{Id="portablesnapshot",GameId=g.Id,Path=Path.GetFullPath("hub-root/history/save.sav"),Source=Path.GetFullPath("hub-root/live.sav")}};portableCopy.Hub.Paths=Hub.Bind(portableCopy,Path.GetFullPath("hub-root"));Check(portableCopy.Hub.Paths.Any(p=>p.Key=="root:games"&&p.Relative=="."),"collection root itself binds relatively");Hub.Rebase(portableCopy,Path.GetFullPath("new-hub-root"),true);Check(portableCopy.GameLibraryRoot==Path.GetFullPath("new-hub-root"),"collection root rebases");Check(portableCopy.Games[0].Saves[0].Path.Contains("new-hub-root"),"linked save paths rebase");Check(portableCopy.SaveSnapshots[0].Path.Contains("new-hub-root")&&portableCopy.SaveSnapshots[0].Source.Contains("new-hub-root"),"snapshot paths and sources rebase");portableCopy.Games[0].Path="later-edit.rom";Throws(()=>Hub.Rebase(portableCopy,Path.GetFullPath("third-hub-root"),false),"changed path bindings require fresh review");
  var originalPath=g.Path;var originalEmulator=g.EmulatorId;var package=Hub.ExportPackage(d);Check(package.Schema==1&&package.Profile!=null,"transfer includes versioned personal profile");Check(Hub.TransferPlan(d,package).Count==0,"identical transfer needs no changes");package.Games[0].Description="Updated description";var changes=Hub.TransferPlan(d,package);Check(changes[0].Status.StartsWith("Conflict"),"unknown baseline conflicts default local");Hub.Ensure(d).SyncHashes[g.Id]=Hub.Fingerprint(g);changes=Hub.TransferPlan(d,package);Check(changes[0].Status=="Update","unchanged local baseline allows update");package.Games[0].Path="foreign.rom";package.Games[0].EmulatorId="foreign";package.Games[0].Arguments="foreign args";package.Games[0].Extras.Fields["Publisher"]="Remote publisher";package.Games[0].Extras.Native=true;package.Games[0].Extras.WorkingDirectory="foreign-work";changes=Hub.TransferPlan(d,package);Hub.ApplyTransfer(d,changes);g=d.Games[0];Check(g.Description=="Updated description","reviewed sync applies metadata");Check(g.Path==originalPath&&g.EmulatorId==originalEmulator,"sync preserves local launch paths and assignments");Check(g.Arguments!="foreign args","sync preserves local arguments");Check(g.Extras.Fields["Publisher"]=="Remote publisher","sync imports custom metadata");Check(!g.Extras.Native&&g.Extras.WorkingDirectory!="foreign-work","sync preserves local launch type and working folder");package=Hub.ExportPackage(d);package.Games[0].Description="Next";changes=Hub.TransferPlan(d,package);g.Notes="Later local edit";Throws(()=>Hub.ApplyTransfer(d,changes),"stale sync review rejected");Check(g.Description=="Updated description","stale sync atomic no-op");Throws(()=>Hub.TransferPlan(d,new TransferPackage{Schema=99,Games=new List<GameEntry>()}),"unknown transfer schema rejected");Throws(()=>Hub.TransferPlan(d,new TransferPackage{Schema=1,Games=new List<GameEntry>{g,g}}),"duplicate transfer IDs rejected");package=Hub.ExportPackage(d);package.Games.Add(new GameEntry{Id="duplicate-path",Title="Duplicate",Path=g.Path});changes=Hub.TransferPlan(d,package);Check(changes.Single().Status.StartsWith("Duplicate"),"duplicate incoming paths identified");Throws(()=>Hub.ApplyTransfer(d,changes),"duplicate path apply rejected");
  var duplicateIncoming=new TransferPackage{Schema=1,Games=new List<GameEntry>{new GameEntry{Id="incoming-a",Title="A",Path="same-new.rom"},new GameEntry{Id="incoming-b",Title="B",Path="same-new.rom"}}};Check(Hub.TransferPlan(d,duplicateIncoming).Count(c=>c.Status=="Add")==1,"duplicate paths within an incoming package are not both added");var staleAdd=Hub.TransferPlan(d,new TransferPackage{Schema=1,Games=new List<GameEntry>{new GameEntry{Id="incoming-new",Title="New",Path="later-added.rom"}}});d.Games.Add(new GameEntry{Id="later",Title="Later",Path="later-added.rom"});Throws(()=>Hub.ApplyTransfer(d,staleAdd),"concurrent path additions invalidate sync review");d.Games.RemoveAll(game=>game.Id=="later");
  Check(!d.Hub.WatchReleases,"release watching defaults off");emulator.ManualVersion="1.0";var releaseResults=ReleaseWatch.Check(new[]{emulator},CancellationToken.None,url=>"{\"tag_name\":\"v2.0\",\"name\":\"v2.0\",\"html_url\":\"https://github.com/owner/repo/releases/tag/v2.0\",\"body\":\"Changes\",\"draft\":false,\"prerelease\":false}");Check(releaseResults.Count==1&&releaseResults[0].Release!=null,"release watch reads configured feeds");Check(ReleaseWatch.Apply(d,releaseResults).Count==1,"newer releases produce a notification candidate");Check(ReleaseWatch.Apply(d,releaseResults).Count==0,"same release is not notified twice");Check(emulator.LatestReleaseTag=="v2.0"&&emulator.LastUpdateCheck!=null,"release inventory persists checked information");var failedRelease=ReleaseWatch.Check(new[]{emulator},CancellationToken.None,url=>{throw new IOException("offline");});Check(failedRelease[0].Error=="offline","offline feed error retained without mutating emulator files");Check(ReleaseWatch.Apply(d,failedRelease).Count==0,"failed feed is quiet");Check(ReleaseWatch.Check(new[]{new EmulatorProfile{Id="no-feed",Preset="Custom",Executable=runner}},CancellationToken.None,url=>{throw new Exception("must not connect");}).Count==0,"unconfigured feed skipped");
  var metadata=Hub.ParseMetadata("{\"query\":{\"pages\":{\"1\":{\"title\":\"Fixture game\",\"extract\":\"A game.\",\"fullurl\":\"https://en.wikipedia.org/wiki/Fixture\",\"thumbnail\":{\"source\":\"https://upload.wikimedia.org/example.png\"}}}}}");Check(metadata.Single().Description=="A game.","metadata description parsed");Check(metadata[0].Image.Contains("wikimedia"),"metadata image parsed");Check(Hub.ParseMetadata("{}").Count==0,"empty metadata handled");Check(Hub.MetadataQuery("A & B").Contains("A%20%26%20B"),"lookup query encoded");Check(Hub.Https("https://example.com")&&!Hub.Https("file:///C:/test")&&!Hub.Https("https://user@example.com"),"external addresses constrained");Throws(()=>Hub.Fetch("http://example.com",100,CancellationToken.None),"HTTP download rejected");Throws(()=>Hub.Fetch("https://example.com",0,CancellationToken.None),"invalid download size rejected");using(var networkCancel=new CancellationTokenSource()){networkCancel.Cancel();Throws(()=>Hub.Fetch("https://example.com",100,networkCancel.Token),"cancelled network request stops before connecting");}g.Extras.MetadataSource="https://example.com/source";Check(UserTools.Html(new[]{g},false,false,false,CancellationToken.None).Contains("Metadata source and licensing"),"HTML catalog carries metadata attribution link");
  Directory.CreateDirectory("hub-live");File.WriteAllText("hub-live/save.dat","before");var save=SaveHistory.Capture(d,g,Path.GetFullPath("hub-live"),"In-game saves",false,CancellationToken.None);File.WriteAllText("hub-live/save.dat","after");File.WriteAllText("hub-live/new.dat","live only");string preview=Hub.RestorePreview(save,CancellationToken.None);Check(preview.Contains("REPLACE save.dat"),"restore previews overwritten contents");Check(preview.Contains("REMOVE FROM LIVE"),"restore previews extra live files");Check(File.ReadAllText("hub-live/save.dat")=="after","restore preview leaves live save unchanged");g.Saves=new List<GameSaveEntry>{new GameSaveEntry{Path=Path.GetFullPath("hub-live"),Kind="In-game saves",IsFolder=true}};var totals=Hub.Storage(d,CancellationToken.None);Check(totals["Games"]>=10,"game storage measured");Check(totals["Artwork"]>0,"artwork storage measured");Check(totals["Linked saves"]==14,"linked save folder measured");Directory.CreateDirectory("cloud-fixture");File.WriteAllText("cloud-fixture/save (conflicted copy).dat","data");File.WriteAllText("cloud-fixture/normal.dat","data");Check(Hub.CloudConflicts(Path.GetFullPath("cloud-fixture"),CancellationToken.None).Count==1,"cloud conflict names detected");var cancel=new CancellationTokenSource();cancel.Cancel();Throws(()=>Hub.Storage(d,cancel.Token),"storage scan cancellable");Hub.Record(d,"Fixture edit");Check(Hub.Ensure(d).Activity.Last().Text=="Fixture edit","activity recorded");
  var scheduled=HubSaveSchedule.Capture(UserTools.Copy(d),CancellationToken.None);Console.WriteLine("Scheduled captures: "+scheduled.Snapshots.Count+"; "+string.Join(" | ",scheduled.Messages));Check(scheduled.Snapshots.Count==1,"scheduled capture includes changed original linked save");HubSaveSchedule.Apply(d,scheduled);Check(HubSaveSchedule.Capture(UserTools.Copy(d),CancellationToken.None).Snapshots.Count==0,"scheduled capture skips unchanged and managed snapshots");Check(File.ReadAllText("hub-live/save.dat")=="after","scheduled captures preserve originals");Throws(()=>HubSaveSchedule.Capture(UserTools.Copy(d),cancel.Token),"scheduled capture cancellable");Check(d.Hub.CaptureMinutes==0,"scheduled captures default off");File.WriteAllText("hub-live/save.dat","third");var cancelledCopy=UserTools.Copy(d);int snapshotsBefore=cancelledCopy.SaveSnapshots.Count;using(var midCancel=new CancellationTokenSource()){Throws(()=>HubSaveSchedule.Capture(cancelledCopy,midCancel.Token,message=>midCancel.Cancel()),"cancellation after a completed capture rolls back the batch");}Check(cancelledCopy.SaveSnapshots.Count==snapshotsBefore,"cancelled batch retains original snapshot catalog");Check(File.ReadAllText("hub-live/save.dat")=="third","cancelled capture preserves live originals");File.WriteAllText("hub-live/save.dat","after");
  var markerPath=Path.GetFullPath("recovery-fixture/open-session.json");var firstMarker=new RecoveryMarker(markerPath);Check(firstMarker.Owned&&!firstMarker.Interrupted,"first run claims recovery marker");var secondMarker=new RecoveryMarker(markerPath);Check(!secondMarker.Owned&&!secondMarker.Interrupted,"another live instance is not reported as a crash");secondMarker.Close();Check(File.Exists(markerPath),"second instance retains owner marker");firstMarker.Close();Check(!File.Exists(markerPath),"clean close removes marker");File.WriteAllText(markerPath,"interrupted");var recoveredMarker=new RecoveryMarker(markerPath);Check(recoveredMarker.Interrupted&&recoveredMarker.Owned,"stale marker offers recovery");recoveredMarker.Close();Check(!RecoveryMarker.Alive("invalid"),"invalid recovery marker handled");
  Store.Save(d);var loaded=Store.Load();Check(loaded.Hub.Paths.Count==binding.Count,"relative bindings persist");Check(loaded.Games[0].Extras.Fields["Series"]=="Fish series","custom fields persist");Check(loaded.Games[1].Extras.Native,"native entry persists");Check(loaded.Collections[1].ParentId==parent.Id,"nested collections persist");
  using(var owner=new Form{ShowInTaskbar=false,StartPosition=FormStartPosition.Manual,Location=new Point(-3000,-3000)}){owner.Show();d.Theme.ConfirmBeforeGameLaunch=false;ExperienceTools.Launch(owner,d,pc);Throws(()=>GameSessions.Validate(d,pc),"running native game cannot launch twice");Throws(()=>SaveHistory.RequireClosed(d,new SaveSnapshot{GameId=pc.Id}),"running native game cannot restore saves");Pump(2200);Check(pc.LaunchCount==1,"native program launches through session tracker");Check(UserTools.ActiveLaunches==0,"native session finishes");Check(d.PlaySessions.Any(s=>s.GameId==pc.Id&&s.EndedAt!=null),"native session journal records completion");
   Dialog("Library extensions",()=>Hub.Show(owner,d),f=>{var tabs=NextUi.Descendants(f).OfType<TabControl>().Single();Check(tabs.TabPages.Count==4,"extensions grouped in four tabs");foreach(TabPage tab in tabs.TabPages){tabs.SelectedTab=tab;Pump(30);Check(tab.AutoScroll,"extension page scrolls: "+tab.Text);using(var bmp=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bmp,new Rectangle(Point.Empty,bmp.Size));bmp.Save("hub-"+tab.Text.Replace(" ","-")+".png");}}});
   NextUi.TextPercent=200;Dialog("Library extensions",()=>Hub.Show(owner,d),f=>{var tabs=NextUi.Descendants(f).OfType<TabControl>().Single();Check(tabs.TabPages[0].BackColor==FishBowlPalette.ThemeSurface,"extension surfaces follow theme");using(var bmp=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bmp,new Rectangle(Point.Empty,bmp.Size));bmp.Save("hub-large-text.png");}});NextUi.TextPercent=100;
   Dialog("Game extensions",()=>Hub.GameOptions(owner,d,g),f=>{Check(NextUi.Descendants(f).OfType<TabControl>().Single().TabPages.Count==2,"per-game options grouped");});
   Dialog("Online metadata",()=>Hub.Metadata(owner,d,g),f=>{Check(NextUi.Descendants(f).OfType<Button>().Any(b=>b.Text=="Search online"),"online lookup is explicit");});
   Dialog("Emulator adapters",()=>Hub.Adapters(owner,d),f=>{Check(NextUi.Descendants(f).OfType<Button>().Any(b=>b.Text=="Export template"),"adapter template export available");});
   Dialog("Emulator versions",()=>Hub.Inventory(owner,d),f=>{Check(NextUi.Descendants(f).OfType<ListView>().Single().Items.Count==emulator.Builds.Count+1,"emulator inventory constructs");});
   Dialog("Profile transfer",()=>Hub.Transfer(owner,d),f=>{Check(NextUi.Descendants(f).OfType<Button>().Any(b=>b.Text=="Preview Library sync"),"sync uses reviewed import");});
   Dialog("Review folder import",()=>Hub.PreviewImport(owner,d,new List<GameEntry>{new GameEntry{Id="newgame",Title="New",Path="new.rom"}}),f=>{Check(NextUi.Descendants(f).OfType<ListView>().Single().CheckBoxes,"folder import selectable");});Check(d.Games.Count==2,"cancelled import preserves Library");
   Dialog("Linked-save backup schedule",()=>HubSaveSchedule.Settings(owner,d),f=>{Check(NextUi.Descendants(f).OfType<Button>().Any(b=>b.Text=="Capture linked saves now"),"live save capture accessible");});
   Dialog("Library view styles",()=>Hub.ViewStyles(owner,d),f=>{Check(NextUi.Descendants(f).OfType<CheckBox>().Count()==3,"view styling controls available");});
  }
  d.Cosmetics.DetailPreview=true;d.Cosmetics.PlatformLabels=true;d.Cosmetics.LibrarySpacing="Compact";g.ConsoleLabel="Test platform";using(var f=new GameLibraryDialog(d)){f.ShowInTaskbar=false;f.StartPosition=FormStartPosition.Manual;f.Location=new Point(-3000,-3000);f.Show();Pump(100);var list=(ListView)Field(f,"games");list.Items[0].Selected=true;Call(f,"UpdateDetailPane");Check(((Panel)Field(f,"detailPane")).Visible,"detail pane visible on wide Library");Check(list.Right<=((Panel)Field(f,"detailPane")).Left,"preview pane occupies separate layout space");Check(list.Items[0].Text.Contains("Test platform"),"platform label displayed");Check(list.SmallImageList.ImageSize.Height<28,"compact row density applied");Call(f,"RememberNavigation");Call(f,"ToggleGameView");Pump(80);Call(f,"RememberNavigation");Check(d.UserTools.Views.ContainsKey("Details")&&d.UserTools.Views.ContainsKey("Artwork"),"views remember separate state");using(var bmp=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bmp,new Rectangle(Point.Empty,bmp.Size));bmp.Save("hub-library-preview.png");}}
  using(var main=new MainForm(true)){main.ShowInTaskbar=false;main.StartPosition=FormStartPosition.Manual;main.Location=new Point(-3000,-3000);Call(main,"StartHubRuntime");Check(File.Exists(Path.Combine(Store.DataDirectory,"open-session.json")),"runtime creates isolated recovery marker");Check(!((NotifyIcon)Field(main,"releaseWatchIcon")).Visible,"release watcher starts without a visible tray icon");main.Show();Pump(80);main.Close();}Check(!File.Exists(Path.Combine(Store.DataDirectory,"open-session.json")),"runtime clean close removes recovery marker");
  using(var f=new LivingRoomLibrary(d)){f.ShowInTaskbar=false;f.Show();Pump(50);Check(f.FormBorderStyle==FormBorderStyle.None&&f.WindowState==FormWindowState.Maximized,"living-room full-screen mode");var previousCovers=((Dictionary<string,Bitmap>)Field(f,"covers")).Values.ToList();Call(f,"RefreshAfterDetails");Check(!((Dictionary<string,Bitmap>)Field(f,"covers")).Values.Any(b=>previousCovers.Contains(b)),"living-room artwork refresh replaces stale covers");Pump(30);Check(NextUi.Descendants(f).OfType<Button>().Any(b=>b.Text=="Exit full screen"),"living-room exit available");using(var bmp=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bmp,new Rectangle(Point.Empty,bmp.Size));bmp.Save("hub-living-room.png");}f.Close();}NextUi.TextPercent=200;using(var f=new LivingRoomLibrary(d)){f.ShowInTaskbar=false;f.Show();Pump(40);var cards=NextUi.Descendants(f).OfType<ListBox>().Single();Check(cards.Font.Size>=48&&cards.ItemHeight>=240,"living-room mode honors large text");using(var bmp=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bmp,new Rectangle(Point.Empty,bmp.Size));bmp.Save("hub-living-room-large-text.png");}f.Close();}NextUi.TextPercent=100;
 }
}
