using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Windows.Forms;
using EmulatorHub;
class UserToolsTests {
 static int checks;static void Check(bool value,string name){if(!value)throw new Exception(name);checks++;}
 static void Throws(Action a,string name){bool threw=false;try{a();}catch{threw=true;}Check(threw,name);}
 [STAThread]static int Main(){Application.EnableVisualStyles();var d=Store.Load();d.Games=new List<GameEntry>();d.Collections=new List<GameCollection>();d.Emulators=new List<EmulatorProfile>();d.PlaySessions=new List<PlaySession>();d.PlayQueue=new List<string>();d.SmartLists=new List<SmartLibraryList>();d.UserTools=null;NextData.Ensure(d);LibraryAdditions.Ensure(d);
  var g=new GameEntry{Id="g",Title="Test <script>alert('x')</script>",Path=Path.GetFullPath("private.rom"),Favorite=true,PlayStatus="Completed",LaunchCount=3,LastLaunched="private time",TotalPlaySeconds=300,Tags=new List<string>{"Test"}};d.Games.Add(g);var settings=UserTools.Ensure(d);string original=settings.ActiveId;settings.WeeklyMinutes=100;settings.BreakMinutes=20;d.PlayQueue.Add(g.Id);d.PlaySessions.Add(new PlaySession{Id="old",GameId=g.Id,StartedAt=DateTime.UtcNow.AddDays(-1).ToString("o"),EndedAt=DateTime.UtcNow.ToString("o"),Seconds=300});Store.Save(d);
  var second=UserTools.Create(d,"Second");Throws(()=>UserTools.Create(d,"second"),"duplicate names rejected");Throws(()=>UserTools.Create(d," "),"empty names rejected");UserTools.Switch(d,second.Id);Check(!g.Favorite&&g.PlayStatus=="Not started"&&g.TotalPlaySeconds==0&&g.LaunchCount==0,"new profile resets personal progress");Check(d.PlaySessions.Count==0&&d.PlayQueue.Count==0,"session journal and queue isolated");Check(d.UserTools.WeeklyMinutes==0&&d.UserTools.BreakMinutes==0,"goal preferences isolated");g.Favorite=false;g.PlayStatus="Playing";g.TotalPlaySeconds=120;d.UserTools.WeeklyMinutes=25;UserTools.Switch(d,original);Check(g.Favorite&&g.PlayStatus=="Completed"&&g.TotalPlaySeconds==300&&g.LaunchCount==3,"original progress restored");Check(d.UserTools.WeeklyMinutes==100&&d.PlayQueue.Count==1&&d.PlaySessions.Count==1,"original preferences restored");UserTools.ActiveLaunches=1;Throws(()=>UserTools.Switch(d,second.Id),"switch blocked during session");Throws(()=>UserTools.BeginGuest(d),"guest blocked during session");UserTools.ActiveLaunches=0;Store.Save(d);var reload=Store.Load();Check(reload.UserTools.Users.Count==2,"profiles survive persistence");UserTools.Switch(reload,second.Id);Check(reload.Games[0].PlayStatus=="Playing"&&reload.Games[0].TotalPlaySeconds==120&&reload.UserTools.WeeklyMinutes==25,"second profile survives reload");
  string saved=File.ReadAllText(Store.FileName);var snapshot=UserTools.BeginGuest(d);g.Title="Guest edit";g.LaunchCount++;Store.Save(d);Check(File.ReadAllText(Store.FileName)==saved,"guest save cannot persist changes");UserTools.EndGuest(d,snapshot);g=d.Games[0];Check(g.Title.Contains("Test")&&g.LaunchCount==3&&!UserTools.Guest,"guest exit restores all library values");
  var record=UserTools.BeforeBulk(d,new List<GameEntry>{g});g.Favorite=false;g.Tags.Add("new");UserTools.AfterBulk(d,record,new List<GameEntry>{g});g.Description="unrelated later change";Check(UserTools.UndoBulk(d).StartsWith("Undid"),"bulk undo works");Check(g.Favorite&&!g.Tags.Contains("new")&&g.Description=="unrelated later change","undo restores changed fields only");record=UserTools.BeforeBulk(d,new List<GameEntry>{g});g.PlayStatus="On hold";UserTools.AfterBulk(d,record,new List<GameEntry>{g});g.PlayStatus="Dropped";Check(UserTools.UndoBulk(d).StartsWith("Undo stopped")&&g.PlayStatus=="Dropped","conflicts cause atomic no-op");d.UserTools.Undo.Clear();
  var collection=new GameCollection{Id="c",Name="Test",GameIds=new List<string>()};d.Collections.Add(collection);record=UserTools.BeforeBulk(d,new List<GameEntry>{g});collection.GameIds.Add(g.Id);UserTools.AfterBulk(d,record,new List<GameEntry>{g});Check(UserTools.UndoBulk(d).StartsWith("Undid")&&collection.GameIds.Count==0,"undo restores collection additions");
  Check(UserTools.Diagnose(d,g).Contains("Assign an emulator"),"unassigned game diagnostic");string html=UserTools.Html(d.Games,false,false);Check(!html.Contains(g.Path)&&!html.Contains(g.LastLaunched),"default catalog excludes private paths and history");Check(html.Contains("&lt;script&gt;")&&!html.Contains("<script>alert"),"catalog escapes metadata markup");Check(UserTools.Html(d.Games,true,true).Contains(UserTools.Escape(g.Path)),"explicit path export works");Check(!html.Contains("https://")&&!html.Contains("http://"),"catalog has no remote dependencies");
  d.PlaySessions.Add(new PlaySession{Id="outside",StartedAt=DateTime.UtcNow.AddDays(-8).ToString("o"),Seconds=999});d.PlaySessions.Add(new PlaySession{Id="future",StartedAt=DateTime.UtcNow.AddDays(1).ToString("o"),Seconds=999});Check(UserTools.WeekSeconds(d,DateTime.UtcNow)==300,"goal excludes old and future sessions");
  File.WriteAllText("rom.bin","123456789");File.WriteAllText("reference.dat","<!DOCTYPE datafile SYSTEM 'http://invalid.example/dat.dtd'><datafile><game name='test'><rom name='rom.bin' size='9' crc='cbf43926' md5='25f9e794323b453885f5181f1b624d0b' sha1='f7c3bc1d808e04732adf679965ccc34ca7ae3441'/></game></datafile>");Check(RomIntegrity.Check("reference.dat","rom.bin",CancellationToken.None,x=>{}).StartsWith("Verified"),"DAT CRC MD5 SHA1 verification");File.WriteAllText("rom.bin","123456780");Check(RomIntegrity.Check("reference.dat","rom.bin",CancellationToken.None,x=>{}).StartsWith("Mismatch"),"DAT mismatch identified");File.WriteAllText("other.bin","123456780");Check(RomIntegrity.Check("reference.dat","other.bin",CancellationToken.None,x=>{}).StartsWith("Unrecognized"),"unknown checksum is not labeled corrupted");var cancel=new CancellationTokenSource();cancel.Cancel();Throws(()=>RomIntegrity.Check("reference.dat","rom.bin",cancel.Token,x=>{}),"integrity check cancels");File.WriteAllText("invalid.dat","<broken>");Throws(()=>RomIntegrity.Check("invalid.dat","rom.bin",CancellationToken.None,x=>{}),"malformed DAT rejected");
  using(var f=new Form{Width=700,Height=400,ShowInTaskbar=false,StartPosition=FormStartPosition.Manual,Location=new Point(-3000,-3000)}){var list=new ListBox{Top=10,Width=250,Height=100};list.Items.AddRange(new object[]{"one","two","three"});list.SelectedIndex=0;int activated=0;list.DoubleClick+=(a,b)=>activated++;var button=new Button{Text="Action",Top=150};int clicked=0;button.Click+=(a,b)=>clicked++;f.Controls.Add(list);f.Controls.Add(button);f.Show();list.Focus();UserToolRuntime.ApplyButtons(f,f,2);Check(list.SelectedIndex==1,"controller navigates selected list item");UserToolRuntime.ApplyButtons(f,f,0x1000);Check(activated==1,"controller activates selected item");button.Focus();UserToolRuntime.ApplyButtons(f,f,0x1000);Check(clicked==1,"controller activates focused button");UserToolRuntime.ApplyButtons(f,f,0x2000);Check(!f.IsDisposed,"controller B preserves main window");}
  using(var owner=new Form{ShowInTaskbar=false,StartPosition=FormStartPosition.Manual,Location=new Point(-3000,-3000)}){owner.Show();using(var timer=new System.Windows.Forms.Timer{Interval=400}){timer.Tick+=(a,b)=>{var f=Application.OpenForms.Cast<Form>().OfType<NextDialog>().FirstOrDefault(x=>x.Text=="User tools");if(f==null)return;timer.Stop();var tabs=NextUi.Descendants(f).OfType<TabControl>().Single();Check(tabs.TabPages.Count==3,"new tools use three grouped tabs");foreach(TabPage tab in tabs.TabPages){tabs.SelectedTab=tab;Application.DoEvents();Check(tab.AutoScroll,"tool tabs can scroll");using(var bmp=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bmp,new Rectangle(0,0,bmp.Width,bmp.Height));bmp.Save("user-tools-"+tab.Text.Replace(" ","-")+".png");}}f.Close();};timer.Start();UserTools.Show(owner,d,()=>{});}}
  using(var art=new Bitmap(40,30)){art.Save("art.png",System.Drawing.Imaging.ImageFormat.Png);}g.ArtworkPath=Path.GetFullPath("art.png");Check(UserTools.Html(d.Games,false,false,true).Contains("data:image/png;base64,"),"artwork embedded as offline thumbnail");Check(!UserTools.Html(d.Games,false,false,true).Contains(g.ArtworkPath),"artwork source path stays private");Check(!UserTools.Html(d.Games,false,false).Contains("data:image"),"artwork excluded unless selected");Throws(()=>UserTools.Html(d.Games,false,false,true,cancel.Token),"catalog rendering cancellation");
  var reference=d.Games[0];saved=File.ReadAllText(Store.FileName);using(var owner=new Form{ShowInTaskbar=false,StartPosition=FormStartPosition.Manual,Location=new Point(-3000,-3000)}){owner.Show();using(var timer=new System.Windows.Forms.Timer{Interval=300}){int phase=0;timer.Tick+=(a,b)=>{if(phase==0){var f=Application.OpenForms.Cast<Form>().OfType<NextDialog>().FirstOrDefault(x=>x.Text=="User tools");if(f==null)return;phase=1;NextUi.Descendants(f).OfType<Button>().Single(x=>x.Text=="Guest browser").PerformClick();}else{var guest=Application.OpenForms.Cast<Form>().OfType<NextDialog>().FirstOrDefault(x=>x.Text.StartsWith("Guest browser"));if(guest==null)return;timer.Stop();Check(UserTools.Guest,"guest UI enables persistence guard");Check(!NextUi.Descendants(guest).OfType<Button>().Any(x=>x.Text.Contains("Edit")||x.Text.Contains("Remove")),"guest UI has no editing commands");var input=NextUi.Descendants(guest).OfType<TextBox>().Single();input.Text="no match anywhere";Check(NextUi.Descendants(guest).OfType<ListBox>().Single().Items.Count==0,"guest library filter works");Store.Save(d);guest.Close();}};timer.Start();UserTools.Show(owner,d,()=>{});}}Check(!UserTools.Guest&&object.ReferenceEquals(reference,d.Games[0]),"guest UI leaves live game references intact");Check(File.ReadAllText(Store.FileName)==saved,"guest UI makes no library writes");
  Console.WriteLine("PASS: "+checks+" user-tool checks covering profiles, guest persistence, undo conflicts, catalog privacy, DAT checksums and controller actions.");return 0;
 }
}
