using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using Avalonia.Controls;

namespace EmulatorHub
{
    public partial class MainWindow
    {
        private CompanionServer companionServer;
        private async Task ShowLibraryIntegrations()
        {
            var settings = IntegrationData.Ensure(library); var dialog = new FishDialog("Library tools", 760, 720);
            var achievements = new StackPanel { Spacing = 8 }; var user = Ui.Field(settings.AchievementUser); var key = Ui.Field(); key.PasswordChar = '●';
            var achievementResults = Ui.Paragraphs(String.Join("\n", (settings.CachedAchievementUser == settings.AchievementUser ? settings.Achievements : new List<AchievementProgress>()).Select(a => a.Title + " · " + a.NumAwarded + "/" + a.MaxPossible)), true); achievementResults.MinHeight = 300;
            achievements.Children.Add(Ui.Hint("View RetroAchievements progress. Achievement unlocking depends on supported emulators. API keys are used for this request and are not saved in the library."));
            achievements.Children.Add(Ui.Caption("Username")); achievements.Children.Add(user); achievements.Children.Add(Ui.Caption("API key (or FISHBOWL_RA_API_KEY environment variable)")); achievements.Children.Add(key);
            achievements.Children.Add(Ui.Action("Refresh progress", async () => { string secret = String.IsNullOrWhiteSpace(key.Text) ? Environment.GetEnvironmentVariable("FISHBOWL_RA_API_KEY") : key.Text; string username = (user.Text ?? "").Trim(); var response = await Task.Run(() => IntegrationData.FetchAchievements(username, secret, CancellationToken.None)); settings.AchievementUser = username; settings.CachedAchievementUser = username; settings.Achievements = response.Results; settings.AchievementUpdatedAt = DateTime.UtcNow.ToString("o"); key.Text = ""; Store.Save(library); achievementResults.Text = String.Join("\n", settings.Achievements.Select(a => a.Title + " · " + a.NumAwarded + "/" + a.MaxPossible)); })); achievements.Children.Add(achievementResults);
            var providers = new StackPanel { Spacing = 8 }; var provider = Ui.Combo(settings.Extensions.Select(e => e.Name), settings.Extensions.FirstOrDefault()?.Name);
            providers.Children.Add(Ui.Hint("Extensions provide metadata catalogs, importer catalogs, or emulator adapters. Manifests contain data and do not execute plugin code.")); providers.Children.Add(provider);
            providers.Children.Add(Ui.Action("Add extension", async () => { var file = await Ui.PickFile(dialog, "Extension manifest", "JSON|*.json"); if (file == null) return; var extension = IntegrationData.LoadExtension(file); if (settings.Extensions.Any(e => e.Id == extension.Id)) throw new IOException("This extension is already registered."); settings.Extensions.Add(extension); if (extension.Kind == "Emulator") { if (library.Hub == null) library.Hub = new HubSettings(); if (library.Hub.Adapters == null) library.Hub.Adapters = new List<EmulatorAdapter>(); library.Hub.Adapters.Add(new EmulatorAdapter { ExtensionId = extension.Id, Name = extension.Name, Platform = extension.Platform, Arguments = extension.Arguments, Extensions = extension.Extensions == null ? new List<string>() : extension.Extensions.ToList(), Website = extension.Website }); } Store.Save(library); provider.ItemsSource = settings.Extensions.Select(e => e.Name).ToList(); provider.SelectedItem = extension.Name; }));
            providers.Children.Add(Ui.Action("Remove extension", async () => { var entry = settings.Extensions.FirstOrDefault(e => e.Name == provider.SelectedItem as string); if (entry == null || !await Ui.Confirm(dialog, "Remove " + entry.Name + " from FishBowl?")) return; settings.Extensions.Remove(entry); if (entry.Kind == "Emulator" && library.Hub?.Adapters != null) library.Hub.Adapters.RemoveAll(a => a.ExtensionId == entry.Id); Store.Save(library); provider.ItemsSource = settings.Extensions.Select(e => e.Name).ToList(); }));
            providers.Children.Add(Ui.Action("Preview and apply metadata", async () => { var entry = settings.Extensions.FirstOrDefault(e => e.Name == provider.SelectedItem as string); if (entry == null || entry.Kind != "Metadata") throw new IOException("Select a Metadata extension."); var records = await Task.Run(() => IntegrationData.ReadCatalog(entry, CancellationToken.None)); var matches = library.Games.Select(g => new { Game = g, Record = IntegrationData.Match(g, records) }).Where(m => m.Record != null).ToList(); if (matches.Count == 0) { await Ui.Message(dialog, "No unique matching metadata was found."); return; } var review = new FishDialog("Metadata preview", 680, 600); var rows = new StackPanel { Spacing = 8 }; rows.Children.Add(Ui.Hint("Choose the games to update. Custom library titles and game files stay unchanged.")); var checks = matches.Select(m => Ui.Check(m.Game.Title + " · " + m.Record.Genre + " · " + m.Record.Developer, true)).ToList(); foreach (var check in checks) rows.Children.Add(check); var chosen = matches.Take(0).ToList(); rows.Children.Add(review.Footer("Apply selected", async () => { chosen = matches.Where((m, i) => checks[i].IsChecked == true).ToList(); if (chosen.Count == 0) { await Ui.Message(review, "Select at least one game."); return false; } return true; })); review.Body = new ScrollViewer { Content = rows }; await review.Present(dialog); if (review.Confirmed) { foreach (var match in chosen) IntegrationData.ApplyMetadata(match.Game, match.Record); Store.Save(library); RefreshGameLibrary(); } }));
            providers.Children.Add(Ui.Action("Import catalog entries", async () => { var entry = settings.Extensions.FirstOrDefault(e => e.Name == provider.SelectedItem as string); if (entry == null || entry.Kind != "Importer") throw new IOException("Select an Importer extension."); var incoming = await Task.Run(() => { string json; if (!String.IsNullOrWhiteSpace(entry.CatalogUrl)) json = IntegrationData.FetchJson(entry.CatalogUrl, CancellationToken.None); else { if (!File.Exists(entry.CatalogPath) || new FileInfo(entry.CatalogPath).Length > 4 * 1024 * 1024) throw new IOException("Choose an available catalog smaller than 4 MB."); json = File.ReadAllText(entry.CatalogPath); } var records = Json.Deserialize<List<GameEntry>>(json); if (records == null) throw new IOException("Importer catalogs must contain a JSON array of game entries."); return records; }); var candidates = IntegrationData.PrepareImport(library, incoming); await new ResultsDialog("Import preview", candidates.Select(g => g.Title + " · " + g.Path)).Present(dialog); if (candidates.Count == 0 || !await Ui.Confirm(dialog, "Import these " + candidates.Count + " reviewed games?")) return; foreach (var game in candidates) { GameLibraryRemoval.AllowPath(library, game.Path); library.Games.Add(game); } Store.Save(library); RefreshGameLibrary(); }));
            providers.Children.Add(Ui.Action("Apply selected game cover", async () => { var game = SelectedLibraryGame(); var entry = settings.Extensions.FirstOrDefault(e => e.Name == provider.SelectedItem as string); if (game == null || entry == null || entry.Kind != "Metadata") throw new IOException("Select a game in Library and a Metadata extension."); var records = await Task.Run(() => IntegrationData.ReadCatalog(entry, CancellationToken.None)); var record = IntegrationData.Match(game, records); if (record == null || String.IsNullOrWhiteSpace(record.CoverUrl)) throw new IOException("This game has no unique matching cover in the catalog."); if (!await Ui.Confirm(dialog, "Download and retain this cover for " + game.Title + "?\n\n" + record.CoverUrl)) return; game.ArtworkPath = await Task.Run(() => DownloadLibraryCover(record.CoverUrl)); Store.Save(library); RefreshGameLibrary(); }));
            providers.Children.Add(Ui.Action("Apply emulator adapter", async () => { var entry = settings.Extensions.FirstOrDefault(e => e.Name == provider.SelectedItem as string); var emulator = CurrentEmulator(); if (entry == null || entry.Kind != "Emulator" || emulator == null) { await Ui.Message(dialog, "Select an emulator in the Emulators tab and an Emulator extension."); return; } if (!await Ui.Confirm(dialog, "Apply " + entry.Name + " arguments and extensions to " + emulator.Name + "?")) return; emulator.Arguments = entry.Arguments; emulator.Extensions = entry.Extensions; emulator.Platform = entry.Platform; Store.Save(library); RefreshHub(); }));
            var companion = new StackPanel { Spacing = 8 }; var address = Ui.Field("127.0.0.1"); var port = new NumericUpDown { Minimum = 1024, Maximum = 65535, Value = settings.CompanionPort < 1024 ? 17325 : settings.CompanionPort }; var connection = Ui.Paragraphs("Companion stopped."); connection.MinHeight = 150;
            companion.Children.Add(Ui.Hint("Start a read-only browser companion for this library. Use localhost for this computer or a private LAN address for a paired phone. Stop it when finished.")); companion.Children.Add(Ui.Caption("Bind address")); companion.Children.Add(address); companion.Children.Add(Ui.Caption("Port")); companion.Children.Add(port);
            companion.Children.Add(Ui.Actions(Ui.Action("Start companion", () => { companionServer?.Dispose(); companionServer = new CompanionServer(); companionServer.Update(IntegrationData.CompanionSnapshot(library)); companionServer.Start(IPAddress.Parse(address.Text), (int)port.Value.GetValueOrDefault()); settings.CompanionPort = companionServer.Port; Store.Save(library); connection.Text = "Paired address: http://" + address.Text + ":" + companionServer.Port + "/?pair=" + companionServer.PairCode + "\nClosing Library tools stops the companion."; }), Ui.Action("Stop companion", () => { companionServer?.Dispose(); companionServer = null; connection.Text = "Companion stopped."; }))); companion.Children.Add(connection);
            var tabs = new TabControl { ItemsSource = new[] { new TabItem { Header = "Achievements", Content = new ScrollViewer { Content = achievements } }, new TabItem { Header = "Providers and extensions", Content = new ScrollViewer { Content = providers } }, new TabItem { Header = "Companion", Content = new ScrollViewer { Content = companion } } } };
            var refresh = new Avalonia.Threading.DispatcherTimer { Interval = TimeSpan.FromSeconds(2) };
            refresh.Tick += delegate { companionServer?.Update(IntegrationData.CompanionSnapshot(library)); }; refresh.Start();
            dialog.Body = tabs; try { await dialog.Present(this); } finally { refresh.Stop(); companionServer?.Dispose(); companionServer = null; }
        }
    }
}
