using System;using System.Linq;using System.Text.Json;using EmulatorHub;
class SchemaTests {
 static int checks;static void Check(bool ok,string message){if(!ok)throw new Exception(message);checks++;}
 static void Preserved(JsonElement before,JsonElement after,string path){
  if(before.ValueKind==JsonValueKind.Object){foreach(var field in before.EnumerateObject()){JsonElement retained;Check(after.TryGetProperty(field.Name,out retained),"missing field "+path+"."+field.Name);Preserved(field.Value,retained,path+"."+field.Name);}}
  else if(before.ValueKind==JsonValueKind.Array){Check(before.GetArrayLength()==after.GetArrayLength(),"array length "+path);for(int i=0;i<before.GetArrayLength();i++)Preserved(before[i],after[i],path+"["+i+"]");}
  else Check(before.ToString()==after.ToString(),"changed field "+path);
 }
 static int Main(){try{
  const string fixture=@"{""Version"":2,""SavedDataRoot"":""/fixture/FishBowlData"",""SavedPortableRoot"":""/fixture"",""RemovalHistory"":[{""Games"":[{""Id"":""removed"",""TitleIsCustom"":true,""ArtworkPath"":""cover.png""}],""Collections"":{""c1"":[""removed""]},""Queue"":[""removed""],""Assignments"":[{""GameId"":""g1"",""EmulatorId"":""e1""}]}],""RemovedGamePaths"":[""excluded.nds""],""Enhancements"":{""TextPercent"":150,""Shortcuts"":{""Home"":""Control, H""}},""Cosmetics"":{""CornerRadius"":8},""Experience"":{""HomeCards"":[""Continue playing""]},""Immersion"":{""Roomier"":true},""Theme"":{""Name"":""Deep Ocean"",""ExpandedHomeCards"":[""Pinned games""],""AppIconColor"":""Match accent"",""LastSeenBuild"":""1.24"",""FutureTheme"":{""Shade"":7}},""Games"":[{""Id"":""g1"",""Title"":""Fixture game"",""TitleIsCustom"":true,""RequiresEmulatorAssignment"":true,""Pinned"":true,""PlayStatus"":""Playing"",""SaveAssociations"":[{""Path"":""fixture.sav""}]}],""Emulators"":[{""Id"":""e1"",""Name"":""Fixture emulator"",""FutureEmulator"":{""Enabled"":true},""LaunchProfiles"":[{""Id"":""p1"",""Name"":""Default"",""FutureProfile"":42}],""Builds"":[{""Id"":""b1"",""FutureBuild"":""preserve""}]}],""Collections"":[{""Id"":""c1"",""FutureCollection"":true}],""Links"":[{""Id"":""l1"",""FutureLink"":""x""}],""Converters"":[{""Id"":""v1"",""FutureConverter"":3}]}";
  var data=Json.Deserialize<LibraryData>(fixture);var roundtrip=Json.Serialize(data);
  using(var before=JsonDocument.Parse(fixture))using(var after=JsonDocument.Parse(roundtrip))Preserved(before.RootElement,after.RootElement,"library");
  data.Games[0].Title="Linux edit";data.Emulators[0].Favorite=true;
  using(var edited=JsonDocument.Parse(Json.Serialize(data))){var doc=edited.RootElement;JsonElement unwanted;Check(doc.GetProperty("Games")[0].GetProperty("Title").GetString()=="Linux edit","known game edits lost");Check(doc.GetProperty("Games")[0].GetProperty("Pinned").GetBoolean(),"unknown nested game field lost during edit");Check(doc.GetProperty("Theme").GetProperty("LastSeenBuild").GetString()=="1.24","unknown theme field lost during edit");Check(doc.GetProperty("Emulators")[0].GetProperty("Favorite").GetBoolean(),"known emulator edit lost");Check(doc.GetProperty("Enhancements").GetProperty("TextPercent").GetInt32()==150,"unknown top-level settings lost during edit");Check(!doc.TryGetProperty("AdditionalFields",out unwanted),"extension data leaked into library format");}
  var typed=Json.Deserialize<LibraryData>(fixture);Check(typed.Games[0].Pinned&&typed.Games[0].PlayStatus=="Playing","Linux reads newer Windows game fields as typed data");
  Check(typed.Games[0].TitleIsCustom && typed.RemovedGamePaths.SequenceEqual(new[]{"excluded.nds"}),"Windows title preference and scan exclusions survive Linux roundtrip");
  Check(typed.Games[0].RequiresEmulatorAssignment && typed.RemovalHistory[0].Games[0].Id=="removed" && typed.SavedPortableRoot=="/fixture", "recovery and portable metadata survive Linux roundtrip");
  const string expansion=@"{""Theme"":{""HomeCardOrder"":[""Continue playing""],""HiddenHomeCards"":[""Tools""],""RestrainedAccents"":true,""CoverAspect"":""Portrait"",""ControlDensity"":""Compact"",""ColorHarmony"":""Harmonized""},""GameTools"":{""SteamLibraryFolders"":[""/fixture/Steam""],""FutureTools"":17},""Integrations"":{""AchievementUser"":""fixture"",""Achievements"":[{""GameID"":1,""Title"":""Game"",""FutureAchievement"":true}],""Extensions"":[{""Id"":""catalog"",""Kind"":""Metadata"",""CatalogPath"":""catalog.json"",""FutureExtension"":2}],""FutureIntegration"":""retained""},""Games"":[{""Tools"":{""MediaLinks"":[{""Title"":""Manual"",""Path"":""manual.pdf"",""FutureMedia"":3}],""ModProfiles"":[{""Id"":""mod"",""FutureMod"":4}],""FutureGameTools"":5}}],""Hub"":{""Adapters"":[{""ExtensionId"":""adapter"",""FutureAdapter"":6}]}}";
  var expanded=Json.Deserialize<LibraryData>(expansion);expanded.Games[0].Title="Edited";
  Check(expanded.Theme.ControlDensity=="Compact" && expanded.Theme.ColorHarmony=="Harmonized","Linux reads Windows density and harmony as typed settings");
  var settingsCopy=Json.Deserialize<ThemeSettings>(Json.Serialize(expanded.Theme));
  Check(settingsCopy.ControlDensity=="Compact" && settingsCopy.ColorHarmony=="Harmonized","Linux settings/profile clone preserves Windows density and harmony");
  expanded.Theme=settingsCopy;
  using(var before=JsonDocument.Parse(expansion))using(var after=JsonDocument.Parse(Json.Serialize(expanded)))Preserved(before.RootElement,after.RootElement,"expansion");
  var old=Json.Deserialize<LibraryData>("{\"Version\":1,\"Games\":[],\"Emulators\":[],\"Theme\":{\"Name\":\"Forest\"}}");Check(old.Version==1&&old.Theme.Name=="Forest","old library fixture rejected");
  const string browser=@"{""Browser"":{""Engine"":""Firefox"",""Executable"":""browser.exe"",""HomePage"":""about:blank"",""FutureBrowser"":1},""Emulators"":[{""Id"":""view"",""PlayView"":{""ShowControls"":false,""Top"":30,""Bottom"":20,""Left"":5,""Right"":7,""FutureView"":2}}]}";
  var web=Json.Deserialize<LibraryData>(browser);Check(web.Browser.Engine=="Firefox"&&web.Emulators[0].PlayView.Top==30,"browser and game-view fields are optional typed settings");
  using(var before=JsonDocument.Parse(browser))using(var after=JsonDocument.Parse(Json.Serialize(web)))Preserved(before.RootElement,after.RootElement,"browser");
  Console.WriteLine("PASS: "+checks+" schema preservation checks");return 0;
 }catch(Exception e){Console.WriteLine(e);return 1;}}
}
